# Generated by Django 5.2.16 on 2026-07-27 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('rule_type', models.CharField(choices=[('compensation', 'Compensation'), ('eligibility', 'Eligibility'), ('root_cause', 'Root cause'), ('routing', 'Routing'), ('validation', 'Validation')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], default='draft', max_length=24)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='datasets.datasnapshot')),
            ],
            options={
                'db_table': 'rules_rule',
                'ordering': ['data_snapshot', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RuleChangeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_set_code', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied')], default='draft', max_length=24)),
                ('reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rule_change_sets', to=settings.AUTH_USER_MODEL)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_change_sets', to='datasets.datasnapshot')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_rule_change_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rules_change_set',
                'ordering': ['data_snapshot', '-created_at', 'change_set_code'],
            },
        ),
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=24)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('condition_tree', models.JSONField(blank=True, default=dict)),
                ('action_config', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('change_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_versions', to='rules.rulechangeset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rule_versions', to=settings.AUTH_USER_MODEL)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_versions', to='datasets.datasnapshot')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='rules.rule')),
            ],
            options={
                'db_table': 'rules_rule_version',
                'ordering': ['rule__code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='RuleTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=24)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('expected_output', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_test_cases', to='datasets.datasnapshot')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='rules.rule')),
                ('rule_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='rules.ruleversion')),
            ],
            options={
                'db_table': 'rules_test_case',
                'ordering': ['rule__code', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='rule',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'code'), name='unique_rule_code_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='rulechangeset',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'change_set_code'), name='unique_rule_change_set_code_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='ruleversion',
            constraint=models.UniqueConstraint(fields=('rule', 'version'), name='unique_rule_version_number'),
        ),
        migrations.AddConstraint(
            model_name='ruleversion',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='rule_version_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='ruletestcase',
            constraint=models.UniqueConstraint(fields=('rule', 'name'), name='unique_rule_test_case_name'),
        ),
    ]
