# Generated by Django 5.2.16 on 2026-07-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['data_snapshot', 'code'], 'verbose_name': 'Kural', 'verbose_name_plural': 'Kurallar'},
        ),
        migrations.AlterModelOptions(
            name='rulechangeset',
            options={'ordering': ['data_snapshot', '-created_at', 'change_set_code'], 'verbose_name': 'Kural değişiklik seti', 'verbose_name_plural': 'Kural değişiklik setleri'},
        ),
        migrations.AlterModelOptions(
            name='ruletestcase',
            options={'ordering': ['rule__code', 'name'], 'verbose_name': 'Kural test senaryosu', 'verbose_name_plural': 'Kural test senaryoları'},
        ),
        migrations.AlterModelOptions(
            name='ruleversion',
            options={'ordering': ['rule__code', '-version'], 'verbose_name': 'Kural versiyonu', 'verbose_name_plural': 'Kural versiyonları'},
        ),
    ]
