# Generated by Django 5.2.16 on 2026-07-29 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0003_groundtruthcase'),
        ('rules', '0002_alter_rule_options_alter_rulechangeset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='conflict_group',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='rule',
            name='family',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('eligibility', 'Eligibility'), ('exclusion', 'Exclusion'), ('broadband', 'Broadband'), ('metro_sla', 'Metro/SLA'), ('failover', 'Failover'), ('modifier', 'Modifier'), ('sla_evidence', 'SLA evidence'), ('manual_review', 'Manual review'), ('final_policy', 'Final policy')], default='legacy', max_length=32),
        ),
        migrations.AddField(
            model_name='ruleversion',
            name='action_type',
            field=models.CharField(choices=[('legacy_monthly_price_percentage', 'Legacy monthly price percentage'), ('pass', 'Pass'), ('ineligible', 'Ineligible'), ('manual_review', 'Manual review'), ('tiered_percentage', 'Tiered percentage'), ('prorated', 'Prorated'), ('sla_matrix', 'SLA matrix'), ('multiplier', 'Multiplier'), ('cap_floor', 'Cap/floor'), ('evidence_only', 'Evidence only')], default='legacy_monthly_price_percentage', max_length=40),
        ),
        migrations.AddField(
            model_name='ruleversion',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ruleversion',
            name='change_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ruleversion',
            name='price_basis',
            field=models.CharField(choices=[('contracted_monthly_price', 'Contracted monthly price'), ('billed_recurring_amount', 'Billed recurring amount'), ('campaign_adjusted_recurring_amount', 'Campaign adjusted recurring amount'), ('package_list_price', 'Package list price')], default='contracted_monthly_price', max_length=48),
        ),
        migrations.AddField(
            model_name='ruleversion',
            name='priority',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='ruleversion',
            name='stackable',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('version', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=160)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('change_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_sets', to='datasets.datasnapshot')),
            ],
            options={
                'verbose_name': 'Kural seti',
                'verbose_name_plural': 'Kural setleri',
                'db_table': 'rules_rule_set',
                'ordering': ['data_snapshot', 'code', '-version'],
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='rule_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='rules.ruleset'),
        ),
        migrations.AddConstraint(
            model_name='ruleset',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'code', 'version'), name='unique_rule_set_code_version_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='ruleset',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='rule_set_effective_range'),
        ),
    ]
