# Generated by Django 5.2.16 on 2026-08-17 06:32

import django.db.models.deletion
from django.db import migrations, models

import apps.simulation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0003_groundtruthcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario_code', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=160)),
                ('scenario_type', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('default_parameters', models.JSONField(blank=True, default=dict)),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulation_scenarios', to='datasets.datasnapshot')),
            ],
            options={
                'db_table': 'simulation_scenario',
                'ordering': ['source_snapshot', 'scenario_code'],
            },
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_code', models.CharField(default=apps.simulation.models.generate_simulation_run_code, max_length=48, unique=True)),
                ('comparison_role', models.CharField(choices=[('baseline', 'Baseline'), ('candidate', 'Candidate')], max_length=16)),
                ('replay_identity', models.CharField(db_index=True, default=apps.simulation.models.generate_replay_identity, max_length=48)),
                ('deterministic_seed', models.CharField(max_length=160)),
                ('virtual_clock', models.DateTimeField()),
                ('speed_multiplier', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='draft', max_length=16)),
                ('input_parameters', models.JSONField(blank=True, default=dict)),
                ('lifecycle_context', models.JSONField(blank=True, default=dict)),
                ('baseline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_runs', to='simulation.simulationrun')),
                ('replay_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replays', to='simulation.simulationrun')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulation_runs', to='datasets.datasnapshot')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='simulation.simulationscenario')),
            ],
            options={
                'db_table': 'simulation_run',
                'ordering': ['-created_at', 'run_code'],
            },
        ),
        migrations.CreateModel(
            name='SimulationRunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('event_code', models.CharField(max_length=120)),
                ('event_type', models.CharField(max_length=80)),
                ('virtual_occurred_at', models.DateTimeField()),
                ('event_context', models.JSONField(blank=True, default=dict)),
                ('simulation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='simulation.simulationrun')),
            ],
            options={
                'db_table': 'simulation_run_event',
                'ordering': ['simulation_run', 'sequence'],
                'indexes': [models.Index(fields=['simulation_run', 'virtual_occurred_at'], name='sim_event_run_clock_idx')],
                'constraints': [models.UniqueConstraint(fields=('simulation_run', 'sequence'), name='simulation_event_run_sequence_uniq'), models.UniqueConstraint(fields=('simulation_run', 'event_code'), name='simulation_event_run_code_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='simulationscenario',
            index=models.Index(fields=['source_snapshot', 'scenario_type'], name='sim_scenario_snap_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='simulationscenario',
            constraint=models.UniqueConstraint(fields=('source_snapshot', 'scenario_code'), name='simulation_scenario_snapshot_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=models.Index(fields=['source_snapshot', 'status', 'created_at'], name='sim_run_snap_status_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=models.Index(fields=['replay_identity', 'created_at'], name='sim_run_replay_idx'),
        ),
        migrations.AddConstraint(
            model_name='simulationrun',
            constraint=models.CheckConstraint(condition=models.Q(('speed_multiplier__in', (1, 10, 60))), name='simulation_run_supported_speed'),
        ),
        migrations.AddConstraint(
            model_name='simulationrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('baseline_run__isnull', True), ('comparison_role', 'baseline')), models.Q(('baseline_run__isnull', False), ('comparison_role', 'candidate')), _connector='OR'), name='simulation_run_baseline_candidate_shape'),
        ),
        migrations.AddConstraint(
            model_name='simulationrun',
            constraint=models.CheckConstraint(condition=models.Q(('pk', models.F('baseline_run')), _negated=True), name='simulation_run_no_self_baseline'),
        ),
        migrations.AddConstraint(
            model_name='simulationrun',
            constraint=models.CheckConstraint(condition=models.Q(('pk', models.F('replay_of')), _negated=True), name='simulation_run_no_self_replay'),
        ),
    ]
