# Generated by Django 5.2.16 on 2026-08-18 16:24

import django.db.models.deletion
from django.db import migrations, models

import apps.simulation.models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0003_groundtruthcase'),
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_code', models.CharField(default=apps.simulation.models.generate_simulation_evidence_code, max_length=48)),
                ('evidence_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('simulation_run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='simulation_evidence', to='simulation.simulationrun')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulation_evidence_records', to='datasets.datasnapshot')),
            ],
            options={
                'db_table': 'simulation_evidence',
                'ordering': ['-created_at', 'evidence_code'],
                'indexes': [models.Index(fields=['source_snapshot', 'finalized', 'created_at'], name='sim_evidence_snap_final_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_snapshot', 'evidence_code'), name='simulation_evidence_snapshot_code_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('finalized', False), ('finalized_at__isnull', True)), models.Q(('finalized', True), ('finalized_at__isnull', False)), _connector='OR'), name='simulation_evidence_finalization_timestamp')],
            },
        ),
    ]
