# Generated by Django 5.2.16 on 2026-07-27 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('network', '0003_remove_networkdevice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], max_length=24)),
                ('category', models.CharField(choices=[('access', 'Access'), ('transport', 'Transport'), ('core', 'Core'), ('power', 'Power'), ('quality', 'Quality')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_types', to='datasets.datasnapshot')),
            ],
            options={
                'db_table': 'operations_alarm_type',
                'ordering': ['data_snapshot', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alarm_id', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], max_length=24)),
                ('status', models.CharField(choices=[('open', 'Open'), ('cleared', 'Cleared'), ('suppressed', 'Suppressed')], default='open', max_length=24)),
                ('detected_at', models.DateTimeField()),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='datasets.datasnapshot')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alarms', to='network.networkdevice')),
                ('alarm_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alarms', to='operations.alarmtype')),
            ],
            options={
                'db_table': 'operations_alarm',
                'ordering': ['data_snapshot', '-detected_at', 'alarm_id'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=24)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], max_length=24)),
                ('root_cause_category', models.CharField(choices=[('unknown', 'Unknown'), ('bng_failure', 'BNG failure'), ('los', 'Loss of signal'), ('power', 'Power'), ('fiber_cut', 'Fiber cut'), ('configuration', 'Configuration')], default='unknown', max_length=40)),
                ('root_cause_summary', models.CharField(blank=True, max_length=240)),
                ('detected_at', models.DateTimeField()),
                ('started_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='datasets.datasnapshot')),
                ('primary_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_incidents', to='network.networkdevice')),
            ],
            options={
                'db_table': 'operations_incident',
                'ordering': ['data_snapshot', '-started_at', 'incident_number'],
            },
        ),
        migrations.CreateModel(
            name='IncidentAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('supporting', 'Supporting'), ('correlated', 'Correlated')], default='correlated', max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_alarms', to='operations.alarm')),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_alarms', to='datasets.datasnapshot')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_alarms', to='operations.incident')),
            ],
            options={
                'db_table': 'operations_incident_alarm',
                'ordering': ['data_snapshot', 'incident__incident_number', 'alarm__alarm_id'],
            },
        ),
        migrations.CreateModel(
            name='OperationalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_code', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('config_change', 'Config change'), ('manual_intervention', 'Manual intervention'), ('auto_recovery', 'Auto recovery'), ('note', 'Note')], max_length=40)),
                ('occurred_at', models.DateTimeField()),
                ('source', models.CharField(blank=True, max_length=80)),
                ('summary', models.CharField(max_length=240)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_events', to='datasets.datasnapshot')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_events', to='network.networkdevice')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_events', to='operations.incident')),
            ],
            options={
                'db_table': 'operations_operational_event',
                'ordering': ['data_snapshot', '-occurred_at', 'event_code'],
            },
        ),
        migrations.CreateModel(
            name='Outage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outage_code', models.CharField(max_length=100)),
                ('outage_type', models.CharField(choices=[('device', 'Device'), ('link', 'Link'), ('access', 'Access'), ('planned', 'Planned')], max_length=24)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='open', max_length=24)),
                ('root_cause_category', models.CharField(choices=[('unknown', 'Unknown'), ('bng_failure', 'BNG failure'), ('los', 'Loss of signal'), ('power', 'Power'), ('fiber_cut', 'Fiber cut'), ('configuration', 'Configuration')], default='unknown', max_length=40)),
                ('root_cause_summary', models.CharField(blank=True, max_length=240)),
                ('detected_at', models.DateTimeField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('impact_scope', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outages', to='datasets.datasnapshot')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outages', to='operations.incident')),
                ('source_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outages', to='network.networkdevice')),
            ],
            options={
                'db_table': 'operations_outage',
                'ordering': ['data_snapshot', '-started_at', 'outage_code'],
            },
        ),
        migrations.CreateModel(
            name='QualityMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_type', models.CharField(choices=[('latency_ms', 'Latency ms'), ('jitter_ms', 'Jitter ms'), ('packet_loss_percent', 'Packet loss percent'), ('availability_percent', 'Availability percent')], max_length=40)),
                ('measured_at', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit', models.CharField(max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_measurements', to='datasets.datasnapshot')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_measurements', to='network.networkdevice')),
            ],
            options={
                'db_table': 'operations_quality_measurement',
                'ordering': ['data_snapshot', '-measured_at', 'device__code', 'metric_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='alarmtype',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'code'), name='unique_alarm_type_code_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='alarm',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'alarm_id'), name='unique_alarm_id_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='alarm',
            constraint=models.CheckConstraint(condition=models.Q(('cleared_at__isnull', True), ('cleared_at__gt', models.F('detected_at')), _connector='OR'), name='alarm_clear_time_after_detected_time'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'incident_number'), name='unique_incident_number_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(condition=models.Q(('resolved_at__isnull', True), ('resolved_at__gt', models.F('started_at')), _connector='OR'), name='incident_resolved_after_started'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(condition=models.Q(('closed_at__isnull', True), ('closed_at__gt', models.F('started_at')), _connector='OR'), name='incident_closed_after_started'),
        ),
        migrations.AddConstraint(
            model_name='incidentalarm',
            constraint=models.UniqueConstraint(fields=('incident', 'alarm'), name='unique_alarm_per_incident'),
        ),
        migrations.AddConstraint(
            model_name='operationalevent',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'event_code'), name='unique_operational_event_code_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='outage',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'outage_code'), name='unique_outage_code_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='outage',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gt', models.F('started_at')), _connector='OR'), name='outage_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='outage',
            constraint=models.CheckConstraint(condition=models.Q(('resolved_at__isnull', True), ('resolved_at__gte', models.F('started_at')), _connector='OR'), name='outage_resolved_at_or_after_start'),
        ),
        migrations.AddConstraint(
            model_name='qualitymeasurement',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'device', 'metric_type', 'measured_at'), name='unique_quality_measurement_per_metric_time'),
        ),
    ]
