# Generated by Django 5.2.16 on 2026-07-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarm',
            options={'ordering': ['data_snapshot', '-detected_at', 'alarm_id'], 'verbose_name': 'Alarm', 'verbose_name_plural': 'Alarmlar'},
        ),
        migrations.AlterModelOptions(
            name='alarmtype',
            options={'ordering': ['data_snapshot', 'code'], 'verbose_name': 'Alarm tipi', 'verbose_name_plural': 'Alarm tipleri'},
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['data_snapshot', '-started_at', 'incident_number'], 'verbose_name': 'Olay', 'verbose_name_plural': 'Olaylar'},
        ),
        migrations.AlterModelOptions(
            name='incidentalarm',
            options={'ordering': ['data_snapshot', 'incident__incident_number', 'alarm__alarm_id'], 'verbose_name': 'Olay alarmı', 'verbose_name_plural': 'Olay alarmları'},
        ),
        migrations.AlterModelOptions(
            name='operationalevent',
            options={'ordering': ['data_snapshot', '-occurred_at', 'event_code'], 'verbose_name': 'Operasyon olayı', 'verbose_name_plural': 'Operasyon olayları'},
        ),
        migrations.AlterModelOptions(
            name='outage',
            options={'ordering': ['data_snapshot', '-started_at', 'outage_code'], 'verbose_name': 'Kesinti', 'verbose_name_plural': 'Kesintiler'},
        ),
        migrations.AlterModelOptions(
            name='qualitymeasurement',
            options={'ordering': ['data_snapshot', '-measured_at', 'device__code', 'metric_type'], 'verbose_name': 'Kalite ölçümü', 'verbose_name_plural': 'Kalite ölçümleri'},
        ),
    ]
