# Generated by Django 5.2.16 on 2026-07-29 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "customers",
            "0006_remove_subscriptionconnection_unique_open_active_connection_per_subscription_and_more",
        ),
        ("datasets", "0003_groundtruthcase"),
        ("network", "0007_alter_networkdevice_device_type_failuredomain_and_more"),
        ("operations", "0002_alter_alarm_options_alter_alarmtype_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlarmTypeAllowedSourceKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("device", "Device"),
                            ("network_link", "Network link"),
                            ("network_port", "Network port"),
                            ("line_connection", "Line connection"),
                            ("failure_domain", "Failure domain"),
                            ("subscription_connection", "Subscription connection"),
                        ],
                        max_length=40,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alarm tipi kaynak türü",
                "verbose_name_plural": "Alarm tipi kaynak türleri",
                "db_table": "operations_alarm_type_allowed_source_kind",
                "ordering": ["data_snapshot", "alarm_type__code", "source_kind"],
            },
        ),
        migrations.CreateModel(
            name="AlarmTypeSupportedDeviceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("bng", "BNG"),
                            ("metro_aggregation", "Metro aggregation"),
                            ("olt", "OLT"),
                            ("dslam", "DSLAM"),
                            ("access_node", "Access node"),
                        ],
                        max_length=24,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alarm tipi cihaz türü",
                "verbose_name_plural": "Alarm tipi cihaz türleri",
                "db_table": "operations_alarm_type_supported_device_type",
                "ordering": ["data_snapshot", "alarm_type__code", "device_type"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference_code", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("overrun", "Overrun"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=24,
                    ),
                ),
                ("planned_start_at", models.DateTimeField()),
                ("planned_end_at", models.DateTimeField()),
                ("actual_start_at", models.DateTimeField(blank=True, null=True)),
                ("actual_end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expected_impact_class",
                    models.CharField(
                        choices=[
                            ("full_outage", "Full outage"),
                            ("partial_outage", "Partial outage"),
                            ("short_interruption", "Short interruption"),
                            ("degradation", "Degradation"),
                            ("protection_loss", "Protection loss"),
                            ("no_direct_customer_impact", "No direct customer impact"),
                            ("unknown", "Unknown"),
                        ],
                        default="no_direct_customer_impact",
                        max_length=40,
                    ),
                ),
                (
                    "actual_impact_class",
                    models.CharField(
                        choices=[
                            ("full_outage", "Full outage"),
                            ("partial_outage", "Partial outage"),
                            ("short_interruption", "Short interruption"),
                            ("degradation", "Degradation"),
                            ("protection_loss", "Protection loss"),
                            ("no_direct_customer_impact", "No direct customer impact"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=40,
                    ),
                ),
                ("overrun_minutes", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Bakım penceresi",
                "verbose_name_plural": "Bakım pencereleri",
                "db_table": "operations_maintenance_window",
                "ordering": ["data_snapshot", "planned_start_at", "reference_code"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceWindowDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bakım cihaz kapsamı",
                "verbose_name_plural": "Bakım cihaz kapsamları",
                "db_table": "operations_maintenance_window_device",
                "ordering": ["data_snapshot", "maintenance_window__reference_code", "device__code"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceWindowNetworkLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bakım ağ bağlantısı kapsamı",
                "verbose_name_plural": "Bakım ağ bağlantısı kapsamları",
                "db_table": "operations_maintenance_window_network_link",
                "ordering": [
                    "data_snapshot",
                    "maintenance_window__reference_code",
                    "network_link__link_code",
                ],
            },
        ),
        migrations.RemoveConstraint(
            model_name="qualitymeasurement",
            name="unique_quality_measurement_per_metric_time",
        ),
        migrations.AddField(
            model_name="alarm",
            name="acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alarm",
            name="deduplication_key",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="alarm",
            name="failure_domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alarms",
                to="network.failuredomain",
            ),
        ),
        migrations.AddField(
            model_name="alarm",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alarm",
            name="line_connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alarms",
                to="network.lineconnection",
            ),
        ),
        migrations.AddField(
            model_name="alarm",
            name="network_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alarms",
                to="network.networklink",
            ),
        ),
        migrations.AddField(
            model_name="alarm",
            name="network_port",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alarms",
                to="network.networkport",
            ),
        ),
        migrations.AddField(
            model_name="alarm",
            name="occurrence_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="alarm",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alarm",
            name="recurrence_group_key",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="alarm",
            name="subscription_connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alarms",
                to="customers.subscriptionconnection",
            ),
        ),
        migrations.AddField(
            model_name="alarm",
            name="suppression_reason",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="alarmtype",
            name="auto_clear_policy",
            field=models.CharField(
                choices=[
                    ("auto", "Auto"),
                    ("manual", "Manual"),
                    ("auto_or_manual", "Auto or manual"),
                ],
                default="auto_or_manual",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="alarmtype",
            name="correlation_family",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="alarmtype",
            name="deduplication_window_seconds",
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name="alarmtype",
            name="default_incident_type",
            field=models.CharField(
                choices=[
                    ("network_outage", "Network outage"),
                    ("service_degradation", "Service degradation"),
                    ("protection_event", "Protection event"),
                    ("intermittent", "Intermittent"),
                    ("planned_maintenance", "Planned maintenance"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="alarmtype",
            name="is_root_candidate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alarmtype",
            name="probable_cause_family",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="alarmtype",
            name="service_impact_class",
            field=models.CharField(
                choices=[
                    ("full_outage", "Full outage"),
                    ("partial_outage", "Partial outage"),
                    ("short_interruption", "Short interruption"),
                    ("degradation", "Degradation"),
                    ("protection_loss", "Protection loss"),
                    ("no_direct_customer_impact", "No direct customer impact"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="correlation_method",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="incident",
            name="failover_result",
            field=models.CharField(
                choices=[
                    ("hitless", "Hitless"),
                    ("near_hitless", "Near-hitless"),
                    ("short_interruption", "Short interruption"),
                    ("degraded", "Degraded"),
                    ("failed", "Failed"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="incident_type",
            field=models.CharField(
                choices=[
                    ("network_outage", "Network outage"),
                    ("service_degradation", "Service degradation"),
                    ("protection_event", "Protection event"),
                    ("intermittent", "Intermittent"),
                    ("planned_maintenance", "Planned maintenance"),
                    ("unknown", "Unknown"),
                ],
                default="network_outage",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="service_impact_class",
            field=models.CharField(
                choices=[
                    ("full_outage", "Full outage"),
                    ("partial_outage", "Partial outage"),
                    ("short_interruption", "Short interruption"),
                    ("degradation", "Degradation"),
                    ("protection_loss", "Protection loss"),
                    ("no_direct_customer_impact", "No direct customer impact"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="transition_duration_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outage",
            name="impact_type",
            field=models.CharField(
                choices=[
                    ("full_outage", "Full outage"),
                    ("partial_outage", "Partial outage"),
                    ("short_interruption", "Short interruption"),
                    ("degradation", "Degradation"),
                    ("protection_loss", "Protection loss"),
                    ("no_direct_customer_impact", "No direct customer impact"),
                    ("unknown", "Unknown"),
                ],
                default="full_outage",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="outage",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outage",
            name="transition_duration_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="qualitymeasurement",
            name="line_connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quality_measurements",
                to="network.lineconnection",
            ),
        ),
        migrations.AddField(
            model_name="qualitymeasurement",
            name="network_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quality_measurements",
                to="network.networklink",
            ),
        ),
        migrations.AddField(
            model_name="qualitymeasurement",
            name="subscription_connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quality_measurements",
                to="customers.subscriptionconnection",
            ),
        ),
        migrations.AlterField(
            model_name="alarm",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alarms",
                to="network.networkdevice",
            ),
        ),
        migrations.AlterField(
            model_name="alarm",
            name="severity",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("minor", "Minor"),
                    ("major", "Major"),
                    ("critical", "Critical"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="alarmtype",
            name="severity",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("minor", "Minor"),
                    ("major", "Major"),
                    ("critical", "Critical"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="severity",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("minor", "Minor"),
                    ("major", "Major"),
                    ("critical", "Critical"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="qualitymeasurement",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quality_measurements",
                to="network.networkdevice",
            ),
        ),
        migrations.AlterField(
            model_name="qualitymeasurement",
            name="metric_type",
            field=models.CharField(
                choices=[
                    ("latency_ms", "Latency ms"),
                    ("jitter_ms", "Jitter ms"),
                    ("packet_loss_percent", "Packet loss percent"),
                    ("availability_percent", "Availability percent"),
                    ("bandwidth_utilization_percent", "Bandwidth utilization percent"),
                ],
                max_length=40,
            ),
        ),
        migrations.AddConstraint(
            model_name="alarm",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status", "open"), models.Q(("deduplication_key", ""), _negated=True)
                ),
                fields=("data_snapshot", "alarm_type", "deduplication_key"),
                name="unique_open_alarm_per_deduplication_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="alarm",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("device__isnull", False),
                        ("network_link__isnull", True),
                        ("network_port__isnull", True),
                        ("line_connection__isnull", True),
                        ("failure_domain__isnull", True),
                        ("subscription_connection__isnull", True),
                    ),
                    models.Q(
                        ("device__isnull", True),
                        ("network_link__isnull", False),
                        ("network_port__isnull", True),
                        ("line_connection__isnull", True),
                        ("failure_domain__isnull", True),
                        ("subscription_connection__isnull", True),
                    ),
                    models.Q(
                        ("device__isnull", True),
                        ("network_link__isnull", True),
                        ("network_port__isnull", False),
                        ("line_connection__isnull", True),
                        ("failure_domain__isnull", True),
                        ("subscription_connection__isnull", True),
                    ),
                    models.Q(
                        ("device__isnull", True),
                        ("network_link__isnull", True),
                        ("network_port__isnull", True),
                        ("line_connection__isnull", False),
                        ("failure_domain__isnull", True),
                        ("subscription_connection__isnull", True),
                    ),
                    models.Q(
                        ("device__isnull", True),
                        ("network_link__isnull", True),
                        ("network_port__isnull", True),
                        ("line_connection__isnull", True),
                        ("failure_domain__isnull", False),
                        ("subscription_connection__isnull", True),
                    ),
                    models.Q(
                        ("device__isnull", True),
                        ("network_link__isnull", True),
                        ("network_port__isnull", True),
                        ("line_connection__isnull", True),
                        ("failure_domain__isnull", True),
                        ("subscription_connection__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="alarm_has_exactly_one_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="alarm",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "cleared"), _negated=True),
                    ("cleared_at__isnull", False),
                    _connector="OR",
                ),
                name="cleared_alarm_requires_cleared_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="qualitymeasurement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("device__isnull", False)),
                fields=("data_snapshot", "device", "metric_type", "measured_at"),
                name="unique_quality_measurement_per_metric_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="qualitymeasurement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("network_link__isnull", False)),
                fields=("data_snapshot", "network_link", "metric_type", "measured_at"),
                name="unique_quality_measurement_per_link_metric_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="qualitymeasurement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("line_connection__isnull", False)),
                fields=("data_snapshot", "line_connection", "metric_type", "measured_at"),
                name="unique_quality_measurement_per_line_metric_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="qualitymeasurement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subscription_connection__isnull", False)),
                fields=("data_snapshot", "subscription_connection", "metric_type", "measured_at"),
                name="unique_quality_measurement_per_sub_conn_metric_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="qualitymeasurement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("device__isnull", False),
                        ("network_link__isnull", True),
                        ("line_connection__isnull", True),
                        ("subscription_connection__isnull", True),
                    ),
                    models.Q(
                        ("device__isnull", True),
                        ("network_link__isnull", False),
                        ("line_connection__isnull", True),
                        ("subscription_connection__isnull", True),
                    ),
                    models.Q(
                        ("device__isnull", True),
                        ("network_link__isnull", True),
                        ("line_connection__isnull", False),
                        ("subscription_connection__isnull", True),
                    ),
                    models.Q(
                        ("device__isnull", True),
                        ("network_link__isnull", True),
                        ("line_connection__isnull", True),
                        ("subscription_connection__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="quality_measurement_has_exactly_one_source",
            ),
        ),
        migrations.AddField(
            model_name="alarmtypeallowedsourcekind",
            name="alarm_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allowed_source_kinds",
                to="operations.alarmtype",
            ),
        ),
        migrations.AddField(
            model_name="alarmtypeallowedsourcekind",
            name="data_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alarm_type_allowed_source_kinds",
                to="datasets.datasnapshot",
            ),
        ),
        migrations.AddField(
            model_name="alarmtypesupporteddevicetype",
            name="alarm_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supported_device_types",
                to="operations.alarmtype",
            ),
        ),
        migrations.AddField(
            model_name="alarmtypesupporteddevicetype",
            name="data_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alarm_type_supported_device_types",
                to="datasets.datasnapshot",
            ),
        ),
        migrations.AddField(
            model_name="maintenancewindow",
            name="data_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_windows",
                to="datasets.datasnapshot",
            ),
        ),
        migrations.AddField(
            model_name="maintenancewindow",
            name="linked_incident",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_windows",
                to="operations.incident",
            ),
        ),
        migrations.AddField(
            model_name="maintenancewindowdevice",
            name="data_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_window_devices",
                to="datasets.datasnapshot",
            ),
        ),
        migrations.AddField(
            model_name="maintenancewindowdevice",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_windows",
                to="network.networkdevice",
            ),
        ),
        migrations.AddField(
            model_name="maintenancewindowdevice",
            name="maintenance_window",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_scopes",
                to="operations.maintenancewindow",
            ),
        ),
        migrations.AddField(
            model_name="maintenancewindownetworklink",
            name="data_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_window_network_links",
                to="datasets.datasnapshot",
            ),
        ),
        migrations.AddField(
            model_name="maintenancewindownetworklink",
            name="maintenance_window",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="network_link_scopes",
                to="operations.maintenancewindow",
            ),
        ),
        migrations.AddField(
            model_name="maintenancewindownetworklink",
            name="network_link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_windows",
                to="network.networklink",
            ),
        ),
        migrations.AddConstraint(
            model_name="alarmtypeallowedsourcekind",
            constraint=models.UniqueConstraint(
                fields=("data_snapshot", "alarm_type", "source_kind"),
                name="unique_alarm_type_allowed_source_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="alarmtypesupporteddevicetype",
            constraint=models.UniqueConstraint(
                fields=("data_snapshot", "alarm_type", "device_type"),
                name="unique_alarm_type_supported_device_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenancewindow",
            constraint=models.UniqueConstraint(
                fields=("data_snapshot", "reference_code"),
                name="unique_maintenance_window_reference_per_snapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenancewindow",
            constraint=models.CheckConstraint(
                condition=models.Q(("planned_end_at__gt", models.F("planned_start_at"))),
                name="maintenance_planned_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenancewindow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actual_end_at__isnull", True),
                    ("actual_start_at__isnull", False),
                    _connector="OR",
                ),
                name="maintenance_actual_end_requires_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenancewindowdevice",
            constraint=models.UniqueConstraint(
                fields=("data_snapshot", "maintenance_window", "device"),
                name="unique_maintenance_window_device",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenancewindownetworklink",
            constraint=models.UniqueConstraint(
                fields=("data_snapshot", "maintenance_window", "network_link"),
                name="unique_maintenance_window_network_link",
            ),
        ),
    ]
