# Generated by Django 5.2.16 on 2026-08-05 06:57

import django.db.models.deletion
from django.db import migrations, models


def sync_ground_truth_row_counts(apps, schema_editor):
    DataSnapshot = apps.get_model('datasets', 'DataSnapshot')
    GroundTruthCase = apps.get_model('datasets', 'GroundTruthCase')
    for snapshot in DataSnapshot.objects.all().iterator():
        count = GroundTruthCase.objects.filter(data_snapshot_id=snapshot.id).count()
        row_counts = dict(snapshot.row_counts or {})
        if row_counts.get('ground_truth_cases') == count:
            continue
        row_counts['ground_truth_cases'] = count
        snapshot.row_counts = row_counts
        snapshot.save(update_fields=['row_counts'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_compensationhistory_compensation_conflict_group_and_more'),
        ('datasets', '0003_groundtruthcase'),
        ('network', '0007_alter_networkdevice_device_type_failuredomain_and_more'),
        ('operations', '0003_alarmtypeallowedsourcekind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CausalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_code', models.CharField(max_length=120)),
                ('event_type', models.CharField(choices=[('device_failure', 'Device Failure'), ('link_failure', 'Link Failure'), ('port_failure', 'Port Failure'), ('access_segment_failure', 'Access Segment Failure'), ('environmental_anomaly', 'Environmental Anomaly'), ('power_event', 'Power Event'), ('degradation', 'Degradation'), ('maintenance', 'Maintenance'), ('unknown', 'Unknown')], max_length=40)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('correlating', 'Correlating'), ('active', 'Active'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='detected', max_length=24)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('source_system', models.CharField(max_length=80)),
                ('origin', models.CharField(choices=[('synthetic', 'Synthetic'), ('imported', 'Imported')], default='synthetic', max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causal_events', to='datasets.datasnapshot')),
                ('root_access_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='root_causal_events', to='network.accesssegment')),
                ('root_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='root_causal_events', to='network.networkdevice')),
                ('root_failure_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='root_causal_events', to='network.failuredomain')),
                ('root_line_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='root_causal_events', to='network.lineconnection')),
                ('root_network_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='root_causal_events', to='network.networklink')),
                ('root_network_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='root_causal_events', to='network.networkport')),
                ('root_subscription_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='root_causal_events', to='customers.subscriptionconnection')),
            ],
            options={
                'verbose_name': 'Nedensel operasyon olayı',
                'verbose_name_plural': 'Nedensel operasyon olayları',
                'db_table': 'operations_causal_event',
                'ordering': ['data_snapshot', '-started_at', 'event_code'],
            },
        ),
        migrations.AddField(
            model_name='alarm',
            name='causal_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarms', to='operations.causalevent'),
        ),
        migrations.AddField(
            model_name='incident',
            name='causal_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='operations.causalevent'),
        ),
        migrations.AddField(
            model_name='operationalevent',
            name='causal_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_events', to='operations.causalevent'),
        ),
        migrations.AddField(
            model_name='outage',
            name='causal_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outages', to='operations.causalevent'),
        ),
        migrations.AddField(
            model_name='qualitymeasurement',
            name='causal_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_measurements', to='operations.causalevent'),
        ),
        migrations.CreateModel(
            name='CustomerImpactAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('potential_impact', 'Potential Impact'), ('verified_impact', 'Verified Impact'), ('verified_no_impact', 'Verified No Impact'), ('insufficient_evidence', 'Insufficient Evidence')], max_length=32)),
                ('potential_impact', models.BooleanField(default=True)),
                ('connection_role', models.CharField(blank=True, max_length=32)),
                ('assessment_started_at', models.DateTimeField()),
                ('assessment_ended_at', models.DateTimeField(blank=True, null=True)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('evidence_session_event_codes', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('causal_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_impact_assessments', to='operations.causalevent')),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_impact_assessments', to='datasets.datasnapshot')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impact_assessments', to='customers.subscription')),
                ('subscription_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impact_assessments', to='customers.subscriptionconnection')),
            ],
            options={
                'verbose_name': 'Müşteri etki değerlendirmesi',
                'verbose_name_plural': 'Müşteri etki değerlendirmeleri',
                'db_table': 'operations_customer_impact_assessment',
                'ordering': ['data_snapshot', 'causal_event__event_code', 'subscription_connection_id'],
            },
        ),
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_event_id', models.CharField(blank=True, max_length=160)),
                ('event_type', models.CharField(choices=[('start', 'Start'), ('continue', 'Continue'), ('stop', 'Stop')], max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('source_system', models.CharField(max_length=80)),
                ('external_service_reference_hash', models.CharField(blank=True, max_length=128)),
                ('nas_identifier', models.CharField(blank=True, max_length=120)),
                ('service_identifier_hash', models.CharField(blank=True, max_length=128)),
                ('session_identifier_hash', models.CharField(blank=True, max_length=128)),
                ('subscriber_reference_hash', models.CharField(blank=True, max_length=128)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('causal_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_events', to='operations.causalevent')),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_events', to='datasets.datasnapshot')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_events', to='customers.subscription')),
                ('subscription_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_events', to='customers.subscriptionconnection')),
            ],
            options={
                'verbose_name': 'Session kanıt olayı',
                'verbose_name_plural': 'Session kanıt olayları',
                'db_table': 'operations_session_event',
                'ordering': ['data_snapshot', 'occurred_at', 'external_event_id'],
            },
        ),
        migrations.AddIndex(
            model_name='causalevent',
            index=models.Index(fields=['data_snapshot', 'event_type', 'status'], name='causal_evt_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='causalevent',
            index=models.Index(fields=['data_snapshot', 'started_at'], name='causal_evt_snapshot_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='causalevent',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'event_code'), name='unique_causal_event_code_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='causalevent',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='causal_event_end_at_or_after_start'),
        ),
        migrations.AddConstraint(
            model_name='causalevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['resolved', 'closed', 'cancelled']), _negated=True), ('ended_at__isnull', False), _connector='OR'), name='causal_event_terminal_status_requires_end'),
        ),
        migrations.AddConstraint(
            model_name='causalevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('root_access_segment__isnull', True), ('root_device__isnull', True), ('root_failure_domain__isnull', True), ('root_line_connection__isnull', True), ('root_network_link__isnull', True), ('root_network_port__isnull', True), ('root_subscription_connection__isnull', True)), models.Q(('root_device__isnull', False), ('root_network_link__isnull', True), ('root_network_port__isnull', True), ('root_line_connection__isnull', True), ('root_access_segment__isnull', True), ('root_failure_domain__isnull', True), ('root_subscription_connection__isnull', True)), models.Q(('root_network_link__isnull', False), ('root_device__isnull', True), ('root_network_port__isnull', True), ('root_line_connection__isnull', True), ('root_access_segment__isnull', True), ('root_failure_domain__isnull', True), ('root_subscription_connection__isnull', True)), models.Q(('root_network_port__isnull', False), ('root_device__isnull', True), ('root_network_link__isnull', True), ('root_line_connection__isnull', True), ('root_access_segment__isnull', True), ('root_failure_domain__isnull', True), ('root_subscription_connection__isnull', True)), models.Q(('root_line_connection__isnull', False), ('root_device__isnull', True), ('root_network_link__isnull', True), ('root_network_port__isnull', True), ('root_access_segment__isnull', True), ('root_failure_domain__isnull', True), ('root_subscription_connection__isnull', True)), models.Q(('root_access_segment__isnull', False), ('root_device__isnull', True), ('root_network_link__isnull', True), ('root_network_port__isnull', True), ('root_line_connection__isnull', True), ('root_failure_domain__isnull', True), ('root_subscription_connection__isnull', True)), models.Q(('root_failure_domain__isnull', False), ('root_device__isnull', True), ('root_network_link__isnull', True), ('root_network_port__isnull', True), ('root_line_connection__isnull', True), ('root_access_segment__isnull', True), ('root_subscription_connection__isnull', True)), models.Q(('root_subscription_connection__isnull', False), ('root_device__isnull', True), ('root_network_link__isnull', True), ('root_network_port__isnull', True), ('root_line_connection__isnull', True), ('root_access_segment__isnull', True), ('root_failure_domain__isnull', True)), _connector='OR'), name='causal_event_has_zero_or_one_root_resource'),
        ),
        migrations.AddIndex(
            model_name='customerimpactassessment',
            index=models.Index(fields=['data_snapshot', 'status'], name='impact_assessment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='customerimpactassessment',
            index=models.Index(fields=['data_snapshot', 'assessment_started_at'], name='impact_assessment_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerimpactassessment',
            constraint=models.UniqueConstraint(condition=models.Q(('subscription_connection__isnull', False)), fields=('causal_event', 'subscription_connection'), name='unique_impact_assessment_per_event_connection'),
        ),
        migrations.AddConstraint(
            model_name='customerimpactassessment',
            constraint=models.UniqueConstraint(condition=models.Q(('subscription__isnull', False), ('subscription_connection__isnull', True)), fields=('causal_event', 'subscription'), name='unique_impact_assessment_per_event_subscription'),
        ),
        migrations.AddConstraint(
            model_name='customerimpactassessment',
            constraint=models.CheckConstraint(condition=models.Q(('assessment_ended_at__isnull', True), ('assessment_ended_at__gte', models.F('assessment_started_at')), _connector='OR'), name='impact_assessment_end_at_or_after_start'),
        ),
        migrations.AddConstraint(
            model_name='customerimpactassessment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['verified_impact', 'verified_no_impact', 'insufficient_evidence']), _negated=True), ('potential_impact', True), _connector='OR'), name='impact_assessment_verified_requires_potential'),
        ),
        migrations.AddConstraint(
            model_name='customerimpactassessment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'potential_impact'), _negated=True), ('potential_impact', True), _connector='OR'), name='impact_assessment_potential_status_requires_flag'),
        ),
        migrations.AddConstraint(
            model_name='customerimpactassessment',
            constraint=models.CheckConstraint(condition=models.Q(('subscription__isnull', False), ('subscription_connection__isnull', False), _connector='OR'), name='impact_assessment_has_subscription_or_connection'),
        ),
        migrations.AddIndex(
            model_name='sessionevent',
            index=models.Index(fields=['data_snapshot', 'event_type', 'occurred_at'], name='session_evt_type_time_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionevent',
            index=models.Index(fields=['data_snapshot', 'subscription_connection', 'occurred_at'], name='session_evt_conn_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_event_id', ''), _negated=True), fields=('data_snapshot', 'source_system', 'external_event_id'), name='unique_session_source_event_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='sessionevent',
            constraint=models.CheckConstraint(condition=models.Q(('received_at__isnull', True), ('received_at__gte', models.F('occurred_at')), _connector='OR'), name='session_event_received_at_or_after_occurred'),
        ),
        migrations.AddConstraint(
            model_name='sessionevent',
            constraint=models.CheckConstraint(condition=models.Q(('subscription__isnull', False), ('subscription_connection__isnull', False), models.Q(('external_service_reference_hash', ''), _negated=True), _connector='OR'), name='session_event_has_identity_reference'),
        ),
        migrations.RunPython(sync_ground_truth_row_counts, noop_reverse),
    ]
