# Generated by Django 5.2.16 on 2026-07-27 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('country_code', models.CharField(default='TR', max_length=2)),
                ('plate_code', models.CharField(blank=True, max_length=8)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'db_table': 'geography_city',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('profile_type', models.CharField(choices=[('unknown', 'Unknown'), ('residential', 'Residential'), ('business', 'Business'), ('industrial', 'Industrial'), ('mixed', 'Mixed')], default='unknown', max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='geography.city')),
            ],
            options={
                'db_table': 'geography_district',
                'ordering': ['city__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('profile_type', models.CharField(choices=[('unknown', 'Unknown'), ('residential', 'Residential'), ('business', 'Business'), ('industrial', 'Industrial'), ('mixed', 'Mixed')], default='unknown', max_length=24)),
                ('external_code', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='geography.district')),
            ],
            options={
                'db_table': 'geography_neighborhood',
                'ordering': ['district__city__name', 'district__name', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('city', 'slug'), name='unique_district_slug_per_city'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('city', 'name'), name='unique_district_name_per_city'),
        ),
        migrations.AddConstraint(
            model_name='neighborhood',
            constraint=models.UniqueConstraint(fields=('district', 'slug'), name='unique_neighborhood_slug_per_district'),
        ),
        migrations.AddConstraint(
            model_name='neighborhood',
            constraint=models.UniqueConstraint(fields=('district', 'name'), name='unique_neighborhood_name_per_district'),
        ),
    ]
