# Generated by Django 5.2.16 on 2026-07-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'İl', 'verbose_name_plural': 'İller'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['city__name', 'name'], 'verbose_name': 'İlçe', 'verbose_name_plural': 'İlçeler'},
        ),
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'ordering': ['district__city__name', 'district__name', 'name'], 'verbose_name': 'Mahalle', 'verbose_name_plural': 'Mahalleler'},
        ),
    ]
