"""Ground-truth oracle cases for the multi-city realism dataset.

These values are deterministic synthetic expectations for simulation validation.
They are not copied from production service responses and do not represent real
operator policy or network data.
"""

from __future__ import annotations

from decimal import Decimal

from data_generator.configs import synthetic_compensation_policy_v1 as policy_config

GROUND_TRUTH_VERSION = "multicity-ground-truth-v1"
DATASET_SLUG = "multi-city-realism-v1"
RULE_SET_CODE = policy_config.RULE_SET["code"]
RULE_SET_VERSION = policy_config.RULE_SET["version"]
CURRENCY = "TRY"

REQUIRED_CATEGORIES = {
    "network_operation",
    "rule_compensation",
    "path_diversity",
    "noise",
    "maintenance",
    "manual_review",
    "duplicate",
}

PATH_DIVERSITY_EXPECTED = {
    "fully_diverse": 112,
    "partially_diverse": 60,
    "shared_risk": 24,
    "unknown": 12,
}

NETWORK_CASES = [
    {
        "case_code": "GT-MCR-NET-BNG-WIDE-001",
        "category": "network_operation",
        "scenario_code": "SCN-BNG-DOWN-001",
        "outage_code": "OUT-MCR-0001",
        "incident_number": "INC-MCR-0001",
        "expected_root_cause": "AGG-ANK-002",
        "expected_root_classification": "unknown",
        "expected_incident_type": "network_outage",
        "expected_impact_class": "full_outage",
        "expected_affected_subscription_count": 572,
        "expected_affected_customer_count": 495,
        "expected_outage_exists": True,
        "expected_selected_rule": "BB-FULL-OUTAGE-TIERED",
        "expected_decision": "eligible",
        "expected_exact_amount": "31.99",
        "expected_manual_review_reason": "",
        "service_checks": ["impact", "root_cause"],
    },
    {
        "case_code": "GT-MCR-NET-METRO-AGG-001",
        "category": "network_operation",
        "scenario_code": "SCN-METRO-AGG-001",
        "outage_code": "OUT-MCR-0002",
        "incident_number": "INC-MCR-0002",
        "expected_root_cause": "AGG-ANK-003",
        "expected_root_classification": "unknown",
        "expected_incident_type": "network_outage",
        "expected_impact_class": "full_outage",
        "expected_affected_subscription_count": 474,
        "expected_affected_customer_count": 437,
        "expected_outage_exists": True,
        "expected_selected_rule": "BB-FULL-OUTAGE-TIERED",
        "expected_decision": "eligible",
        "expected_exact_amount": "31.99",
        "expected_manual_review_reason": "",
        "service_checks": ["impact", "root_cause"],
    },
    {
        "case_code": "GT-MCR-NET-FIBER-ROUTE-001",
        "category": "network_operation",
        "scenario_code": "SCN-FIBER-ROUTE-001",
        "outage_code": "OUT-MCR-0003",
        "incident_number": "INC-MCR-0003",
        "expected_root_cause": "AGG-ANK-004",
        "expected_root_classification": "unknown",
        "expected_incident_type": "network_outage",
        "expected_impact_class": "full_outage",
        "expected_affected_subscription_count": 192,
        "expected_affected_customer_count": 192,
        "expected_outage_exists": True,
        "expected_selected_rule": "BB-FULL-OUTAGE-TIERED",
        "expected_decision": "eligible",
        "expected_exact_amount": "31.99",
        "expected_manual_review_reason": "",
        "service_checks": ["impact", "root_cause"],
    },
    {
        "case_code": "GT-MCR-NET-POWER-ZONE-001",
        "category": "network_operation",
        "scenario_code": "SCN-POWER-001",
        "outage_code": "OUT-MCR-0004",
        "incident_number": "INC-MCR-0004",
        "expected_root_cause": "AGG-KOC-001",
        "expected_root_classification": "unknown",
        "expected_incident_type": "network_outage",
        "expected_impact_class": "full_outage",
        "expected_affected_subscription_count": 926,
        "expected_affected_customer_count": 736,
        "expected_outage_exists": True,
        "expected_selected_rule": "BB-FULL-OUTAGE-TIERED",
        "expected_decision": "eligible",
        "expected_exact_amount": "31.99",
        "expected_manual_review_reason": "",
        "service_checks": ["impact", "root_cause"],
    },
    {
        "case_code": "GT-MCR-NET-PON-PARTIAL-001",
        "category": "network_operation",
        "scenario_code": "SCN-PON-PORT-001",
        "outage_code": "OUT-MCR-0005",
        "incident_number": "INC-MCR-0005",
        "expected_root_cause": "AGG-KOC-002",
        "expected_root_classification": "unknown",
        "expected_incident_type": "network_outage",
        "expected_impact_class": "full_outage",
        "expected_affected_subscription_count": 1338,
        "expected_affected_customer_count": 1101,
        "expected_outage_exists": True,
        "expected_selected_rule": "BB-PARTIAL-OUTAGE-PRORATED",
        "expected_decision": "eligible",
        "expected_exact_amount": "10.00",
        "expected_modifier_or_cap": "minimum_positive_amount",
        "expected_manual_review_reason": "",
        "service_checks": ["impact", "root_cause"],
    },
    {
        "case_code": "GT-MCR-NET-DSLAM-GROUP-001",
        "category": "network_operation",
        "scenario_code": "SCN-DSLAM-PORT-GROUP-001",
        "outage_code": "OUT-MCR-0006",
        "incident_number": "INC-MCR-0006",
        "expected_root_cause": "AGG-KOC-003",
        "expected_root_classification": "unknown",
        "expected_incident_type": "network_outage",
        "expected_impact_class": "full_outage",
        "expected_affected_subscription_count": 999,
        "expected_affected_customer_count": 895,
        "expected_outage_exists": True,
        "expected_selected_rule": "BB-FULL-OUTAGE-TIERED",
        "expected_decision": "eligible",
        "expected_exact_amount": "31.99",
        "expected_manual_review_reason": "",
        "service_checks": ["impact", "root_cause"],
    },
    {
        "case_code": "GT-MCR-NET-FLAPPING-001",
        "category": "network_operation",
        "scenario_code": "SCN-LINK-FLAP-001",
        "outage_code": "OUT-MCR-0007",
        "incident_number": "INC-MCR-0007",
        "expected_root_cause": "AGG-KOC-004",
        "expected_root_classification": "unknown",
        "expected_incident_type": "network_outage",
        "expected_impact_class": "full_outage",
        "expected_affected_subscription_count": 968,
        "expected_affected_customer_count": 869,
        "expected_outage_exists": True,
        "expected_selected_rule": "MOD-RECURRING-INCIDENT",
        "expected_decision": "eligible",
        "expected_exact_amount": "10.00",
        "expected_modifier_or_cap": "recurring_modifier",
        "expected_manual_review_reason": "",
        "service_checks": ["impact", "root_cause"],
    },
    {
        "case_code": "GT-MCR-NET-FAILED-FAILOVER-001",
        "category": "network_operation",
        "scenario_code": "SCN-FAILOVER-FAILED-001",
        "outage_code": "OUT-MCR-0013",
        "incident_number": "INC-MCR-0013",
        "expected_root_cause": "AGG-İZM-002",
        "expected_root_classification": "unknown",
        "expected_incident_type": "network_outage",
        "expected_impact_class": "full_outage",
        "expected_affected_subscription_count": 1438,
        "expected_affected_customer_count": 1267,
        "expected_outage_exists": True,
        "expected_selected_rule": "ME-FAILED-FAILOVER",
        "expected_decision": "eligible",
        "expected_exact_amount": "839.99",
        "expected_manual_review_reason": "",
        "service_checks": ["impact", "root_cause"],
    },
    {
        "case_code": "GT-MCR-NET-SHARED-RISK-001",
        "category": "path_diversity",
        "scenario_code": "SCN-SHARED-RISK-FAILOVER-001",
        "outage_code": "OUT-MCR-0015",
        "incident_number": "INC-MCR-0015",
        "expected_root_cause": "AGG-İZM-004",
        "expected_root_classification": "unknown",
        "expected_incident_type": "network_outage",
        "expected_impact_class": "full_outage",
        "expected_affected_subscription_count": 1112,
        "expected_affected_customer_count": 989,
        "expected_outage_exists": True,
        "expected_selected_rule": "SLA-PATH-DIVERSITY-BREACH",
        "expected_decision": "manual_review",
        "expected_exact_amount": "0.00",
        "expected_manual_review_reason": "shared_risk_diversity",
        "service_checks": ["impact", "root_cause", "path_diversity_distribution"],
    },
    {
        "case_code": "GT-MCR-NET-UNKNOWN-RCA-001",
        "category": "manual_review",
        "scenario_code": "SCN-UNKNOWN-RCA-001",
        "outage_code": "OUT-MCR-0021",
        "incident_number": "INC-MCR-0021",
        "expected_root_cause": "AN-ESE-002",
        "expected_root_classification": "unknown",
        "expected_incident_type": "network_outage",
        "expected_impact_class": "full_outage",
        "expected_affected_subscription_count": 48,
        "expected_affected_customer_count": 24,
        "expected_outage_exists": True,
        "expected_selected_rule": "MR-UNKNOWN-MISSING-EVIDENCE",
        "expected_decision": "manual_review",
        "expected_exact_amount": "0.00",
        "expected_manual_review_reason": "unknown_root_cause",
        "service_checks": ["impact"],
    },
]

RULE_CASES = [
    {
        "case_code": "GT-MCR-RULE-FULL-OUTAGE-001",
        "category": "rule_compensation",
        "scenario_code": "GT-FULL-OUTAGE",
        "expected_selected_rule": "BB-FULL-OUTAGE-TIERED",
        "expected_decision": "eligible",
        "expected_exact_amount": "31.99",
        "action_context": {"outage_duration_seconds": 14400},
        "price_basis_amount": "399.90",
    },
    {
        "case_code": "GT-MCR-RULE-UNDER-30-001",
        "category": "rule_compensation",
        "scenario_code": "GT-UNDER-30",
        "expected_selected_rule": "BB-FULL-OUTAGE-TIERED",
        "expected_decision": "ineligible",
        "expected_exact_amount": "0.00",
        "action_context": {"outage_duration_seconds": 1799},
        "price_basis_amount": "399.90",
    },
    {
        "case_code": "GT-MCR-RULE-PARTIAL-PRORATED-001",
        "category": "rule_compensation",
        "scenario_code": "GT-PARTIAL",
        "expected_selected_rule": "BB-PARTIAL-OUTAGE-PRORATED",
        "expected_decision": "eligible",
        "expected_exact_amount": "10.00",
        "expected_modifier_or_cap": "minimum_positive_amount",
        "action_context": {
            "affected_duration_seconds": 7200,
            "billing_period_seconds": 2678400,
            "affected_capacity_ratio": "0.50",
        },
        "price_basis_amount": "499.90",
    },
    {
        "case_code": "GT-MCR-RULE-BB-DEGRADATION-001",
        "category": "rule_compensation",
        "scenario_code": "GT-BB-DEGRADATION",
        "expected_selected_rule": "BB-DEGRADATION-QUALITY",
        "expected_decision": "eligible",
        "expected_exact_amount": "41.99",
        "action_context": {"exceedance_ratio": "1.50"},
        "price_basis_amount": "599.90",
    },
    {
        "case_code": "GT-MCR-RULE-ME-LATENCY-001",
        "category": "rule_compensation",
        "scenario_code": "GT-ME-LATENCY",
        "expected_selected_rule": "ME-LATENCY-BREACH",
        "expected_decision": "eligible",
        "expected_exact_amount": "489.99",
        "action_context": {"exceedance_ratio": "1.50"},
        "price_basis_amount": "6999.90",
    },
    {
        "case_code": "GT-MCR-RULE-FAILOVER-45S-001",
        "category": "rule_compensation",
        "scenario_code": "GT-FAILOVER-45S",
        "expected_selected_rule": "ME-SHORT-FAILOVER-INTERRUPTION",
        "expected_decision": "eligible",
        "expected_exact_amount": "35.00",
        "expected_modifier_or_cap": "absolute_cap_50_not_reached",
        "action_context": {"transition_duration_seconds": 45},
        "price_basis_amount": "6999.90",
    },
    {
        "case_code": "GT-MCR-RULE-FAILED-FAILOVER-001",
        "category": "rule_compensation",
        "scenario_code": "GT-FAILED-FAILOVER",
        "expected_selected_rule": "ME-FAILED-FAILOVER",
        "expected_decision": "eligible",
        "expected_exact_amount": "839.99",
        "action_context": {"outage_duration_seconds": 9000},
        "price_basis_amount": "6999.90",
    },
    {
        "case_code": "GT-MCR-RULE-PROTECTION-LOSS-001",
        "category": "path_diversity",
        "scenario_code": "GT-PROTECTION-LOSS",
        "incident_number": "INC-MCR-0140",
        "expected_incident_type": "protection_event",
        "expected_impact_class": "protection_loss",
        "expected_outage_exists": False,
        "expected_selected_rule": "EXCL-PROTECTION-LOSS-ONLY",
        "expected_decision": "evidence_only",
        "expected_exact_amount": "0.00",
        "expected_manual_review_reason": "protection_loss_only",
    },
    {
        "case_code": "GT-MCR-RULE-PLANNED-NORMAL-001",
        "category": "maintenance",
        "scenario_code": "GT-MAINTENANCE-NORMAL",
        "incident_number": "INC-MCR-0163",
        "expected_incident_type": "planned_maintenance",
        "expected_outage_exists": False,
        "expected_selected_rule": "EXCL-PLANNED-MAINTENANCE-NORMAL",
        "expected_decision": "ineligible",
        "expected_exact_amount": "0.00",
        "expected_manual_review_reason": "planned_maintenance_completed_in_window",
    },
    {
        "case_code": "GT-MCR-RULE-MAINT-OVERRUN-001",
        "category": "maintenance",
        "scenario_code": "GT-MAINTENANCE-OVERRUN",
        "incident_number": "INC-MCR-0164",
        "expected_incident_type": "network_outage",
        "expected_outage_exists": False,
        "expected_selected_rule": "MOD-MAINTENANCE-OVERRUN",
        "expected_decision": "eligible",
        "expected_exact_amount": "8.00",
        "expected_modifier_or_cap": "maintenance_overrun_modifier",
        "action_context": {"base_amount": "80.00"},
        "price_basis_amount": "399.90",
    },
    {
        "case_code": "GT-MCR-RULE-RECURRING-MOD-001",
        "category": "rule_compensation",
        "scenario_code": "GT-RECURRING",
        "expected_selected_rule": "MOD-RECURRING-INCIDENT",
        "expected_decision": "eligible",
        "expected_exact_amount": "10.00",
        "expected_modifier_or_cap": "recurring_modifier",
        "action_context": {"base_amount": "100.00"},
        "price_basis_amount": "399.90",
    },
    {
        "case_code": "GT-MCR-RULE-DUPLICATE-001",
        "category": "duplicate",
        "scenario_code": "GT-DUPLICATE",
        "expected_selected_rule": "EXCL-DUPLICATE-COMPENSATION",
        "expected_decision": "ineligible",
        "expected_exact_amount": "0.00",
        "expected_manual_review_reason": "duplicate_final_compensation",
    },
    {
        "case_code": "GT-MCR-RULE-MONTHLY-CAP-001",
        "category": "rule_compensation",
        "scenario_code": "GT-MONTHLY-CAP",
        "expected_selected_rule": "CAP-FLOOR-CONFLICT",
        "expected_decision": "eligible",
        "expected_exact_amount": "49.93",
        "expected_modifier_or_cap": "billing_period_cumulative_cap",
        "action_context": {
            "amount": "300.00",
            "price_basis_amount": "399.90",
            "billing_period_cumulative_amount": "250.00",
        },
        "price_basis_amount": "399.90",
    },
    {
        "case_code": "GT-MCR-RULE-NOISE-NO-INCIDENT-001",
        "category": "noise",
        "scenario_code": "SCN-NOISE-001",
        "expected_selected_rule": "NONE",
        "expected_decision": "ineligible",
        "expected_exact_amount": "0.00",
        "expected_outage_exists": False,
        "expected_manual_review_reason": "noise_alarm_suppressed_no_incident",
    },
    {
        "case_code": "GT-MCR-RULE-PAYMENT-SUSPENSION-001",
        "category": "rule_compensation",
        "scenario_code": "GT-PAYMENT-SUSPENSION",
        "expected_selected_rule": "EXCL-SUSPENSION-POLICY",
        "expected_decision": "ineligible",
        "expected_exact_amount": "0.00",
        "expected_manual_review_reason": "suspended_payment_related",
        "subscription_precondition": {
            "status": "suspended",
            "suspension_reason": "payment_related",
        },
    },
    {
        "case_code": "GT-MCR-RULE-PROVIDER-FAULT-SUSPENSION-001",
        "category": "rule_compensation",
        "scenario_code": "GT-PROVIDER-FAULT-SUSPENSION",
        "expected_selected_rule": "ELIG-SUBSCRIPTION-VALID",
        "expected_decision": "eligible",
        "expected_exact_amount": "31.99",
        "expected_manual_review_reason": "provider_fault_suspension",
        "subscription_precondition": {
            "status": "suspended",
            "suspension_reason": "provider_fault",
        },
        "action_context": {"outage_duration_seconds": 14400},
        "price_basis_amount": "399.90",
        "amount_rule": "BB-FULL-OUTAGE-TIERED",
    },
    {
        "case_code": "GT-MCR-RULE-MISSING-PRICE-001",
        "category": "manual_review",
        "scenario_code": "GT-MISSING-PRICE",
        "expected_selected_rule": "MR-UNKNOWN-MISSING-EVIDENCE",
        "expected_decision": "manual_review",
        "expected_exact_amount": "0.00",
        "expected_manual_review_reason": "missing_price",
        "action_context": {"outage_duration_seconds": 14400},
        "price_basis_amount": None,
        "amount_rule": "BB-FULL-OUTAGE-TIERED",
    },
    {
        "case_code": "GT-MCR-RULE-UNKNOWN-ROOT-001",
        "category": "manual_review",
        "scenario_code": "GT-UNKNOWN-ROOT",
        "incident_number": "INC-MCR-0168",
        "expected_incident_type": "unknown",
        "expected_selected_rule": "MR-UNKNOWN-MISSING-EVIDENCE",
        "expected_decision": "manual_review",
        "expected_exact_amount": "0.00",
        "expected_manual_review_reason": "unknown_root_cause",
    },
    {
        "case_code": "GT-MCR-RULE-SHARED-RISK-DIVERSITY-001",
        "category": "path_diversity",
        "scenario_code": "GT-SHARED-RISK",
        "expected_selected_rule": "SLA-PATH-DIVERSITY-BREACH",
        "expected_decision": "manual_review",
        "expected_exact_amount": "0.00",
        "expected_manual_review_reason": "shared_risk_diversity",
        "expected_path_diversity": "shared_risk",
    },
    {
        "case_code": "GT-MCR-RULE-BACKUP-MISSING-001",
        "category": "path_diversity",
        "scenario_code": "GT-BACKUP-MISSING",
        "expected_selected_rule": "SLA-BACKUP-MISSING",
        "expected_decision": "manual_review",
        "expected_exact_amount": "0.00",
        "expected_manual_review_reason": "required_backup_missing",
    },
]


GROUND_TRUTH_CASES = NETWORK_CASES + RULE_CASES

EXPECTED_CASE_COUNT = len(GROUND_TRUTH_CASES)


def expected_amount(value: str) -> Decimal:
    return Decimal(value)
