"""Synthetic alarm catalog and scenario templates for realistic dataset v1.

These definitions are planning inputs for the future large synthetic dataset.
They are not real operator alarm codes, inventory records, or policy data.
"""

from apps.network.models import NetworkDeviceType
from apps.operations.models import (
    AlarmCategory,
    AlarmSourceKind,
    AutoClearPolicy,
    FailoverResult,
    IncidentType,
    ServiceImpactClass,
    Severity,
)

GENERATOR_VERSION = "realistic-alarm-catalog-v1"

ALARM_CATALOG = [
    {
        "code": "BNG_UNREACHABLE",
        "name": "BNG unreachable",
        "category": AlarmCategory.CORE,
        "severity": Severity.CRITICAL,
        "allowed_source_kinds": [AlarmSourceKind.DEVICE],
        "supported_device_types": [NetworkDeviceType.BNG],
        "probable_cause_family": "core_device_unreachable",
        "service_impact_class": ServiceImpactClass.FULL_OUTAGE,
        "auto_clear_policy": AutoClearPolicy.AUTO_OR_MANUAL,
        "deduplication_window_seconds": 600,
        "correlation_family": "device_unreachable",
        "default_incident_type": IncidentType.NETWORK_OUTAGE,
        "is_root_candidate": True,
        "impact_class": "full_outage",
    },
    {
        "code": "METRO_AGG_UNREACHABLE",
        "name": "Metro aggregation unreachable",
        "category": AlarmCategory.TRANSPORT,
        "severity": Severity.CRITICAL,
        "allowed_source_kinds": [AlarmSourceKind.DEVICE],
        "supported_device_types": [NetworkDeviceType.METRO_AGGREGATION],
        "probable_cause_family": "aggregation_device_unreachable",
        "service_impact_class": ServiceImpactClass.PARTIAL_OUTAGE,
        "auto_clear_policy": AutoClearPolicy.AUTO_OR_MANUAL,
        "deduplication_window_seconds": 600,
        "correlation_family": "device_unreachable",
        "default_incident_type": IncidentType.NETWORK_OUTAGE,
        "is_root_candidate": True,
        "impact_class": "partial_outage",
    },
    {
        "code": "OLT_UNREACHABLE",
        "name": "OLT unreachable",
        "category": AlarmCategory.ACCESS,
        "severity": Severity.MAJOR,
        "allowed_source_kinds": [AlarmSourceKind.DEVICE],
        "supported_device_types": [NetworkDeviceType.OLT],
        "probable_cause_family": "access_device_unreachable",
        "service_impact_class": ServiceImpactClass.PARTIAL_OUTAGE,
        "auto_clear_policy": AutoClearPolicy.AUTO_OR_MANUAL,
        "deduplication_window_seconds": 600,
        "correlation_family": "device_unreachable",
        "default_incident_type": IncidentType.NETWORK_OUTAGE,
        "is_root_candidate": True,
        "impact_class": "partial_outage",
    },
    {
        "code": "DSLAM_UNREACHABLE",
        "name": "DSLAM unreachable",
        "category": AlarmCategory.ACCESS,
        "severity": Severity.MAJOR,
        "allowed_source_kinds": [AlarmSourceKind.DEVICE],
        "supported_device_types": [NetworkDeviceType.DSLAM],
        "probable_cause_family": "access_device_unreachable",
        "service_impact_class": ServiceImpactClass.PARTIAL_OUTAGE,
        "auto_clear_policy": AutoClearPolicy.AUTO_OR_MANUAL,
        "deduplication_window_seconds": 600,
        "correlation_family": "device_unreachable",
        "default_incident_type": IncidentType.NETWORK_OUTAGE,
        "is_root_candidate": True,
        "impact_class": "partial_outage",
    },
    {
        "code": "ACCESS_NODE_UNREACHABLE",
        "name": "Access node unreachable",
        "category": AlarmCategory.ACCESS,
        "severity": Severity.MAJOR,
        "allowed_source_kinds": [AlarmSourceKind.DEVICE],
        "supported_device_types": [NetworkDeviceType.ACCESS_NODE],
        "probable_cause_family": "access_node_unreachable",
        "service_impact_class": ServiceImpactClass.PARTIAL_OUTAGE,
        "auto_clear_policy": AutoClearPolicy.AUTO_OR_MANUAL,
        "deduplication_window_seconds": 600,
        "correlation_family": "device_unreachable",
        "default_incident_type": IncidentType.NETWORK_OUTAGE,
        "is_root_candidate": True,
        "impact_class": "partial_outage",
    },
    {
        "code": "UPLINK_DOWN",
        "name": "Uplink down",
        "category": AlarmCategory.TRANSPORT,
        "severity": Severity.MAJOR,
        "allowed_source_kinds": [AlarmSourceKind.NETWORK_LINK],
        "supported_device_types": [],
        "probable_cause_family": "uplink_failure",
        "service_impact_class": ServiceImpactClass.PARTIAL_OUTAGE,
        "auto_clear_policy": AutoClearPolicy.AUTO_OR_MANUAL,
        "deduplication_window_seconds": 300,
        "correlation_family": "link_down",
        "default_incident_type": IncidentType.NETWORK_OUTAGE,
        "is_root_candidate": True,
        "impact_class": "partial_outage",
    },
    {
        "code": "FIBER_CUT_SUSPECTED",
        "name": "Fiber cut suspected",
        "category": AlarmCategory.TRANSPORT,
        "severity": Severity.CRITICAL,
        "allowed_source_kinds": [
            AlarmSourceKind.NETWORK_LINK,
            AlarmSourceKind.FAILURE_DOMAIN,
        ],
        "supported_device_types": [],
        "probable_cause_family": "fiber_route_failure",
        "service_impact_class": ServiceImpactClass.PARTIAL_OUTAGE,
        "auto_clear_policy": AutoClearPolicy.MANUAL,
        "deduplication_window_seconds": 1800,
        "correlation_family": "fiber_route",
        "default_incident_type": IncidentType.NETWORK_OUTAGE,
        "is_root_candidate": True,
        "impact_class": "partial_outage",
    },
    {
        "code": "LINK_PACKET_LOSS_HIGH",
        "name": "High packet loss",
        "category": AlarmCategory.QUALITY,
        "severity": Severity.MAJOR,
        "allowed_source_kinds": [AlarmSourceKind.NETWORK_LINK],
        "supported_device_types": [],
        "probable_cause_family": "transport_quality_degraded",
        "service_impact_class": ServiceImpactClass.DEGRADATION,
        "auto_clear_policy": AutoClearPolicy.AUTO,
        "deduplication_window_seconds": 300,
        "correlation_family": "transport_quality",
        "default_incident_type": IncidentType.SERVICE_DEGRADATION,
        "is_root_candidate": False,
        "impact_class": "degradation",
    },
    {
        "code": "LINK_FLAPPING",
        "name": "Link flapping",
        "category": AlarmCategory.TRANSPORT,
        "severity": Severity.MAJOR,
        "allowed_source_kinds": [AlarmSourceKind.NETWORK_LINK],
        "supported_device_types": [],
        "probable_cause_family": "intermittent_transport",
        "service_impact_class": ServiceImpactClass.SHORT_INTERRUPTION,
        "auto_clear_policy": AutoClearPolicy.AUTO_OR_MANUAL,
        "deduplication_window_seconds": 900,
        "correlation_family": "flapping",
        "default_incident_type": IncidentType.INTERMITTENT,
        "is_root_candidate": True,
        "impact_class": "short_interruption",
    },
    {
        "code": "BACKUP_LINK_UNAVAILABLE",
        "name": "Backup link unavailable",
        "category": AlarmCategory.TRANSPORT,
        "severity": Severity.MINOR,
        "allowed_source_kinds": [
            AlarmSourceKind.NETWORK_LINK,
            AlarmSourceKind.SUBSCRIPTION_CONNECTION,
        ],
        "supported_device_types": [],
        "probable_cause_family": "protection_path_unavailable",
        "service_impact_class": ServiceImpactClass.PROTECTION_LOSS,
        "auto_clear_policy": AutoClearPolicy.AUTO_OR_MANUAL,
        "deduplication_window_seconds": 600,
        "correlation_family": "protection",
        "default_incident_type": IncidentType.PROTECTION_EVENT,
        "is_root_candidate": False,
        "impact_class": "protection_loss",
    },
    {
        "code": "PON_PORT_DOWN",
        "name": "PON port down",
        "category": AlarmCategory.ACCESS,
        "severity": Severity.MAJOR,
        "allowed_source_kinds": [AlarmSourceKind.NETWORK_PORT],
        "supported_device_types": [NetworkDeviceType.OLT],
        "probable_cause_family": "pon_port_failure",
        "service_impact_class": ServiceImpactClass.PARTIAL_OUTAGE,
        "auto_clear_policy": AutoClearPolicy.AUTO_OR_MANUAL,
        "deduplication_window_seconds": 600,
        "correlation_family": "gpon_access",
        "default_incident_type": IncidentType.NETWORK_OUTAGE,
        "is_root_candidate": True,
        "impact_class": "partial_outage",
    },
    {
        "code": "OPTICAL_SIGNAL_LOW",
        "name": "Optical signal low",
        "category": AlarmCategory.ACCESS,
        "severity": Severity.MINOR,
        "allowed_source_kinds": [AlarmSourceKind.LINE_CONNECTION],
        "supported_device_types": [NetworkDeviceType.OLT, NetworkDeviceType.ACCESS_NODE],
        "probable_cause_family": "optical_signal_degraded",
        "service_impact_class": ServiceImpactClass.DEGRADATION,
        "auto_clear_policy": AutoClearPolicy.AUTO,
        "deduplication_window_seconds": 600,
        "correlation_family": "optical_quality",
        "default_incident_type": IncidentType.SERVICE_DEGRADATION,
        "is_root_candidate": False,
        "impact_class": "degradation",
    },
    {
        "code": "OPTICAL_SIGNAL_LOSS",
        "name": "Optical signal loss",
        "category": AlarmCategory.ACCESS,
        "severity": Severity.MAJOR,
        "allowed_source_kinds": [AlarmSourceKind.LINE_CONNECTION],
        "supported_device_types": [NetworkDeviceType.OLT, NetworkDeviceType.ACCESS_NODE],
        "probable_cause_family": "optical_signal_loss",
        "service_impact_class": ServiceImpactClass.PARTIAL_OUTAGE,
        "auto_clear_policy": AutoClearPolicy.AUTO_OR_MANUAL,
        "deduplication_window_seconds": 600,
        "correlation_family": "optical_loss",
        "default_incident_type": IncidentType.NETWORK_OUTAGE,
        "is_root_candidate": True,
        "impact_class": "partial_outage",
    },
    {
        "code": "ONT_DISCONNECT_SURGE",
        "name": "High ONT disconnect count",
        "category": AlarmCategory.ACCESS,
        "severity": Severity.MAJOR,
        "allowed_source_kinds": [AlarmSourceKind.NETWORK_PORT],
        "supported_device_types": [NetworkDeviceType.OLT],
        "probable_cause_family": "gpon_splitter_or_pon_issue",
        "service_impact_class": ServiceImpactClass.PARTIAL_OUTAGE,
        "auto_clear_policy": AutoClearPolicy.AUTO,
        "deduplication_window_seconds": 900,
        "correlation_family": "gpon_access",
        "default_incident_type": IncidentType.NETWORK_OUTAGE,
        "is_root_candidate": True,
        "impact_class": "partial_outage",
    },
    {
        "code": "PON_CAPACITY_THRESHOLD",
        "name": "PON capacity threshold",
        "category": AlarmCategory.QUALITY,
        "severity": Severity.WARNING,
        "allowed_source_kinds": [AlarmSourceKind.NETWORK_PORT],
        "supported_device_types": [NetworkDeviceType.OLT],
        "probable_cause_family": "pon_capacity_pressure",
        "service_impact_class": ServiceImpactClass.NO_DIRECT_CUSTOMER_IMPACT,
        "auto_clear_policy": AutoClearPolicy.AUTO,
        "deduplication_window_seconds": 3600,
        "correlation_family": "capacity",
        "default_incident_type": IncidentType.UNKNOWN,
        "is_root_candidate": False,
        "impact_class": "no_direct_customer_impact",
    },
    {
        "code": "DSL_PORT_DOWN",
        "name": "DSL port down",
        "category": AlarmCategory.ACCESS,
        "severity": Severity.MAJOR,
        "allowed_source_kinds": [AlarmSourceKind.NETWORK_PORT],
        "supported_device_types": [NetworkDeviceType.DSLAM],
        "probable_cause_family": "dsl_port_failure",
        "service_impact_class": ServiceImpactClass.PARTIAL_OUTAGE,
        "auto_clear_policy": AutoClearPolicy.AUTO_OR_MANUAL,
        "deduplication_window_seconds": 600,
        "correlation_family": "xdsl_access",
        "default_incident_type": IncidentType.NETWORK_OUTAGE,
        "is_root_candidate": True,
        "impact_class": "partial_outage",
    },
    {
        "code": "DSL_LINE_QUALITY_DEGRADED",
        "name": "DSL line quality degraded",
        "category": AlarmCategory.QUALITY,
        "severity": Severity.MINOR,
        "allowed_source_kinds": [AlarmSourceKind.LINE_CONNECTION],
        "supported_device_types": [NetworkDeviceType.DSLAM],
        "probable_cause_family": "dsl_signal_quality",
        "service_impact_class": ServiceImpactClass.DEGRADATION,
        "auto_clear_policy": AutoClearPolicy.AUTO,
        "deduplication_window_seconds": 900,
        "correlation_family": "xdsl_quality",
        "default_incident_type": IncidentType.SERVICE_DEGRADATION,
        "is_root_candidate": False,
        "impact_class": "degradation",
    },
    {
        "code": "DSL_RETRAIN_FREQUENT",
        "name": "Frequent DSL retrain",
        "category": AlarmCategory.QUALITY,
        "severity": Severity.MINOR,
        "allowed_source_kinds": [AlarmSourceKind.LINE_CONNECTION],
        "supported_device_types": [NetworkDeviceType.DSLAM],
        "probable_cause_family": "intermittent_dsl_quality",
        "service_impact_class": ServiceImpactClass.DEGRADATION,
        "auto_clear_policy": AutoClearPolicy.AUTO,
        "deduplication_window_seconds": 1800,
        "correlation_family": "flapping",
        "default_incident_type": IncidentType.INTERMITTENT,
        "is_root_candidate": False,
        "impact_class": "degradation",
    },
    {
        "code": "DSLAM_PORT_SATURATION",
        "name": "DSLAM port saturation",
        "category": AlarmCategory.QUALITY,
        "severity": Severity.WARNING,
        "allowed_source_kinds": [AlarmSourceKind.DEVICE],
        "supported_device_types": [NetworkDeviceType.DSLAM],
        "probable_cause_family": "access_capacity_pressure",
        "service_impact_class": ServiceImpactClass.NO_DIRECT_CUSTOMER_IMPACT,
        "auto_clear_policy": AutoClearPolicy.AUTO,
        "deduplication_window_seconds": 3600,
        "correlation_family": "capacity",
        "default_incident_type": IncidentType.UNKNOWN,
        "is_root_candidate": False,
        "impact_class": "no_direct_customer_impact",
    },
    {
        "code": "DEDICATED_PORT_DOWN",
        "name": "Dedicated port down",
        "category": AlarmCategory.ACCESS,
        "severity": Severity.MAJOR,
        "allowed_source_kinds": [AlarmSourceKind.NETWORK_PORT],
        "supported_device_types": [NetworkDeviceType.ACCESS_NODE],
        "probable_cause_family": "dedicated_fiber_port_failure",
        "service_impact_class": ServiceImpactClass.PARTIAL_OUTAGE,
        "auto_clear_policy": AutoClearPolicy.AUTO_OR_MANUAL,
        "deduplication_window_seconds": 600,
        "correlation_family": "dedicated_access",
        "default_incident_type": IncidentType.NETWORK_OUTAGE,
        "is_root_candidate": True,
        "impact_class": "partial_outage",
    },
    {
        "code": "SLA_LATENCY_BREACH",
        "name": "SLA latency breach",
        "category": AlarmCategory.QUALITY,
        "severity": Severity.MAJOR,
        "allowed_source_kinds": [AlarmSourceKind.SUBSCRIPTION_CONNECTION],
        "supported_device_types": [],
        "probable_cause_family": "metro_ethernet_sla_latency",
        "service_impact_class": ServiceImpactClass.DEGRADATION,
        "auto_clear_policy": AutoClearPolicy.AUTO,
        "deduplication_window_seconds": 900,
        "correlation_family": "sla_quality",
        "default_incident_type": IncidentType.SERVICE_DEGRADATION,
        "is_root_candidate": False,
        "impact_class": "degradation",
    },
    {
        "code": "SLA_PACKET_LOSS_BREACH",
        "name": "SLA packet-loss breach",
        "category": AlarmCategory.QUALITY,
        "severity": Severity.MAJOR,
        "allowed_source_kinds": [AlarmSourceKind.SUBSCRIPTION_CONNECTION],
        "supported_device_types": [],
        "probable_cause_family": "metro_ethernet_sla_packet_loss",
        "service_impact_class": ServiceImpactClass.DEGRADATION,
        "auto_clear_policy": AutoClearPolicy.AUTO,
        "deduplication_window_seconds": 900,
        "correlation_family": "sla_quality",
        "default_incident_type": IncidentType.SERVICE_DEGRADATION,
        "is_root_candidate": False,
        "impact_class": "degradation",
    },
    {
        "code": "PRIMARY_PATH_DOWN",
        "name": "Primary path down",
        "category": AlarmCategory.TRANSPORT,
        "severity": Severity.MAJOR,
        "allowed_source_kinds": [AlarmSourceKind.SUBSCRIPTION_CONNECTION],
        "supported_device_types": [],
        "probable_cause_family": "primary_access_path_failure",
        "service_impact_class": ServiceImpactClass.PROTECTION_LOSS,
        "auto_clear_policy": AutoClearPolicy.AUTO_OR_MANUAL,
        "deduplication_window_seconds": 600,
        "correlation_family": "protection",
        "default_incident_type": IncidentType.PROTECTION_EVENT,
        "is_root_candidate": True,
        "impact_class": "protection_loss",
    },
    {
        "code": "FAILOVER_UNSUCCESSFUL",
        "name": "Failover unsuccessful",
        "category": AlarmCategory.TRANSPORT,
        "severity": Severity.CRITICAL,
        "allowed_source_kinds": [AlarmSourceKind.SUBSCRIPTION_CONNECTION],
        "supported_device_types": [],
        "probable_cause_family": "protection_failover_failed",
        "service_impact_class": ServiceImpactClass.FULL_OUTAGE,
        "auto_clear_policy": AutoClearPolicy.AUTO_OR_MANUAL,
        "deduplication_window_seconds": 600,
        "correlation_family": "protection",
        "default_incident_type": IncidentType.NETWORK_OUTAGE,
        "is_root_candidate": True,
        "impact_class": "full_outage",
    },
    {
        "code": "COMMERCIAL_POWER_LOSS",
        "name": "Commercial power loss",
        "category": AlarmCategory.POWER,
        "severity": Severity.CRITICAL,
        "allowed_source_kinds": [AlarmSourceKind.FAILURE_DOMAIN],
        "supported_device_types": [],
        "probable_cause_family": "commercial_power_failure",
        "service_impact_class": ServiceImpactClass.PARTIAL_OUTAGE,
        "auto_clear_policy": AutoClearPolicy.MANUAL,
        "deduplication_window_seconds": 1800,
        "correlation_family": "power",
        "default_incident_type": IncidentType.NETWORK_OUTAGE,
        "is_root_candidate": True,
        "impact_class": "partial_outage",
    },
    {
        "code": "BACKUP_POWER_DEGRADED",
        "name": "Backup power degraded",
        "category": AlarmCategory.POWER,
        "severity": Severity.MAJOR,
        "allowed_source_kinds": [AlarmSourceKind.FAILURE_DOMAIN],
        "supported_device_types": [],
        "probable_cause_family": "backup_power_degraded",
        "service_impact_class": ServiceImpactClass.PROTECTION_LOSS,
        "auto_clear_policy": AutoClearPolicy.AUTO_OR_MANUAL,
        "deduplication_window_seconds": 1800,
        "correlation_family": "power",
        "default_incident_type": IncidentType.PROTECTION_EVENT,
        "is_root_candidate": False,
        "impact_class": "protection_loss",
    },
    {
        "code": "HIGH_TEMPERATURE",
        "name": "High temperature",
        "category": AlarmCategory.POWER,
        "severity": Severity.MAJOR,
        "allowed_source_kinds": [AlarmSourceKind.DEVICE],
        "supported_device_types": [],
        "probable_cause_family": "environment_temperature",
        "service_impact_class": ServiceImpactClass.DEGRADATION,
        "auto_clear_policy": AutoClearPolicy.AUTO,
        "deduplication_window_seconds": 900,
        "correlation_family": "environment",
        "default_incident_type": IncidentType.SERVICE_DEGRADATION,
        "is_root_candidate": True,
        "impact_class": "degradation",
    },
    {
        "code": "COOLING_FAILURE",
        "name": "Fan or cooling failure",
        "category": AlarmCategory.POWER,
        "severity": Severity.MAJOR,
        "allowed_source_kinds": [AlarmSourceKind.DEVICE, AlarmSourceKind.FAILURE_DOMAIN],
        "supported_device_types": [],
        "probable_cause_family": "cooling_failure",
        "service_impact_class": ServiceImpactClass.DEGRADATION,
        "auto_clear_policy": AutoClearPolicy.AUTO_OR_MANUAL,
        "deduplication_window_seconds": 900,
        "correlation_family": "environment",
        "default_incident_type": IncidentType.SERVICE_DEGRADATION,
        "is_root_candidate": True,
        "impact_class": "degradation",
    },
    {
        "code": "DEVICE_RESOURCE_HIGH",
        "name": "Device CPU or memory high",
        "category": AlarmCategory.QUALITY,
        "severity": Severity.WARNING,
        "allowed_source_kinds": [AlarmSourceKind.DEVICE],
        "supported_device_types": [],
        "probable_cause_family": "device_resource_pressure",
        "service_impact_class": ServiceImpactClass.NO_DIRECT_CUSTOMER_IMPACT,
        "auto_clear_policy": AutoClearPolicy.AUTO,
        "deduplication_window_seconds": 900,
        "correlation_family": "capacity",
        "default_incident_type": IncidentType.UNKNOWN,
        "is_root_candidate": False,
        "impact_class": "no_direct_customer_impact",
    },
    {
        "code": "BANDWIDTH_UTIL_HIGH",
        "name": "Bandwidth utilization high",
        "category": AlarmCategory.QUALITY,
        "severity": Severity.WARNING,
        "allowed_source_kinds": [AlarmSourceKind.NETWORK_LINK, AlarmSourceKind.NETWORK_PORT],
        "supported_device_types": [],
        "probable_cause_family": "bandwidth_capacity_pressure",
        "service_impact_class": ServiceImpactClass.DEGRADATION,
        "auto_clear_policy": AutoClearPolicy.AUTO,
        "deduplication_window_seconds": 900,
        "correlation_family": "capacity",
        "default_incident_type": IncidentType.SERVICE_DEGRADATION,
        "is_root_candidate": False,
        "impact_class": "degradation",
    },
    {
        "code": "DISTRIBUTION_CABLE_DOWN",
        "name": "Distribution cable down",
        "category": AlarmCategory.ACCESS,
        "severity": Severity.MAJOR,
        "allowed_source_kinds": [
            AlarmSourceKind.NETWORK_LINK,
            AlarmSourceKind.FAILURE_DOMAIN,
        ],
        "supported_device_types": [],
        "probable_cause_family": "distribution_fiber_failure",
        "service_impact_class": ServiceImpactClass.PARTIAL_OUTAGE,
        "auto_clear_policy": AutoClearPolicy.MANUAL,
        "deduplication_window_seconds": 1800,
        "correlation_family": "distribution_fiber",
        "default_incident_type": IncidentType.NETWORK_OUTAGE,
        "is_root_candidate": True,
        "impact_class": "partial_outage",
    },
]

SCENARIO_TEMPLATES = [
    {
        "code": "SCN-BNG-DOWN-001",
        "profile": "istanbul_high_density",
        "source": "bng",
        "alarm_codes": ["BNG_UNREACHABLE", "UPLINK_DOWN"],
        "incident_type": IncidentType.NETWORK_OUTAGE,
        "service_impact_class": ServiceImpactClass.FULL_OUTAGE,
        "planned": False,
        "ground_truth_candidate": True,
        "expected_root_cause": "bng",
        "failover_result": FailoverResult.UNKNOWN,
    },
    {
        "code": "SCN-METRO-AGG-001",
        "profile": "metro_aggregation_branch",
        "source": "metro_aggregation",
        "alarm_codes": ["METRO_AGG_UNREACHABLE", "ACCESS_NODE_UNREACHABLE"],
        "incident_type": IncidentType.NETWORK_OUTAGE,
        "service_impact_class": ServiceImpactClass.PARTIAL_OUTAGE,
        "planned": False,
        "ground_truth_candidate": True,
        "expected_root_cause": "metro_aggregation",
        "failover_result": FailoverResult.UNKNOWN,
    },
    {
        "code": "SCN-FIBER-ROUTE-001",
        "profile": "shared_fiber_route",
        "source": "failure_domain",
        "alarm_codes": ["FIBER_CUT_SUSPECTED", "UPLINK_DOWN", "LINK_PACKET_LOSS_HIGH"],
        "incident_type": IncidentType.NETWORK_OUTAGE,
        "service_impact_class": ServiceImpactClass.PARTIAL_OUTAGE,
        "planned": False,
        "ground_truth_candidate": True,
        "expected_root_cause": "fiber_route",
        "failover_result": FailoverResult.UNKNOWN,
    },
    {
        "code": "SCN-POWER-001",
        "profile": "shared_power_zone",
        "source": "failure_domain",
        "alarm_codes": ["COMMERCIAL_POWER_LOSS", "BACKUP_POWER_DEGRADED"],
        "incident_type": IncidentType.NETWORK_OUTAGE,
        "service_impact_class": ServiceImpactClass.PARTIAL_OUTAGE,
        "planned": False,
        "ground_truth_candidate": True,
        "expected_root_cause": "power_zone",
        "failover_result": FailoverResult.UNKNOWN,
    },
    {
        "code": "SCN-PON-PORT-001",
        "profile": "gpon_access",
        "source": "network_port",
        "alarm_codes": ["PON_PORT_DOWN", "ONT_DISCONNECT_SURGE"],
        "incident_type": IncidentType.NETWORK_OUTAGE,
        "service_impact_class": ServiceImpactClass.PARTIAL_OUTAGE,
        "planned": False,
        "ground_truth_candidate": True,
        "expected_root_cause": "pon_port",
        "failover_result": FailoverResult.UNKNOWN,
    },
    {
        "code": "SCN-DSLAM-PORT-GROUP-001",
        "profile": "xdsl_access",
        "source": "device",
        "alarm_codes": ["DSL_PORT_DOWN", "DSLAM_PORT_SATURATION"],
        "incident_type": IncidentType.NETWORK_OUTAGE,
        "service_impact_class": ServiceImpactClass.PARTIAL_OUTAGE,
        "planned": False,
        "ground_truth_candidate": True,
        "expected_root_cause": "dslam_port_group",
        "failover_result": FailoverResult.UNKNOWN,
    },
    {
        "code": "SCN-LINK-FLAP-001",
        "profile": "intermittent_transport",
        "source": "network_link",
        "alarm_codes": ["LINK_FLAPPING"],
        "incident_type": IncidentType.INTERMITTENT,
        "service_impact_class": ServiceImpactClass.SHORT_INTERRUPTION,
        "planned": False,
        "ground_truth_candidate": True,
        "expected_root_cause": "intermittent_link",
        "failover_result": FailoverResult.UNKNOWN,
    },
    {
        "code": "SCN-DSL-QUALITY-001",
        "profile": "legacy_xdsl_quality",
        "source": "line_connection",
        "alarm_codes": ["DSL_LINE_QUALITY_DEGRADED", "DSL_RETRAIN_FREQUENT"],
        "incident_type": IncidentType.SERVICE_DEGRADATION,
        "service_impact_class": ServiceImpactClass.DEGRADATION,
        "planned": False,
        "ground_truth_candidate": True,
        "expected_root_cause": "line_quality",
        "failover_result": FailoverResult.UNKNOWN,
    },
    {
        "code": "SCN-SLA-LATENCY-001",
        "profile": "metro_ethernet_sla",
        "source": "subscription_connection",
        "alarm_codes": ["SLA_LATENCY_BREACH", "SLA_PACKET_LOSS_BREACH"],
        "incident_type": IncidentType.SERVICE_DEGRADATION,
        "service_impact_class": ServiceImpactClass.DEGRADATION,
        "planned": False,
        "ground_truth_candidate": True,
        "expected_root_cause": "sla_quality",
        "failover_result": FailoverResult.UNKNOWN,
    },
    {
        "code": "SCN-FAILOVER-HITLESS-001",
        "profile": "critical_enterprise",
        "source": "subscription_connection",
        "alarm_codes": ["PRIMARY_PATH_DOWN"],
        "incident_type": IncidentType.PROTECTION_EVENT,
        "service_impact_class": ServiceImpactClass.PROTECTION_LOSS,
        "planned": False,
        "ground_truth_candidate": True,
        "expected_root_cause": "primary_path",
        "failover_result": FailoverResult.HITLESS,
        "creates_outage": False,
    },
    {
        "code": "SCN-FAILOVER-SHORT-001",
        "profile": "critical_enterprise",
        "source": "subscription_connection",
        "alarm_codes": ["PRIMARY_PATH_DOWN"],
        "incident_type": IncidentType.PROTECTION_EVENT,
        "service_impact_class": ServiceImpactClass.SHORT_INTERRUPTION,
        "planned": False,
        "ground_truth_candidate": True,
        "expected_root_cause": "primary_path",
        "failover_result": FailoverResult.SHORT_INTERRUPTION,
        "creates_outage": True,
    },
    {
        "code": "SCN-FAILOVER-DEGRADED-001",
        "profile": "critical_enterprise",
        "source": "subscription_connection",
        "alarm_codes": ["PRIMARY_PATH_DOWN", "SLA_LATENCY_BREACH"],
        "incident_type": IncidentType.PROTECTION_EVENT,
        "service_impact_class": ServiceImpactClass.DEGRADATION,
        "planned": False,
        "ground_truth_candidate": True,
        "expected_root_cause": "primary_path",
        "failover_result": FailoverResult.DEGRADED,
        "creates_outage": False,
    },
    {
        "code": "SCN-FAILOVER-FAILED-001",
        "profile": "critical_enterprise",
        "source": "subscription_connection",
        "alarm_codes": ["PRIMARY_PATH_DOWN", "FAILOVER_UNSUCCESSFUL"],
        "incident_type": IncidentType.NETWORK_OUTAGE,
        "service_impact_class": ServiceImpactClass.FULL_OUTAGE,
        "planned": False,
        "ground_truth_candidate": True,
        "expected_root_cause": "protection_failure",
        "failover_result": FailoverResult.FAILED,
        "creates_outage": True,
    },
    {
        "code": "SCN-BACKUP-LOSS-001",
        "profile": "protected_customer_no_impact",
        "source": "subscription_connection",
        "alarm_codes": ["BACKUP_LINK_UNAVAILABLE"],
        "incident_type": IncidentType.PROTECTION_EVENT,
        "service_impact_class": ServiceImpactClass.PROTECTION_LOSS,
        "planned": False,
        "ground_truth_candidate": True,
        "expected_root_cause": "backup_path",
        "failover_result": FailoverResult.UNKNOWN,
        "creates_outage": False,
    },
    {
        "code": "SCN-SHARED-RISK-FAILOVER-001",
        "profile": "shared_failure_domain",
        "source": "failure_domain",
        "alarm_codes": ["FIBER_CUT_SUSPECTED", "PRIMARY_PATH_DOWN", "FAILOVER_UNSUCCESSFUL"],
        "incident_type": IncidentType.NETWORK_OUTAGE,
        "service_impact_class": ServiceImpactClass.FULL_OUTAGE,
        "planned": False,
        "ground_truth_candidate": True,
        "expected_root_cause": "shared_failure_domain",
        "failover_result": FailoverResult.FAILED,
        "creates_outage": True,
    },
    {
        "code": "SCN-PLANNED-MAINT-001",
        "profile": "planned_maintenance",
        "source": "maintenance_window",
        "alarm_codes": ["UPLINK_DOWN"],
        "incident_type": IncidentType.PLANNED_MAINTENANCE,
        "service_impact_class": ServiceImpactClass.SHORT_INTERRUPTION,
        "planned": True,
        "ground_truth_candidate": True,
        "expected_root_cause": "planned_work",
        "failover_result": FailoverResult.UNKNOWN,
    },
    {
        "code": "SCN-PLANNED-OVERRUN-001",
        "profile": "maintenance_overrun",
        "source": "maintenance_window",
        "alarm_codes": ["UPLINK_DOWN", "LINK_FLAPPING"],
        "incident_type": IncidentType.NETWORK_OUTAGE,
        "service_impact_class": ServiceImpactClass.PARTIAL_OUTAGE,
        "planned": False,
        "linked_maintenance_window": True,
        "ground_truth_candidate": True,
        "expected_root_cause": "maintenance_overrun",
        "failover_result": FailoverResult.UNKNOWN,
    },
    {
        "code": "SCN-ACCESS-NODE-001",
        "city": "İstanbul",
        "district": "Şişli",
        "profile": "corporate_access_node",
        "source": "device",
        "alarm_codes": ["ACCESS_NODE_UNREACHABLE", "DEDICATED_PORT_DOWN"],
        "incident_type": IncidentType.NETWORK_OUTAGE,
        "service_impact_class": ServiceImpactClass.PARTIAL_OUTAGE,
        "planned": False,
        "ground_truth_candidate": True,
        "expected_root_cause": "access_node",
        "failover_result": FailoverResult.UNKNOWN,
    },
    {
        "code": "SCN-CAPACITY-001",
        "profile": "capacity_pressure",
        "source": "network_port",
        "alarm_codes": ["PON_CAPACITY_THRESHOLD", "BANDWIDTH_UTIL_HIGH", "DEVICE_RESOURCE_HIGH"],
        "incident_type": IncidentType.SERVICE_DEGRADATION,
        "service_impact_class": ServiceImpactClass.DEGRADATION,
        "planned": False,
        "ground_truth_candidate": True,
        "expected_root_cause": "capacity",
        "failover_result": FailoverResult.UNKNOWN,
    },
    {
        "code": "SCN-ENVIRONMENT-001",
        "profile": "site_environment",
        "source": "failure_domain",
        "alarm_codes": ["HIGH_TEMPERATURE", "COOLING_FAILURE", "DEVICE_RESOURCE_HIGH"],
        "incident_type": IncidentType.SERVICE_DEGRADATION,
        "service_impact_class": ServiceImpactClass.DEGRADATION,
        "planned": False,
        "ground_truth_candidate": True,
        "expected_root_cause": "environment",
        "failover_result": FailoverResult.UNKNOWN,
    },
    {
        "code": "SCN-NOISE-001",
        "profile": "noise_alarm",
        "source": "device",
        "alarm_codes": ["DEVICE_RESOURCE_HIGH"],
        "creates_incident": False,
        "service_impact_class": ServiceImpactClass.NO_DIRECT_CUSTOMER_IMPACT,
        "planned": False,
        "ground_truth_candidate": True,
        "expected_root_cause": "none",
        "failover_result": FailoverResult.UNKNOWN,
    },
    {
        "code": "SCN-UNKNOWN-RCA-001",
        "profile": "missing_alarm_data",
        "source": "unknown",
        "alarm_codes": ["LINK_PACKET_LOSS_HIGH"],
        "incident_type": IncidentType.UNKNOWN,
        "service_impact_class": ServiceImpactClass.UNKNOWN,
        "planned": False,
        "ground_truth_candidate": True,
        "expected_root_cause": "unknown",
        "failover_result": FailoverResult.UNKNOWN,
    },
]

FAILOVER_TRANSITION_CLASSES = {
    "hitless": {
        "transition_duration_seconds_max": 1,
        "customer_result": "no_customer_impact",
    },
    "near_hitless": {
        "transition_duration_seconds_max": 5,
        "customer_result": "short_interruption",
    },
    "short_interruption": {
        "transition_duration_seconds_min": 6,
        "transition_duration_seconds_max": 60,
        "customer_result": "short_interruption",
    },
    "degraded": {
        "transition_duration_seconds_min": 0,
        "customer_result": "degradation",
    },
    "failed": {
        "customer_result": "full_outage",
    },
}

DATASET_VOLUME_TARGETS = {
    "alarm_types": 31,
    "alarms": 2100,
    "cleared_alarms": 1680,
    "open_alarms": 210,
    "suppressed_alarms": 210,
    "acknowledged_open_alarms": 105,
    "incidents": 210,
    "outages": 78,
    "degradation_incidents": 60,
    "protection_loss_incidents": 22,
    "maintenance_windows": 30,
    "operational_events": 900,
    "quality_measurements": 12000,
    "timeline_days": 60,
    "intense_event_days": 9,
    "planned_maintenance_intense_days": 3,
    "recurring_flapping_days": 4,
}

assert len(ALARM_CATALOG) == DATASET_VOLUME_TARGETS["alarm_types"]
assert len(SCENARIO_TEMPLATES) == 22
