GENERATOR_VERSION = "realistic-commercial-profile-v1"
FIXED_RANDOM_SEED = "realistic-commercial-fixed-seed-v1"
DEFAULT_REFERENCE_DATETIME = "2026-08-01T00:00:00+03:00"

DATASET_SCALE = {
    "customers": 14400,
    "subscriptions": 16200,
    "segments": {
        "individual": 9208,
        "sme": 3243,
        "enterprise": 1517,
        "public": 432,
    },
    "priority_levels": {
        "vip": 862,
        "standard": 13538,
    },
    "customer_subscription_counts": {
        "single_subscription": 12830,
        "two_subscriptions": 1340,
        "three_subscriptions": 230,
        "four_or_more_subscriptions": 0,
    },
    "subscription_statuses": {
        "active": 15256,
        "suspended": 465,
        "cancelled": 306,
        "pending": 173,
    },
    "subscription_connections": {
        "open_primary_at_reference": 15721,
        "historical_cancelled_primary": 306,
        "total_primary_records": 16027,
        "backup_records": 208,
        "total_records": 16235,
        "pending_without_connection": 173,
    },
}

DISTRICT_COMMERCIAL_DISTRIBUTION = {
    "Maltepe": {
        "customers": 1400,
        "subscriptions": 1550,
        "segments": {"individual": 1092, "sme": 210, "enterprise": 70, "public": 28},
        "priority": {"vip": 70, "standard": 1330},
        "subscription_counts": {"single": 1260, "double": 130, "triple": 10},
        "subscription_statuses": {"active": 1457, "suspended": 47, "cancelled": 31, "pending": 15},
    },
    "Şişli": {
        "customers": 1100,
        "subscriptions": 1320,
        "segments": {"individual": 385, "sme": 385, "enterprise": 275, "public": 55},
        "priority": {"vip": 99, "standard": 1001},
        "subscription_counts": {"single": 920, "double": 140, "triple": 40},
        "subscription_statuses": {"active": 1247, "suspended": 40, "cancelled": 20, "pending": 13},
    },
    "Esenyurt": {
        "customers": 2200,
        "subscriptions": 2350,
        "segments": {"individual": 1936, "sme": 220, "enterprise": 33, "public": 11},
        "priority": {"vip": 66, "standard": 2134},
        "subscription_counts": {"single": 2058, "double": 134, "triple": 8},
        "subscription_statuses": {"active": 2185, "suspended": 94, "cancelled": 47, "pending": 24},
    },
    "Çankaya": {
        "customers": 1400,
        "subscriptions": 1650,
        "segments": {"individual": 700, "sme": 308, "enterprise": 252, "public": 140},
        "priority": {"vip": 126, "standard": 1274},
        "subscription_counts": {"single": 1195, "double": 160, "triple": 45},
        "subscription_statuses": {"active": 1568, "suspended": 33, "cancelled": 33, "pending": 16},
    },
    "Yenimahalle": {
        "customers": 1100,
        "subscriptions": 1260,
        "segments": {"individual": 605, "sme": 352, "enterprise": 110, "public": 33},
        "priority": {"vip": 66, "standard": 1034},
        "subscription_counts": {"single": 960, "double": 120, "triple": 20},
        "subscription_statuses": {"active": 1178, "suspended": 44, "cancelled": 25, "pending": 13},
    },
    "Etimesgut": {
        "customers": 1000,
        "subscriptions": 1080,
        "segments": {"individual": 820, "sme": 130, "enterprise": 30, "public": 20},
        "priority": {"vip": 40, "standard": 960},
        "subscription_counts": {"single": 925, "double": 70, "triple": 5},
        "subscription_statuses": {"active": 1026, "suspended": 22, "cancelled": 11, "pending": 21},
    },
    "Konak": {
        "customers": 1000,
        "subscriptions": 1100,
        "segments": {"individual": 680, "sme": 240, "enterprise": 60, "public": 20},
        "priority": {"vip": 50, "standard": 950},
        "subscription_counts": {"single": 908, "double": 84, "triple": 8},
        "subscription_statuses": {"active": 1023, "suspended": 44, "cancelled": 22, "pending": 11},
    },
    "Bornova": {
        "customers": 1100,
        "subscriptions": 1230,
        "segments": {"individual": 792, "sme": 220, "enterprise": 55, "public": 33},
        "priority": {"vip": 55, "standard": 1045},
        "subscription_counts": {"single": 982, "double": 106, "triple": 12},
        "subscription_statuses": {"active": 1156, "suspended": 37, "cancelled": 25, "pending": 12},
    },
    "Karşıyaka": {
        "customers": 900,
        "subscriptions": 990,
        "segments": {"individual": 738, "sme": 126, "enterprise": 27, "public": 9},
        "priority": {"vip": 54, "standard": 846},
        "subscription_counts": {"single": 815, "double": 80, "triple": 5},
        "subscription_statuses": {"active": 941, "suspended": 20, "cancelled": 19, "pending": 10},
    },
    "İzmit": {
        "customers": 1000,
        "subscriptions": 1110,
        "segments": {"individual": 600, "sme": 270, "enterprise": 100, "public": 30},
        "priority": {"vip": 60, "standard": 940},
        "subscription_counts": {"single": 902, "double": 86, "triple": 12},
        "subscription_statuses": {"active": 1043, "suspended": 33, "cancelled": 22, "pending": 12},
    },
    "Gebze": {
        "customers": 1300,
        "subscriptions": 1500,
        "segments": {"individual": 455, "sme": 494, "enterprise": 325, "public": 26},
        "priority": {"vip": 104, "standard": 1196},
        "subscription_counts": {"single": 1145, "double": 110, "triple": 45},
        "subscription_statuses": {"active": 1425, "suspended": 30, "cancelled": 30, "pending": 15},
    },
    "Körfez": {
        "customers": 900,
        "subscriptions": 1060,
        "segments": {"individual": 405, "sme": 288, "enterprise": 180, "public": 27},
        "priority": {"vip": 72, "standard": 828},
        "subscription_counts": {"single": 760, "double": 120, "triple": 20},
        "subscription_statuses": {"active": 1007, "suspended": 21, "cancelled": 21, "pending": 11},
    },
}

TECHNOLOGY_TOTALS = {
    "gpon": 7577,
    "fiber": 2042,
    "vdsl": 5894,
    "adsl": 687,
    "metro_ethernet_subset_of_fiber": 520,
}

SLA_PROFILES = [
    {
        "code": "best_effort",
        "name": "Best Effort",
        "availability_target_percent": "99.00",
        "support_window": "8x5",
        "response_target_minutes": 1440,
        "restoration_target_minutes": 4320,
        "latency_threshold_ms": 80,
        "jitter_threshold_ms": 30,
        "packet_loss_threshold_percent": "2.00",
        "backup_requirement": "none",
        "required_path_diversity": "not_required",
        "monitoring_level": "standard",
        "is_contractual": False,
        "active": True,
    },
    {
        "code": "business_standard",
        "name": "Business Standard",
        "availability_target_percent": "99.50",
        "support_window": "8x5",
        "response_target_minutes": 480,
        "restoration_target_minutes": 1440,
        "latency_threshold_ms": 50,
        "jitter_threshold_ms": 20,
        "packet_loss_threshold_percent": "1.00",
        "backup_requirement": "optional",
        "required_path_diversity": "not_required",
        "monitoring_level": "enhanced",
        "is_contractual": True,
        "active": True,
    },
    {
        "code": "business_plus",
        "name": "Business Plus",
        "availability_target_percent": "99.90",
        "support_window": "extended",
        "response_target_minutes": 120,
        "restoration_target_minutes": 480,
        "latency_threshold_ms": 35,
        "jitter_threshold_ms": 15,
        "packet_loss_threshold_percent": "0.50",
        "backup_requirement": "recommended",
        "required_path_diversity": "partially_diverse",
        "monitoring_level": "proactive",
        "is_contractual": True,
        "active": True,
    },
    {
        "code": "mission_critical",
        "name": "Mission Critical",
        "availability_target_percent": "99.95",
        "support_window": "24x7",
        "response_target_minutes": 15,
        "restoration_target_minutes": 240,
        "latency_threshold_ms": 20,
        "jitter_threshold_ms": 8,
        "packet_loss_threshold_percent": "0.10",
        "backup_requirement": "required",
        "required_path_diversity": "fully_diverse",
        "monitoring_level": "continuous",
        "is_contractual": True,
        "active": True,
    },
    {
        "code": "public_critical",
        "name": "Public Critical",
        "availability_target_percent": "99.95",
        "support_window": "24x7",
        "response_target_minutes": 30,
        "restoration_target_minutes": 240,
        "latency_threshold_ms": 25,
        "jitter_threshold_ms": 10,
        "packet_loss_threshold_percent": "0.20",
        "backup_requirement": "required",
        "required_path_diversity": "fully_diverse",
        "monitoring_level": "continuous",
        "is_contractual": True,
        "active": True,
    },
]

PACKAGE_CATALOG = [
    {
        "code": "ADSL-16-SYN",
        "service_type": "broadband",
        "technology": "adsl",
        "download_mbps": 16,
        "upload_mbps": 2,
        "symmetric": False,
        "allowed_segments": ["individual"],
        "list_price": "199.90",
        "commitment_months": 12,
        "default_sla": "best_effort",
        "backup_eligible": False,
        "status": "active",
        "subscription_count": 470,
    },
    {
        "code": "ADSL-24-SYN",
        "service_type": "broadband",
        "technology": "adsl",
        "download_mbps": 24,
        "upload_mbps": 3,
        "symmetric": False,
        "allowed_segments": ["individual"],
        "list_price": "229.90",
        "commitment_months": 12,
        "default_sla": "best_effort",
        "backup_eligible": False,
        "status": "active",
        "subscription_count": 217,
    },
    {
        "code": "VDSL-35-SYN",
        "service_type": "broadband",
        "technology": "vdsl",
        "download_mbps": 35,
        "upload_mbps": 6,
        "symmetric": False,
        "allowed_segments": ["individual"],
        "list_price": "249.90",
        "commitment_months": 12,
        "default_sla": "best_effort",
        "backup_eligible": False,
        "status": "active",
        "subscription_count": 1700,
    },
    {
        "code": "VDSL-50-SYN",
        "service_type": "broadband",
        "technology": "vdsl",
        "download_mbps": 50,
        "upload_mbps": 10,
        "symmetric": False,
        "allowed_segments": ["individual"],
        "list_price": "299.90",
        "commitment_months": 12,
        "default_sla": "best_effort",
        "backup_eligible": False,
        "status": "active",
        "subscription_count": 1900,
    },
    {
        "code": "VDSL-100-SYN",
        "service_type": "broadband",
        "technology": "vdsl",
        "download_mbps": 100,
        "upload_mbps": 15,
        "symmetric": False,
        "allowed_segments": ["individual"],
        "list_price": "399.90",
        "commitment_months": 12,
        "default_sla": "best_effort",
        "backup_eligible": False,
        "status": "active",
        "subscription_count": 1250,
    },
    {
        "code": "SME-VDSL-50-SYN",
        "service_type": "broadband",
        "technology": "vdsl",
        "download_mbps": 50,
        "upload_mbps": 10,
        "symmetric": False,
        "allowed_segments": ["sme"],
        "list_price": "349.90",
        "commitment_months": 12,
        "default_sla": "business_standard",
        "backup_eligible": False,
        "status": "active",
        "subscription_count": 650,
    },
    {
        "code": "SME-VDSL-100-SYN",
        "service_type": "broadband",
        "technology": "vdsl",
        "download_mbps": 100,
        "upload_mbps": 20,
        "symmetric": False,
        "allowed_segments": ["sme"],
        "list_price": "449.90",
        "commitment_months": 12,
        "default_sla": "business_standard",
        "backup_eligible": False,
        "status": "active",
        "subscription_count": 250,
    },
    {
        "code": "PUB-VDSL-50-SYN",
        "service_type": "broadband",
        "technology": "vdsl",
        "download_mbps": 50,
        "upload_mbps": 10,
        "symmetric": False,
        "allowed_segments": ["public"],
        "list_price": "369.90",
        "commitment_months": 12,
        "default_sla": "business_standard",
        "backup_eligible": False,
        "status": "active",
        "subscription_count": 144,
    },
    {
        "code": "FIBER-100-SYN",
        "service_type": "broadband",
        "technology": "fiber",
        "download_mbps": 100,
        "upload_mbps": 20,
        "symmetric": False,
        "allowed_segments": ["individual"],
        "list_price": "399.90",
        "commitment_months": 12,
        "default_sla": "best_effort",
        "backup_eligible": False,
        "status": "active",
        "subscription_count": 2200,
    },
    {
        "code": "FIBER-200-SYN",
        "service_type": "broadband",
        "technology": "fiber",
        "download_mbps": 200,
        "upload_mbps": 30,
        "symmetric": False,
        "allowed_segments": ["individual"],
        "list_price": "499.90",
        "commitment_months": 12,
        "default_sla": "best_effort",
        "backup_eligible": False,
        "status": "active",
        "subscription_count": 1900,
    },
    {
        "code": "FIBER-500-SYN",
        "service_type": "broadband",
        "technology": "fiber",
        "download_mbps": 500,
        "upload_mbps": 50,
        "symmetric": False,
        "allowed_segments": ["individual"],
        "list_price": "699.90",
        "commitment_months": 12,
        "default_sla": "best_effort",
        "backup_eligible": False,
        "status": "active",
        "subscription_count": 1200,
    },
    {
        "code": "FIBER-1000-SYN",
        "service_type": "broadband",
        "technology": "fiber",
        "download_mbps": 1000,
        "upload_mbps": 100,
        "symmetric": False,
        "allowed_segments": ["individual"],
        "list_price": "1199.90",
        "commitment_months": 12,
        "default_sla": "best_effort",
        "backup_eligible": False,
        "status": "active",
        "subscription_count": 600,
    },
    {
        "code": "FIBER-NC-100-SYN",
        "service_type": "broadband",
        "technology": "fiber",
        "download_mbps": 100,
        "upload_mbps": 20,
        "symmetric": False,
        "allowed_segments": ["individual"],
        "list_price": "449.90",
        "commitment_months": 0,
        "default_sla": "best_effort",
        "backup_eligible": False,
        "status": "active",
        "subscription_count": 700,
    },
    {
        "code": "SME-FIBER-100-SYN",
        "service_type": "broadband",
        "technology": "fiber",
        "download_mbps": 100,
        "upload_mbps": 30,
        "symmetric": False,
        "allowed_segments": ["sme"],
        "list_price": "499.90",
        "commitment_months": 12,
        "default_sla": "business_standard",
        "backup_eligible": False,
        "status": "active",
        "subscription_count": 650,
    },
    {
        "code": "SME-FIBER-300-SYN",
        "service_type": "broadband",
        "technology": "fiber",
        "download_mbps": 300,
        "upload_mbps": 50,
        "symmetric": False,
        "allowed_segments": ["sme"],
        "list_price": "699.90",
        "commitment_months": 12,
        "default_sla": "business_standard",
        "backup_eligible": False,
        "status": "active",
        "subscription_count": 520,
    },
    {
        "code": "SME-FIBER-500-SYN",
        "service_type": "broadband",
        "technology": "fiber",
        "download_mbps": 500,
        "upload_mbps": 100,
        "symmetric": False,
        "allowed_segments": ["sme"],
        "list_price": "899.90",
        "commitment_months": 12,
        "default_sla": "business_plus",
        "backup_eligible": False,
        "status": "active",
        "subscription_count": 360,
    },
    {
        "code": "ENT-FIBER-500-SYN",
        "service_type": "broadband",
        "technology": "fiber",
        "download_mbps": 500,
        "upload_mbps": 100,
        "symmetric": False,
        "allowed_segments": ["enterprise"],
        "list_price": "999.90",
        "commitment_months": 12,
        "default_sla": "business_plus",
        "backup_eligible": False,
        "status": "active",
        "subscription_count": 300,
    },
    {
        "code": "ENT-FIBER-1000-SYN",
        "service_type": "broadband",
        "technology": "fiber",
        "download_mbps": 1000,
        "upload_mbps": 200,
        "symmetric": False,
        "allowed_segments": ["enterprise"],
        "list_price": "1499.90",
        "commitment_months": 12,
        "default_sla": "business_plus",
        "backup_eligible": False,
        "status": "active",
        "subscription_count": 260,
    },
    {
        "code": "ENT-FIBER-2000-SYN",
        "service_type": "broadband",
        "technology": "fiber",
        "download_mbps": 2000,
        "upload_mbps": 500,
        "symmetric": False,
        "allowed_segments": ["enterprise"],
        "list_price": "2499.90",
        "commitment_months": 12,
        "default_sla": "mission_critical",
        "backup_eligible": False,
        "status": "active",
        "subscription_count": 140,
    },
    {
        "code": "PUB-FIBER-200-SYN",
        "service_type": "broadband",
        "technology": "fiber",
        "download_mbps": 200,
        "upload_mbps": 50,
        "symmetric": False,
        "allowed_segments": ["public"],
        "list_price": "699.90",
        "commitment_months": 12,
        "default_sla": "business_standard",
        "backup_eligible": False,
        "status": "active",
        "subscription_count": 120,
    },
    {
        "code": "PUB-FIBER-500-SYN",
        "service_type": "broadband",
        "technology": "fiber",
        "download_mbps": 500,
        "upload_mbps": 100,
        "symmetric": False,
        "allowed_segments": ["public"],
        "list_price": "999.90",
        "commitment_months": 12,
        "default_sla": "business_plus",
        "backup_eligible": False,
        "status": "active",
        "subscription_count": 100,
    },
    {
        "code": "PUB-FIBER-1000-SYN",
        "service_type": "broadband",
        "technology": "fiber",
        "download_mbps": 1000,
        "upload_mbps": 200,
        "symmetric": False,
        "allowed_segments": ["public"],
        "list_price": "1499.90",
        "commitment_months": 12,
        "default_sla": "public_critical",
        "backup_eligible": False,
        "status": "active",
        "subscription_count": 49,
    },
    {
        "code": "METRO-50-SYN",
        "service_type": "metro_ethernet",
        "technology": "fiber",
        "download_mbps": 50,
        "upload_mbps": 50,
        "symmetric": True,
        "allowed_segments": ["sme", "enterprise", "public"],
        "list_price": "1799.90",
        "commitment_months": 24,
        "default_sla": "business_plus",
        "backup_eligible": True,
        "status": "active",
        "subscription_count": 90,
    },
    {
        "code": "METRO-100-SYN",
        "service_type": "metro_ethernet",
        "technology": "fiber",
        "download_mbps": 100,
        "upload_mbps": 100,
        "symmetric": True,
        "allowed_segments": ["sme", "enterprise", "public"],
        "list_price": "2499.90",
        "commitment_months": 24,
        "default_sla": "business_plus",
        "backup_eligible": True,
        "status": "active",
        "subscription_count": 140,
    },
    {
        "code": "METRO-200-SYN",
        "service_type": "metro_ethernet",
        "technology": "fiber",
        "download_mbps": 200,
        "upload_mbps": 200,
        "symmetric": True,
        "allowed_segments": ["enterprise", "public"],
        "list_price": "3799.90",
        "commitment_months": 24,
        "default_sla": "mission_critical",
        "backup_eligible": True,
        "status": "active",
        "subscription_count": 130,
    },
    {
        "code": "METRO-500-SYN",
        "service_type": "metro_ethernet",
        "technology": "fiber",
        "download_mbps": 500,
        "upload_mbps": 500,
        "symmetric": True,
        "allowed_segments": ["enterprise", "public"],
        "list_price": "6999.90",
        "commitment_months": 24,
        "default_sla": "mission_critical",
        "backup_eligible": True,
        "status": "active",
        "subscription_count": 95,
    },
    {
        "code": "METRO-1000-SYN",
        "service_type": "metro_ethernet",
        "technology": "fiber",
        "download_mbps": 1000,
        "upload_mbps": 1000,
        "symmetric": True,
        "allowed_segments": ["enterprise", "public"],
        "list_price": "11999.90",
        "commitment_months": 24,
        "default_sla": "public_critical",
        "backup_eligible": True,
        "status": "active",
        "subscription_count": 65,
    },
]

CAMPAIGNS = [
    {
        "code": "NEW_CUSTOMER_DISCOUNT",
        "discount_type": "percent",
        "discount_value": "10.00",
        "duration_months": 6,
        "allowed_segments": ["individual", "sme"],
        "allowed_service_types": ["broadband"],
        "allowed_technologies": ["fiber", "gpon", "vdsl", "adsl"],
        "stackable": False,
        "status": "active",
    },
    {
        "code": "COMMITMENT_12M",
        "discount_type": "percent",
        "discount_value": "8.00",
        "duration_months": 12,
        "allowed_segments": ["individual", "sme"],
        "allowed_service_types": ["broadband"],
        "allowed_technologies": ["fiber", "gpon", "vdsl", "adsl"],
        "stackable": True,
        "status": "active",
    },
    {
        "code": "FIBER_MIGRATION",
        "discount_type": "percent",
        "discount_value": "12.00",
        "duration_months": 6,
        "allowed_segments": ["individual", "sme"],
        "allowed_service_types": ["broadband"],
        "allowed_technologies": ["fiber"],
        "stackable": False,
        "status": "active",
    },
    {
        "code": "LOYALTY_RETENTION",
        "discount_type": "fixed_amount",
        "discount_value": "75.00",
        "duration_months": 3,
        "allowed_segments": ["individual", "sme"],
        "allowed_service_types": ["broadband"],
        "allowed_technologies": ["fiber", "vdsl", "adsl"],
        "stackable": False,
        "status": "active",
    },
    {
        "code": "MULTI_SUBSCRIPTION",
        "discount_type": "percent",
        "discount_value": "5.00",
        "duration_months": 12,
        "allowed_segments": ["individual", "sme", "enterprise", "public"],
        "allowed_service_types": ["broadband"],
        "allowed_technologies": ["fiber", "gpon", "vdsl", "adsl"],
        "stackable": True,
        "status": "active",
    },
    {
        "code": "SME_START",
        "discount_type": "percent",
        "discount_value": "15.00",
        "duration_months": 6,
        "allowed_segments": ["sme"],
        "allowed_service_types": ["broadband"],
        "allowed_technologies": ["fiber", "vdsl"],
        "stackable": False,
        "status": "active",
    },
    {
        "code": "ENTERPRISE_VOLUME",
        "discount_type": "percent",
        "discount_value": "18.00",
        "duration_months": 12,
        "allowed_segments": ["enterprise"],
        "allowed_service_types": ["broadband", "metro_ethernet"],
        "allowed_technologies": ["fiber"],
        "stackable": False,
        "status": "active",
    },
    {
        "code": "PUBLIC_FRAMEWORK",
        "discount_type": "percent",
        "discount_value": "20.00",
        "duration_months": 12,
        "allowed_segments": ["public"],
        "allowed_service_types": ["broadband", "metro_ethernet"],
        "allowed_technologies": ["fiber", "vdsl"],
        "stackable": False,
        "status": "active",
    },
    {
        "code": "Q3_SEASONAL",
        "discount_type": "fixed_amount",
        "discount_value": "100.00",
        "duration_months": 2,
        "allowed_segments": ["individual", "sme"],
        "allowed_service_types": ["broadband"],
        "allowed_technologies": ["fiber", "vdsl"],
        "stackable": True,
        "status": "active",
    },
    {
        "code": "METRO_SLA_UPGRADE",
        "discount_type": "percent",
        "discount_value": "7.50",
        "duration_months": 6,
        "allowed_segments": ["sme", "enterprise", "public"],
        "allowed_service_types": ["metro_ethernet"],
        "allowed_technologies": ["fiber"],
        "stackable": True,
        "status": "active",
    },
]

BACKUP_DISTRIBUTION = {
    "by_district": {
        "Maltepe": 0,
        "Şişli": 46,
        "Esenyurt": 1,
        "Çankaya": 50,
        "Yenimahalle": 8,
        "Etimesgut": 1,
        "Konak": 2,
        "Bornova": 4,
        "Karşıyaka": 1,
        "İzmit": 7,
        "Gebze": 55,
        "Körfez": 33,
    },
    "by_segment": {
        "enterprise": 145,
        "public": 34,
        "sme": 29,
        "individual": 0,
    },
    "actual_path_diversity": {
        "fully_diverse": 112,
        "partially_diverse": 60,
        "shared_risk": 24,
        "unknown": 12,
    },
    "reserved_backup_port_capacity": 261,
    "unused_backup_port_capacity": 53,
}

PAYMENT_HISTORY = {
    "timeline_months": ["2026-04", "2026-05", "2026-06", "2026-07"],
    "record_count": 59600,
    "statuses": {
        "paid_on_time": 48000,
        "paid_late": 6200,
        "overdue": 2700,
        "partial": 1500,
        "failed": 600,
        "reversed": 300,
        "voided": 300,
    },
}

CAMPAIGN_ENROLLMENT_TARGETS = {
    "total": 4050,
    "statuses": {
        "active": 2650,
        "completed": 950,
        "cancelled": 200,
        "expired": 250,
    },
}

COMPENSATION_HISTORY_TARGETS = {
    "total": 1100,
    "decision_statuses": {
        "approved": 620,
        "rejected": 300,
        "manual_review": 180,
    },
    "approved_settlement_statuses": {
        "credited": 400,
        "paid": 140,
        "pending": 80,
    },
}

PRICE_VERSION_TARGETS = {
    "service_package_price_versions": 72,
}

SYNTHETIC_COMMERCIAL_DISCLAIMER = (
    "All commercial packages, SLA profiles, prices, campaigns, payment records, "
    "and compensation history targets are synthetic simulation data. They do not "
    "represent real Turkcell products, tariffs, customer contracts, or billing data."
)
