RULE_SET = {
    "code": "SYN-COMP-2026",
    "version": 1,
    "name": "Synthetic compensation policy 2026",
    "effective_from": "2026-07-01T00:00:00+03:00",
    "effective_to": None,
    "active": True,
    "change_reason": (
        "Synthetic policy catalog for the realistic multi-city dataset. "
        "It is not a real Turkcell or operator policy."
    ),
}

PRICE_BASIS = {
    "default": "contracted_monthly_price",
    "allowed": [
        "contracted_monthly_price",
        "billed_recurring_amount",
        "campaign_adjusted_recurring_amount",
        "package_list_price",
    ],
}

BROADBAND_FULL_OUTAGE_TIERS = [
    {"min_seconds": 0, "max_seconds": 1800, "rate": "0.00", "label": "under_30_minutes"},
    {"min_seconds": 1800, "max_seconds": 7200, "rate": "0.02", "label": "30_to_120_minutes"},
    {"min_seconds": 7200, "max_seconds": 21600, "rate": "0.08", "label": "2_to_6_hours"},
    {"min_seconds": 21600, "max_seconds": 86400, "rate": "0.20", "label": "6_to_24_hours"},
    {"min_seconds": 86400, "max_seconds": None, "rate": "0.35", "label": "over_24_hours"},
]

METRO_FAILED_FAILOVER_TIERS = [
    {"min_seconds": 0, "max_seconds": 1800, "rate": "0.02", "label": "under_30_minutes"},
    {"min_seconds": 1800, "max_seconds": 7200, "rate": "0.06", "label": "30_to_120_minutes"},
    {"min_seconds": 7200, "max_seconds": 21600, "rate": "0.12", "label": "2_to_6_hours"},
    {"min_seconds": 21600, "max_seconds": 86400, "rate": "0.25", "label": "6_to_24_hours"},
    {"min_seconds": 86400, "max_seconds": None, "rate": "0.40", "label": "over_24_hours"},
]

SLA_EXCEEDANCE_TIERS = [
    {"min_ratio_exclusive": "1.00", "max_ratio_inclusive": "1.25", "rate": "0.03"},
    {"min_ratio_exclusive": "1.25", "max_ratio_inclusive": "2.00", "rate": "0.07"},
    {"min_ratio_exclusive": "2.00", "max_ratio_inclusive": None, "rate": "0.12"},
]

AVAILABILITY_SHORTFALL_TIERS = [
    {"min_ratio_exclusive": "0.00", "max_ratio_inclusive": "0.10", "rate": "0.03"},
    {"min_ratio_exclusive": "0.10", "max_ratio_inclusive": "0.50", "rate": "0.08"},
    {"min_ratio_exclusive": "0.50", "max_ratio_inclusive": "1.00", "rate": "0.15"},
    {"min_ratio_exclusive": "1.00", "max_ratio_inclusive": None, "rate": "0.25"},
]


def condition(field: str, operator: str, value):
    return {"field": field, "operator": operator, "value": value}


def all_of(*conditions: dict):
    return {"operator": "all", "conditions": list(conditions)}


def any_of(*conditions: dict):
    return {"operator": "any", "conditions": list(conditions)}


RULES = [
    {
        "code": "ELIG-SUBSCRIPTION-VALID",
        "name": "Subscription validity eligibility",
        "family": "eligibility",
        "conflict_group": "eligibility",
        "priority": 10,
        "action_type": "pass",
        "price_basis": "contracted_monthly_price",
        "stackable": True,
        "condition_tree": all_of(
            condition("subscription_active_during_outage", "eq", True),
            condition("connection_active_during_outage", "eq", True),
        ),
        "action_config": {"reason_code": "subscription_valid"},
    },
    {
        "code": "ELIG-CUSTOMER-IMPACT-CONFIRMED",
        "name": "Customer impact confirmed",
        "family": "eligibility",
        "conflict_group": "eligibility",
        "priority": 20,
        "action_type": "pass",
        "price_basis": "contracted_monthly_price",
        "stackable": True,
        "condition_tree": all_of(condition("customer_impacted", "eq", True)),
        "action_config": {"reason_code": "customer_impact_confirmed"},
    },
    {
        "code": "EXCL-PENDING-CANCELLED",
        "name": "Pending or cancelled subscription exclusion",
        "family": "exclusion",
        "conflict_group": "eligibility",
        "priority": 30,
        "action_type": "ineligible",
        "price_basis": "contracted_monthly_price",
        "stackable": False,
        "condition_tree": all_of(condition("subscription_status", "in", ["pending", "cancelled"])),
        "action_config": {"reason_code": "subscription_status_not_eligible"},
    },
    {
        "code": "EXCL-SUSPENSION-POLICY",
        "name": "Suspension policy",
        "family": "exclusion",
        "conflict_group": "eligibility",
        "priority": 35,
        "action_type": "manual_review",
        "price_basis": "contracted_monthly_price",
        "stackable": False,
        "condition_tree": all_of(
            condition("subscription_status", "eq", "suspended"),
            condition("suspension_reason", "in", ["administrative", "unknown"]),
        ),
        "action_config": {"reason_code": "suspension_requires_review"},
    },
    {
        "code": "EXCL-PLANNED-MAINTENANCE-NORMAL",
        "name": "Normal planned maintenance exclusion",
        "family": "exclusion",
        "conflict_group": "maintenance",
        "priority": 40,
        "action_type": "ineligible",
        "price_basis": "contracted_monthly_price",
        "stackable": False,
        "condition_tree": all_of(
            condition("incident_type", "eq", "planned_maintenance"),
            condition("maintenance_overrun_minutes", "lte", 0),
        ),
        "action_config": {"reason_code": "planned_maintenance_completed_in_window"},
    },
    {
        "code": "EXCL-PROTECTION-LOSS-ONLY",
        "name": "Protection loss only exclusion",
        "family": "exclusion",
        "conflict_group": "protection",
        "priority": 45,
        "action_type": "evidence_only",
        "price_basis": "contracted_monthly_price",
        "stackable": False,
        "condition_tree": all_of(condition("protection_loss_only", "eq", True)),
        "action_config": {"reason_code": "protection_loss_only"},
    },
    {
        "code": "EXCL-DUPLICATE-COMPENSATION",
        "name": "Duplicate compensation exclusion",
        "family": "exclusion",
        "conflict_group": "duplicate",
        "priority": 50,
        "action_type": "ineligible",
        "price_basis": "contracted_monthly_price",
        "stackable": False,
        "condition_tree": all_of(condition("duplicate_final_compensation_exists", "eq", True)),
        "action_config": {"reason_code": "duplicate_final_compensation"},
    },
    {
        "code": "BB-FULL-OUTAGE-TIERED",
        "name": "Broadband full outage tiered credit",
        "family": "broadband",
        "conflict_group": "broadband_outage",
        "priority": 100,
        "action_type": "tiered_percentage",
        "price_basis": "contracted_monthly_price",
        "stackable": False,
        "condition_tree": all_of(
            condition("service_type", "eq", "broadband"),
            condition("impact_class", "eq", "full_outage"),
        ),
        "action_config": {
            "tiers": BROADBAND_FULL_OUTAGE_TIERS,
            "minimum_positive_amount": "10.00",
            "incident_cap_percent": "0.40",
        },
    },
    {
        "code": "BB-PARTIAL-OUTAGE-PRORATED",
        "name": "Broadband partial outage prorated credit",
        "family": "broadband",
        "conflict_group": "broadband_outage",
        "priority": 110,
        "action_type": "prorated",
        "price_basis": "contracted_monthly_price",
        "stackable": False,
        "condition_tree": all_of(
            condition("service_type", "eq", "broadband"),
            condition("impact_class", "eq", "partial_outage"),
            condition("outage_duration_seconds", "gte", 1800),
        ),
        "action_config": {
            "minimum_duration_seconds": "1800",
            "minimum_positive_amount": "10.00",
            "incident_cap_percent": "0.25",
        },
    },
    {
        "code": "BB-DEGRADATION-QUALITY",
        "name": "Broadband quality degradation credit",
        "family": "broadband",
        "conflict_group": "broadband_degradation",
        "priority": 120,
        "action_type": "sla_matrix",
        "price_basis": "contracted_monthly_price",
        "stackable": False,
        "condition_tree": all_of(
            condition("service_type", "eq", "broadband"),
            condition("impact_class", "eq", "degradation"),
            condition("outage_duration_seconds", "gte", 1800),
        ),
        "action_config": {
            "exceedance_tiers": SLA_EXCEEDANCE_TIERS,
            "minimum_positive_amount": "10.00",
            "incident_cap_percent": "0.20",
        },
    },
    {
        "code": "ME-SHORT-FAILOVER-INTERRUPTION",
        "name": "Metro Ethernet short failover interruption",
        "family": "failover",
        "conflict_group": "metro_failover",
        "priority": 90,
        "action_type": "tiered_percentage",
        "price_basis": "contracted_monthly_price",
        "stackable": False,
        "condition_tree": all_of(
            condition("service_type", "eq", "metro_ethernet"),
            condition("sla_contractual", "eq", True),
            condition("transition_duration_seconds", "gt", 30),
            condition("transition_duration_seconds", "lte", 60),
        ),
        "action_config": {
            "tiers": [{"min_seconds": 31, "max_seconds": 61, "rate": "0.005"}],
            "duration_field": "transition_duration_seconds",
            "minimum_positive_amount": "10.00",
            "incident_cap_percent": "0.007143",
            "absolute_cap_amount": "50.00",
        },
    },
    {
        "code": "ME-AVAILABILITY-BREACH",
        "name": "Metro Ethernet availability breach",
        "family": "metro_sla",
        "conflict_group": "metro_sla",
        "priority": 130,
        "action_type": "sla_matrix",
        "price_basis": "contracted_monthly_price",
        "stackable": False,
        "condition_tree": all_of(
            condition("service_type", "eq", "metro_ethernet"),
            condition("sla_contractual", "eq", True),
            condition("impact_class", "in", ["partial_outage", "degradation"]),
        ),
        "action_config": {
            "exceedance_tiers": AVAILABILITY_SHORTFALL_TIERS,
            "minimum_positive_amount": "10.00",
            "incident_cap_percent": "0.60",
        },
    },
    {
        "code": "ME-LATENCY-BREACH",
        "name": "Metro Ethernet latency breach",
        "family": "metro_sla",
        "conflict_group": "metro_sla",
        "priority": 140,
        "action_type": "sla_matrix",
        "price_basis": "contracted_monthly_price",
        "stackable": False,
        "condition_tree": all_of(
            condition("service_type", "eq", "metro_ethernet"),
            condition("sla_contractual", "eq", True),
            condition("impact_class", "eq", "degradation"),
        ),
        "action_config": {
            "exceedance_tiers": SLA_EXCEEDANCE_TIERS,
            "minimum_positive_amount": "10.00",
            "incident_cap_percent": "0.60",
        },
    },
    {
        "code": "ME-JITTER-BREACH",
        "name": "Metro Ethernet jitter breach",
        "family": "metro_sla",
        "conflict_group": "metro_sla",
        "priority": 141,
        "action_type": "sla_matrix",
        "price_basis": "contracted_monthly_price",
        "stackable": False,
        "condition_tree": all_of(
            condition("service_type", "eq", "metro_ethernet"),
            condition("sla_contractual", "eq", True),
            condition("impact_class", "eq", "degradation"),
        ),
        "action_config": {
            "exceedance_tiers": SLA_EXCEEDANCE_TIERS,
            "minimum_positive_amount": "10.00",
            "incident_cap_percent": "0.60",
        },
    },
    {
        "code": "ME-PACKET-LOSS-BREACH",
        "name": "Metro Ethernet packet loss breach",
        "family": "metro_sla",
        "conflict_group": "metro_sla",
        "priority": 142,
        "action_type": "sla_matrix",
        "price_basis": "contracted_monthly_price",
        "stackable": False,
        "condition_tree": all_of(
            condition("service_type", "eq", "metro_ethernet"),
            condition("sla_contractual", "eq", True),
            condition("impact_class", "eq", "degradation"),
        ),
        "action_config": {
            "exceedance_tiers": SLA_EXCEEDANCE_TIERS,
            "minimum_positive_amount": "10.00",
            "incident_cap_percent": "0.60",
        },
    },
    {
        "code": "ME-FAILED-FAILOVER",
        "name": "Metro Ethernet failed failover full outage",
        "family": "failover",
        "conflict_group": "metro_failover",
        "priority": 80,
        "action_type": "tiered_percentage",
        "price_basis": "contracted_monthly_price",
        "stackable": False,
        "condition_tree": all_of(
            condition("service_type", "eq", "metro_ethernet"),
            condition("failover_result", "eq", "failed"),
            condition("impact_class", "eq", "full_outage"),
        ),
        "action_config": {
            "tiers": METRO_FAILED_FAILOVER_TIERS,
            "minimum_positive_amount": "10.00",
            "incident_cap_percent": "0.60",
        },
    },
    {
        "code": "ME-DEGRADED-FAILOVER",
        "name": "Metro Ethernet degraded failover",
        "family": "failover",
        "conflict_group": "metro_failover",
        "priority": 85,
        "action_type": "sla_matrix",
        "price_basis": "contracted_monthly_price",
        "stackable": False,
        "condition_tree": all_of(
            condition("service_type", "eq", "metro_ethernet"),
            condition("failover_result", "eq", "degraded"),
            condition("impact_class", "eq", "degradation"),
        ),
        "action_config": {
            "exceedance_tiers": SLA_EXCEEDANCE_TIERS,
            "minimum_positive_amount": "10.00",
            "incident_cap_percent": "0.60",
        },
    },
    {
        "code": "MOD-GRADED-RESTORATION",
        "name": "Graded restoration modifier",
        "family": "modifier",
        "conflict_group": "modifier",
        "priority": 300,
        "action_type": "multiplier",
        "price_basis": "contracted_monthly_price",
        "stackable": True,
        "condition_tree": all_of(
            condition("impact_class", "in", ["full_outage", "partial_outage"])
        ),
        "action_config": {"modifier_rate": "0.10", "modifier_cap_percent": "0.15"},
    },
    {
        "code": "MOD-RECURRING-INCIDENT",
        "name": "Recurring incident modifier",
        "family": "modifier",
        "conflict_group": "modifier",
        "priority": 310,
        "action_type": "multiplier",
        "price_basis": "contracted_monthly_price",
        "stackable": True,
        "condition_tree": all_of(condition("recurring_incident_count", "gte", 3)),
        "action_config": {"modifier_rate": "0.10", "max_modifier_rate": "0.25"},
    },
    {
        "code": "MOD-MAINTENANCE-OVERRUN",
        "name": "Maintenance overrun modifier",
        "family": "modifier",
        "conflict_group": "modifier",
        "priority": 320,
        "action_type": "multiplier",
        "price_basis": "contracted_monthly_price",
        "stackable": True,
        "condition_tree": all_of(condition("maintenance_overrun_minutes", "gt", 30)),
        "action_config": {"modifier_rate": "0.10"},
    },
    {
        "code": "MOD-RESTORATION-TARGET-BREACH",
        "name": "Restoration target breach modifier",
        "family": "modifier",
        "conflict_group": "modifier",
        "priority": 330,
        "action_type": "multiplier",
        "price_basis": "contracted_monthly_price",
        "stackable": True,
        "condition_tree": all_of(condition("restoration_target_breached", "eq", True)),
        "action_config": {"modifier_rate": "0.10"},
    },
    {
        "code": "SLA-PATH-DIVERSITY-BREACH",
        "name": "SLA path diversity breach",
        "family": "sla_evidence",
        "conflict_group": "sla_evidence",
        "priority": 400,
        "action_type": "manual_review",
        "price_basis": "contracted_monthly_price",
        "stackable": False,
        "condition_tree": all_of(
            condition("required_path_diversity", "eq", "fully_diverse"),
            condition(
                "observed_path_diversity", "in", ["partially_diverse", "shared_risk", "unknown"]
            ),
        ),
        "action_config": {"reason_code": "path_diversity_breach_requires_review"},
    },
    {
        "code": "SLA-BACKUP-MISSING",
        "name": "SLA backup missing",
        "family": "sla_evidence",
        "conflict_group": "sla_evidence",
        "priority": 410,
        "action_type": "manual_review",
        "price_basis": "contracted_monthly_price",
        "stackable": False,
        "condition_tree": all_of(condition("backup_required_missing", "eq", True)),
        "action_config": {"reason_code": "required_backup_missing"},
    },
    {
        "code": "MR-UNKNOWN-MISSING-EVIDENCE",
        "name": "Unknown or missing evidence manual review",
        "family": "manual_review",
        "conflict_group": "manual_review",
        "priority": 500,
        "action_type": "manual_review",
        "price_basis": "contracted_monthly_price",
        "stackable": False,
        "condition_tree": any_of(
            condition("root_cause_known", "eq", False),
            condition("price_available", "eq", False),
        ),
        "action_config": {"reason_code": "unknown_or_missing_evidence"},
    },
    {
        "code": "CAP-FLOOR-CONFLICT",
        "name": "Final cap floor and conflict policy",
        "family": "final_policy",
        "conflict_group": "final_policy",
        "priority": 900,
        "action_type": "cap_floor",
        "price_basis": "contracted_monthly_price",
        "stackable": True,
        "condition_tree": all_of(condition("price_available", "eq", True)),
        "action_config": {
            "minimum_positive_amount": "10.00",
            "broadband_incident_cap_percent": "0.40",
            "metro_incident_cap_percent": "0.60",
            "monthly_cumulative_cap_percent": "0.75",
            "high_amount_manual_review_threshold": "10000.00",
        },
    },
]

GROUND_TRUTH_CANDIDATES = [
    {
        "code": "GT-FULL-OUTAGE",
        "expected_decision": "eligible",
        "selected_rule": "BB-FULL-OUTAGE-TIERED",
        "evidence_reason": "full_outage_tier",
    },
    {
        "code": "GT-UNDER-30",
        "expected_decision": "ineligible",
        "selected_rule": "BB-FULL-OUTAGE-TIERED",
        "evidence_reason": "duration_below_threshold",
    },
    {
        "code": "GT-PARTIAL",
        "expected_decision": "eligible",
        "selected_rule": "BB-PARTIAL-OUTAGE-PRORATED",
        "evidence_reason": "partial_proration",
    },
    {
        "code": "GT-BB-DEGRADATION",
        "expected_decision": "eligible",
        "selected_rule": "BB-DEGRADATION-QUALITY",
        "evidence_reason": "quality_threshold_breach",
    },
    {
        "code": "GT-ME-LATENCY",
        "expected_decision": "eligible",
        "selected_rule": "ME-LATENCY-BREACH",
        "evidence_reason": "latency_sla_breach",
    },
    {
        "code": "GT-FAILOVER-45S",
        "expected_decision": "eligible",
        "selected_rule": "ME-SHORT-FAILOVER-INTERRUPTION",
        "evidence_reason": "45_second_failover",
    },
    {
        "code": "GT-FAILED-FAILOVER",
        "expected_decision": "eligible",
        "selected_rule": "ME-FAILED-FAILOVER",
        "evidence_reason": "failed_failover_full_outage",
    },
    {
        "code": "GT-PROTECTION-LOSS",
        "expected_decision": "evidence_only",
        "selected_rule": "EXCL-PROTECTION-LOSS-ONLY",
        "evidence_reason": "backup_only_loss",
    },
    {
        "code": "GT-MAINTENANCE-NORMAL",
        "expected_decision": "ineligible",
        "selected_rule": "EXCL-PLANNED-MAINTENANCE-NORMAL",
        "evidence_reason": "normal_planned_maintenance",
    },
    {
        "code": "GT-MAINTENANCE-OVERRUN",
        "expected_decision": "eligible",
        "selected_rule": "MOD-MAINTENANCE-OVERRUN",
        "evidence_reason": "planned_window_overrun",
    },
    {
        "code": "GT-RECURRING",
        "expected_decision": "eligible",
        "selected_rule": "MOD-RECURRING-INCIDENT",
        "evidence_reason": "recurring_incident_modifier",
    },
    {
        "code": "GT-DUPLICATE",
        "expected_decision": "ineligible",
        "selected_rule": "EXCL-DUPLICATE-COMPENSATION",
        "evidence_reason": "duplicate_prevention",
    },
    {
        "code": "GT-MONTHLY-CAP",
        "expected_decision": "eligible",
        "selected_rule": "CAP-FLOOR-CONFLICT",
        "evidence_reason": "monthly_cumulative_cap",
    },
    {
        "code": "GT-PAYMENT-SUSPENSION",
        "expected_decision": "ineligible",
        "selected_rule": "EXCL-SUSPENSION-POLICY",
        "evidence_reason": "payment_related_suspension",
    },
    {
        "code": "GT-PROVIDER-FAULT-SUSPENSION",
        "expected_decision": "eligible",
        "selected_rule": "ELIG-SUBSCRIPTION-VALID",
        "evidence_reason": "provider_fault_suspension",
    },
    {
        "code": "GT-MISSING-PRICE",
        "expected_decision": "manual_review",
        "selected_rule": "MR-UNKNOWN-MISSING-EVIDENCE",
        "evidence_reason": "missing_price",
    },
    {
        "code": "GT-UNKNOWN-ROOT",
        "expected_decision": "manual_review",
        "selected_rule": "MR-UNKNOWN-MISSING-EVIDENCE",
        "evidence_reason": "unknown_root_cause",
    },
    {
        "code": "GT-SHARED-RISK",
        "expected_decision": "manual_review",
        "selected_rule": "SLA-PATH-DIVERSITY-BREACH",
        "evidence_reason": "shared_risk_diversity",
    },
    {
        "code": "GT-BACKUP-MISSING",
        "expected_decision": "manual_review",
        "selected_rule": "SLA-BACKUP-MISSING",
        "evidence_reason": "required_backup_missing",
    },
]

CATALOG_TARGETS = {
    "rule_count": 25,
    "rule_set_code": "SYN-COMP-2026",
    "rule_set_version": 1,
    "ground_truth_candidate_count": 19,
    "synthetic_policy_only": True,
}
