# Generated by Django 5.2.16 on 2026-08-05 13:09

import django.db.models.deletion
from django.db import migrations, models

import apps.orchestration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0003_groundtruthcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_run_code', models.CharField(default=apps.orchestration.models.generate_query_run_code, max_length=48, unique=True)),
                ('request_id', models.CharField(db_index=True, default=apps.orchestration.models.generate_request_id, max_length=128)),
                ('idempotency_key', models.CharField(db_index=True, max_length=160, unique=True)),
                ('original_query', models.TextField()),
                ('structured_query', models.JSONField(blank=True, default=dict)),
                ('planned_tools', models.JSONField(blank=True, default=list)),
                ('executed_tools', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('planned', 'Planned'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('final_result', models.JSONField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=160)),
                ('prompt_version', models.CharField(blank=True, max_length=160)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_summary', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='query_runs', to='datasets.datasnapshot')),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retries', to='orchestration.queryrun')),
            ],
            options={
                'verbose_name': 'Sorgu çalıştırması',
                'verbose_name_plural': 'Sorgu çalıştırmaları',
                'db_table': 'orchestration_query_run',
                'ordering': ['-created_at', 'query_run_code'],
                'indexes': [models.Index(fields=['data_snapshot', 'status', 'created_at'], name='query_run_snapshot_status_idx'), models.Index(fields=['request_id'], name='query_run_request_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'completed'), _negated=True), models.Q(('completed_at__isnull', False), ('final_result__isnull', False)), _connector='OR'), name='query_run_completed_requires_result'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'failed'), _negated=True), models.Q(('completed_at__isnull', False), models.Q(('error_code', ''), _negated=True)), _connector='OR'), name='query_run_failed_requires_error'), models.CheckConstraint(condition=models.Q(('status__in', frozenset(['completed', 'failed'])), ('completed_at__isnull', True), _connector='OR'), name='query_run_nonterminal_not_completed')],
            },
        ),
    ]
