# Generated by Django 5.2.16 on 2026-08-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryrun',
            name='embedding_prompt_version',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='queryrun',
            name='requested_embedding_provider',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='queryrun',
            name='requested_llm_provider',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='queryrun',
            name='resolved_embedding_model',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='queryrun',
            name='resolved_embedding_provider',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='queryrun',
            name='resolved_llm_model',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='queryrun',
            name='resolved_llm_provider',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='queryrun',
            name='structured_query_parser',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='queryrun',
            name='structured_query_parser_version',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
