# Generated by Django 5.2.16 on 2026-08-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0003_add_query_run_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryrun',
            name='response_audit',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
