# Generated by Django 5.2.16 on 2026-08-14 15:09

import apps.orchestration.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0003_groundtruthcase'),
        ('orchestration', '0004_queryrun_response_audit'),
        ('rag', '0002_document_chunk_embedding'),
        ('rules', '0003_rule_conflict_group_rule_family_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_code', models.CharField(default=apps.orchestration.models.generate_evidence_record_code, max_length=48)),
                ('snapshot_context', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_records', to='datasets.datasnapshot')),
                ('query_run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_record', to='orchestration.queryrun')),
            ],
            options={
                'db_table': 'orchestration_evidence_record',
                'ordering': ['-created_at', 'evidence_code'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceRAGReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_path', models.JSONField(blank=True, default=list)),
                ('retrieval_score', models.FloatField(blank=True, null=True)),
                ('document_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_rag_references', to='rag.documentchunk')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_rag_references', to='rag.sourcedocument')),
                ('evidence_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='orchestration.evidencerecord')),
            ],
            options={
                'db_table': 'orchestration_evidence_rag_reference',
                'ordering': ['evidence_record', 'source_document', 'document_chunk'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('calculation_code', models.CharField(max_length=120)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('outputs', models.JSONField(blank=True, default=dict)),
                ('evidence_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='orchestration.evidencerecord')),
            ],
            options={
                'db_table': 'orchestration_evidence_calculation',
                'ordering': ['evidence_record', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceRuleReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_role', models.CharField(default='selected', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('evidence_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='orchestration.evidencerecord')),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_rule_references', to='rules.ruleversion')),
            ],
            options={
                'db_table': 'orchestration_evidence_rule_reference',
                'ordering': ['evidence_record', 'rule_version'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('server_name', models.CharField(max_length=80)),
                ('tool_name', models.CharField(max_length=160)),
                ('status', models.CharField(max_length=32)),
                ('request_summary', models.JSONField(blank=True, default=dict)),
                ('response_summary', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='orchestration.evidencerecord')),
            ],
            options={
                'db_table': 'orchestration_evidence_tool_call',
                'ordering': ['evidence_record', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='evidencerecord',
            index=models.Index(fields=['data_snapshot', 'finalized', 'created_at'], name='evidence_record_snap_final_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidencerecord',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'evidence_code'), name='evidence_record_snapshot_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='evidencerecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finalized', False), ('finalized_at__isnull', True)), models.Q(('finalized', True), ('finalized_at__isnull', False)), _connector='OR'), name='evidence_record_finalization_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='evidenceragreference',
            constraint=models.UniqueConstraint(fields=('evidence_record', 'source_document', 'document_chunk'), name='evidence_rag_reference_uniq'),
        ),
        migrations.AddConstraint(
            model_name='evidencecalculation',
            constraint=models.UniqueConstraint(fields=('evidence_record', 'sequence'), name='evidence_calculation_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='evidencerulereference',
            constraint=models.UniqueConstraint(fields=('evidence_record', 'rule_version', 'reference_role'), name='evidence_rule_reference_uniq'),
        ),
        migrations.AddConstraint(
            model_name='evidencetoolcall',
            constraint=models.UniqueConstraint(fields=('evidence_record', 'sequence'), name='evidence_tool_call_sequence_uniq'),
        ),
    ]
