# Generated by Django 5.2.16 on 2026-07-27 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('device_type', models.CharField(choices=[('bng', 'BNG'), ('olt', 'OLT'), ('dslam', 'DSLAM'), ('access_node', 'Access node')], max_length=24)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('decommissioned', 'Decommissioned')], default='active', max_length=24)),
                ('vendor', models.CharField(blank=True, max_length=80)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('software_version', models.CharField(blank=True, max_length=80)),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='network_devices', to='geography.city')),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_devices', to='datasets.datasnapshot')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_devices', to='geography.district')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_devices', to='geography.neighborhood')),
            ],
            options={
                'db_table': 'network_device',
                'ordering': ['data_snapshot', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AccessSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment_code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('technology', models.CharField(choices=[('fiber', 'Fiber'), ('gpon', 'GPON'), ('vdsl', 'VDSL'), ('adsl', 'ADSL'), ('metro_ethernet', 'Metro Ethernet')], max_length=32)),
                ('estimated_customer_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_segments', to='geography.city')),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_segments', to='datasets.datasnapshot')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_segments', to='geography.district')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_segments', to='geography.neighborhood')),
                ('serving_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_segments', to='network.networkdevice')),
            ],
            options={
                'db_table': 'network_access_segment',
                'ordering': ['data_snapshot', 'segment_code'],
            },
        ),
        migrations.CreateModel(
            name='NetworkLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link_code', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('degraded', 'Degraded'), ('down', 'Down'), ('maintenance', 'Maintenance')], default='active', max_length=24)),
                ('capacity_mbps', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_links', to='datasets.datasnapshot')),
                ('source_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='network.networkdevice')),
                ('target_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='network.networkdevice')),
            ],
            options={
                'db_table': 'network_link',
                'ordering': ['data_snapshot', 'link_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='networkdevice',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'code'), name='unique_network_device_code_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='accesssegment',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'segment_code'), name='unique_access_segment_code_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='networklink',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'link_code'), name='unique_network_link_code_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='networklink',
            constraint=models.CheckConstraint(condition=models.Q(('source_device', models.F('target_device')), _negated=True), name='network_link_source_target_differ'),
        ),
    ]
