# Generated by Django 5.2.16 on 2026-07-27 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0001_initial'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='inventory_status',
            field=models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('decommissioned', 'Decommissioned')], default='active', max_length=24),
        ),
        migrations.CreateModel(
            name='NetworkPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('port_code', models.CharField(max_length=80)),
                ('port_type', models.CharField(choices=[('uplink', 'Uplink'), ('downlink', 'Downlink'), ('access', 'Access'), ('customer', 'Customer'), ('management', 'Management')], default='access', max_length=24)),
                ('inventory_status', models.CharField(choices=[('active', 'Active'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance'), ('decommissioned', 'Decommissioned')], default='active', max_length=24)),
                ('capacity_mbps', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_ports', to='datasets.datasnapshot')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='network.networkdevice')),
            ],
            options={
                'db_table': 'network_port',
                'ordering': ['data_snapshot', 'device__code', 'port_code'],
            },
        ),
        migrations.CreateModel(
            name='LineConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_code', models.CharField(max_length=80)),
                ('technology', models.CharField(choices=[('fiber', 'Fiber'), ('gpon', 'GPON'), ('vdsl', 'VDSL'), ('adsl', 'ADSL'), ('metro_ethernet', 'Metro Ethernet')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('planned', 'Planned'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=24)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('access_segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_connections', to='network.accesssegment')),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_connections', to='datasets.datasnapshot')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_connections', to='network.networkport')),
            ],
            options={
                'db_table': 'network_line_connection',
                'ordering': ['data_snapshot', 'line_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='networkport',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'device', 'port_code'), name='unique_network_port_code_per_device_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='lineconnection',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'line_code'), name='unique_line_connection_code_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='lineconnection',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='line_connection_valid_range'),
        ),
    ]
