# Generated by Django 5.2.16 on 2026-07-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_networkdevice_inventory_status_networkport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkdevice',
            name='status',
        ),
    ]
