# Generated by Django 5.2.16 on 2026-07-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_networkdevice_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesssegment',
            options={'ordering': ['data_snapshot', 'segment_code'], 'verbose_name': 'Erişim segmenti', 'verbose_name_plural': 'Erişim segmentleri'},
        ),
        migrations.AlterModelOptions(
            name='lineconnection',
            options={'ordering': ['data_snapshot', 'line_code'], 'verbose_name': 'Hat bağlantısı', 'verbose_name_plural': 'Hat bağlantıları'},
        ),
        migrations.AlterModelOptions(
            name='networkdevice',
            options={'ordering': ['data_snapshot', 'code'], 'verbose_name': 'Ağ cihazı', 'verbose_name_plural': 'Ağ cihazları'},
        ),
        migrations.AlterModelOptions(
            name='networklink',
            options={'ordering': ['data_snapshot', 'link_code'], 'verbose_name': 'Ağ bağlantısı', 'verbose_name_plural': 'Ağ bağlantıları'},
        ),
        migrations.AlterModelOptions(
            name='networkport',
            options={'ordering': ['data_snapshot', 'device__code', 'port_code'], 'verbose_name': 'Ağ portu', 'verbose_name_plural': 'Ağ portları'},
        ),
    ]
