# Generated by Django 5.2.16 on 2026-07-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_accesssegment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesssegment',
            name='technology',
            field=models.CharField(choices=[('fiber', 'Fiber'), ('gpon', 'GPON'), ('vdsl', 'VDSL'), ('adsl', 'ADSL')], max_length=32),
        ),
        migrations.AlterField(
            model_name='lineconnection',
            name='technology',
            field=models.CharField(choices=[('fiber', 'Fiber'), ('gpon', 'GPON'), ('vdsl', 'VDSL'), ('adsl', 'ADSL')], max_length=32),
        ),
    ]
