# Generated by Django 5.2.16 on 2026-07-29 08:58

from django.db import migrations, models


def backfill_access_node_roles(apps, schema_editor):
    NetworkDevice = apps.get_model("network", "NetworkDevice")
    NetworkDevice.objects.filter(device_type="access_node").update(
        access_role="standard_access"
    )
    NetworkDevice.objects.exclude(device_type="access_node").update(access_role=None)


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0003_groundtruthcase'),
        ('geography', '0002_alter_city_options_alter_district_options_and_more'),
        ('network', '0005_alter_accesssegment_technology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='access_role',
            field=models.CharField(blank=True, choices=[('standard_access', 'Standard access'), ('corporate_fiber_aggregation', 'Corporate fiber aggregation')], max_length=40, null=True),
        ),
        migrations.RunPython(
            backfill_access_node_roles,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='networkdevice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('access_role__isnull', False), ('device_type', 'access_node')), models.Q(models.Q(('device_type', 'access_node'), _negated=True), ('access_role__isnull', True)), _connector='OR'), name='network_device_access_role_matches_type'),
        ),
    ]
