# Generated by Django 5.2.16 on 2026-07-29 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0003_groundtruthcase'),
        ('network', '0006_networkdevice_access_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='device_type',
            field=models.CharField(choices=[('bng', 'BNG'), ('metro_aggregation', 'Metro aggregation'), ('olt', 'OLT'), ('dslam', 'DSLAM'), ('access_node', 'Access node')], max_length=24),
        ),
        migrations.CreateModel(
            name='FailureDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('domain_type', models.CharField(choices=[('site', 'Site'), ('power_zone', 'Power zone'), ('fiber_route', 'Fiber route')], max_length=24)),
                ('description', models.TextField(blank=True)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_domains', to='datasets.datasnapshot')),
            ],
            options={
                'verbose_name': 'Arıza alanı',
                'verbose_name_plural': 'Arıza alanları',
                'db_table': 'network_failure_domain',
                'ordering': ['data_snapshot', 'domain_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DeviceFailureDomainMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_failure_domain_memberships', to='datasets.datasnapshot')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_domain_memberships', to='network.networkdevice')),
                ('failure_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_memberships', to='network.failuredomain')),
            ],
            options={
                'verbose_name': 'Cihaz arıza alanı üyeliği',
                'verbose_name_plural': 'Cihaz arıza alanı üyelikleri',
                'db_table': 'network_device_failure_domain_membership',
                'ordering': ['data_snapshot', 'device__code', 'failure_domain__code'],
            },
        ),
        migrations.CreateModel(
            name='LineConnectionFailureDomainMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_connection_failure_domain_memberships', to='datasets.datasnapshot')),
                ('failure_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_connection_memberships', to='network.failuredomain')),
                ('line_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_domain_memberships', to='network.lineconnection')),
            ],
            options={
                'verbose_name': 'Hat arıza alanı üyeliği',
                'verbose_name_plural': 'Hat arıza alanı üyelikleri',
                'db_table': 'network_line_connection_failure_domain_membership',
                'ordering': ['data_snapshot', 'line_connection__line_code', 'failure_domain__code'],
            },
        ),
        migrations.CreateModel(
            name='NetworkLinkFailureDomainMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_link_failure_domain_memberships', to='datasets.datasnapshot')),
                ('failure_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_link_memberships', to='network.failuredomain')),
                ('network_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_domain_memberships', to='network.networklink')),
            ],
            options={
                'verbose_name': 'Ağ bağlantısı arıza alanı üyeliği',
                'verbose_name_plural': 'Ağ bağlantısı arıza alanı üyelikleri',
                'db_table': 'network_link_failure_domain_membership',
                'ordering': ['data_snapshot', 'network_link__link_code', 'failure_domain__code'],
            },
        ),
        migrations.AddConstraint(
            model_name='failuredomain',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'code'), name='unique_failure_domain_code_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='devicefailuredomainmembership',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'device', 'failure_domain'), name='unique_device_failure_domain_membership'),
        ),
        migrations.AddConstraint(
            model_name='lineconnectionfailuredomainmembership',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'line_connection', 'failure_domain'), name='unique_line_connection_failure_domain_membership'),
        ),
        migrations.AddConstraint(
            model_name='networklinkfailuredomainmembership',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'network_link', 'failure_domain'), name='unique_network_link_failure_domain_membership'),
        ),
    ]
