# Generated by Django 5.2.16 on 2026-07-27 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('geography', '0001_initial'),
        ('network', '0003_remove_networkdevice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_number', models.CharField(max_length=80)),
                ('display_name', models.CharField(max_length=160)),
                ('segment', models.CharField(choices=[('individual', 'Individual'), ('sme', 'SME'), ('enterprise', 'Enterprise'), ('public', 'Public')], default='individual', max_length=24)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('churned', 'Churned')], default='active', max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='geography.city')),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='datasets.datasnapshot')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='geography.district')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='geography.neighborhood')),
            ],
            options={
                'db_table': 'customers_customer',
                'ordering': ['data_snapshot', 'customer_number'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('technology', models.CharField(choices=[('fiber', 'Fiber'), ('gpon', 'GPON'), ('vdsl', 'VDSL'), ('adsl', 'ADSL'), ('metro_ethernet', 'Metro Ethernet')], max_length=32)),
                ('download_mbps', models.PositiveIntegerField(default=0)),
                ('upload_mbps', models.PositiveIntegerField(default=0)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commitment_months', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_packages', to='datasets.datasnapshot')),
            ],
            options={
                'db_table': 'customers_service_package',
                'ordering': ['data_snapshot', 'package_code'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_number', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='active', max_length=24)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='customers.customer')),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='datasets.datasnapshot')),
                ('service_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='customers.servicepackage')),
            ],
            options={
                'db_table': 'customers_subscription',
                'ordering': ['data_snapshot', 'subscription_number'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('due', 'Due'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='due', max_length=24)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='datasets.datasnapshot')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='customers.subscription')),
            ],
            options={
                'db_table': 'customers_payment_record',
                'ordering': ['data_snapshot', 'subscription__subscription_number', 'period'],
            },
        ),
        migrations.CreateModel(
            name='CompensationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='proposed', max_length=24)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_history', to='datasets.datasnapshot')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_history', to='customers.subscription')),
            ],
            options={
                'verbose_name_plural': 'compensation history',
                'db_table': 'customers_compensation_history',
                'ordering': ['data_snapshot', 'subscription__subscription_number', 'reference_code'],
            },
        ),
        migrations.CreateModel(
            name='CampaignEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=24)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_enrollments', to='datasets.datasnapshot')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_enrollments', to='customers.subscription')),
            ],
            options={
                'db_table': 'customers_campaign_enrollment',
                'ordering': ['data_snapshot', 'subscription__subscription_number', 'campaign_code'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('port_identifier', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_connections', to='datasets.datasnapshot')),
                ('line_connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_connections', to='network.lineconnection')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='customers.subscription')),
            ],
            options={
                'db_table': 'customers_subscription_connection',
                'ordering': ['data_snapshot', 'subscription__subscription_number', 'valid_from'],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'customer_number'), name='unique_customer_number_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='servicepackage',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'package_code'), name='unique_service_package_code_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'subscription_number'), name='unique_subscription_number_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='subscription_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='paymentrecord',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'subscription', 'period'), name='unique_payment_record_period_per_subscription'),
        ),
        migrations.AddConstraint(
            model_name='compensationhistory',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'reference_code'), name='unique_compensation_reference_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionconnection',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='subscription_connection_valid_range'),
        ),
    ]
