# Generated by Django 5.2.16 on 2026-07-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignenrollment',
            options={'ordering': ['data_snapshot', 'subscription__subscription_number', 'campaign_code'], 'verbose_name': 'Kampanya katılımı', 'verbose_name_plural': 'Kampanya katılımları'},
        ),
        migrations.AlterModelOptions(
            name='compensationhistory',
            options={'ordering': ['data_snapshot', 'subscription__subscription_number', 'reference_code'], 'verbose_name': 'Telafi geçmişi', 'verbose_name_plural': 'Telafi geçmişi'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['data_snapshot', 'customer_number'], 'verbose_name': 'Müşteri', 'verbose_name_plural': 'Müşteriler'},
        ),
        migrations.AlterModelOptions(
            name='paymentrecord',
            options={'ordering': ['data_snapshot', 'subscription__subscription_number', 'period'], 'verbose_name': 'Ödeme kaydı', 'verbose_name_plural': 'Ödeme kayıtları'},
        ),
        migrations.AlterModelOptions(
            name='servicepackage',
            options={'ordering': ['data_snapshot', 'package_code'], 'verbose_name': 'Servis paketi', 'verbose_name_plural': 'Servis paketleri'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['data_snapshot', 'subscription_number'], 'verbose_name': 'Abonelik', 'verbose_name_plural': 'Abonelikler'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionconnection',
            options={'ordering': ['data_snapshot', 'subscription__subscription_number', 'valid_from'], 'verbose_name': 'Abonelik bağlantısı', 'verbose_name_plural': 'Abonelik bağlantıları'},
        ),
    ]
