# Generated by Django 5.2.16 on 2026-07-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_campaignenrollment_options_and_more'),
        ('datasets', '0002_alter_datasetversion_options_and_more'),
        ('network', '0004_alter_accesssegment_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscriptionconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('valid_to__isnull', True)), fields=('subscription',), name='unique_open_active_connection_per_subscription'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('valid_to__isnull', True)), fields=('line_connection',), name='unique_open_active_connection_per_line'),
        ),
    ]
