# Generated by Django 5.2.16 on 2026-07-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_subscriptionconnection_unique_open_active_connection_per_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='priority_level',
            field=models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP')], default='standard', max_length=24),
        ),
    ]
