# Generated by Django 5.2.16 on 2026-07-29 08:38

from django.db import migrations, models


def backfill_service_package_service_type(apps, schema_editor):
    ServicePackage = apps.get_model("customers", "ServicePackage")
    ServicePackage.objects.all().update(service_type="broadband")


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_priority_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='service_type',
            field=models.CharField(choices=[('broadband', 'Broadband'), ('metro_ethernet', 'Metro Ethernet')], default='broadband', max_length=32),
        ),
        migrations.RunPython(
            backfill_service_package_service_type,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='technology',
            field=models.CharField(choices=[('fiber', 'Fiber'), ('gpon', 'GPON'), ('vdsl', 'VDSL'), ('adsl', 'ADSL')], max_length=32),
        ),
    ]
