# Generated by Django 5.2.16 on 2026-07-29 08:58

from django.db import migrations, models


def backfill_subscription_connection_role(apps, schema_editor):
    SubscriptionConnection = apps.get_model("customers", "SubscriptionConnection")
    SubscriptionConnection.objects.all().update(connection_role="primary")


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_servicepackage_service_type_and_more'),
        ('datasets', '0003_groundtruthcase'),
        ('network', '0005_alter_accesssegment_technology_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptionconnection',
            name='unique_open_active_connection_per_subscription',
        ),
        migrations.AddField(
            model_name='subscriptionconnection',
            name='connection_role',
            field=models.CharField(choices=[('primary', 'Primary'), ('backup', 'Backup')], default='primary', max_length=16),
        ),
        migrations.RunPython(
            backfill_subscription_connection_role,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='subscriptionconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('valid_to__isnull', True)), fields=('subscription', 'connection_role'), name='unique_open_active_connection_per_subscription_role'),
        ),
    ]
