# Generated by Django 5.2.16 on 2026-07-29 11:29

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def backfill_commercial_defaults(apps, schema_editor):
    ServicePackage = apps.get_model("customers", "ServicePackage")
    ServicePackageAllowedSegment = apps.get_model("customers", "ServicePackageAllowedSegment")
    ServicePackagePriceVersion = apps.get_model("customers", "ServicePackagePriceVersion")
    SLAProfile = apps.get_model("customers", "SLAProfile")
    Subscription = apps.get_model("customers", "Subscription")
    PaymentRecord = apps.get_model("customers", "PaymentRecord")
    CompensationHistory = apps.get_model("customers", "CompensationHistory")

    now = timezone.now()
    segment_values = ["individual", "sme", "enterprise", "public"]
    snapshot_ids = set(ServicePackage.objects.values_list("data_snapshot_id", flat=True))
    snapshot_ids.update(Subscription.objects.values_list("data_snapshot_id", flat=True))

    for snapshot_id in sorted(snapshot_ids):
        sla_profile, _created = SLAProfile.objects.get_or_create(
            data_snapshot_id=snapshot_id,
            code="best_effort",
            defaults={
                "name": "Best Effort Synthetic SLA",
                "availability_target_percent": Decimal("99.00"),
                "support_window": "8x5",
                "response_target_minutes": 1440,
                "restoration_target_minutes": 4320,
                "latency_threshold_ms": 80,
                "jitter_threshold_ms": 30,
                "packet_loss_threshold_percent": Decimal("2.00"),
                "backup_requirement": "none",
                "required_path_diversity": "not_required",
                "monitoring_level": "standard",
                "is_contractual": False,
                "active": True,
                "metadata": {
                    "synthetic": True,
                    "migration_backfill": True,
                    "reason": "039.5.4 default SLA for existing packages and subscriptions",
                },
            },
        )
        for package in ServicePackage.objects.filter(data_snapshot_id=snapshot_id).order_by("id"):
            updates = {}
            if package.default_sla_profile_id is None:
                updates["default_sla_profile_id"] = sla_profile.id
            if package.valid_from is None:
                updates["valid_from"] = now
            if updates:
                ServicePackage.objects.filter(pk=package.pk).update(**updates)
                for field_name, value in updates.items():
                    setattr(package, field_name, value)
            for segment in segment_values:
                ServicePackageAllowedSegment.objects.get_or_create(
                    data_snapshot_id=snapshot_id,
                    service_package_id=package.id,
                    segment=segment,
                )
            ServicePackagePriceVersion.objects.get_or_create(
                service_package_id=package.id,
                version_number=1,
                defaults={
                    "data_snapshot_id": snapshot_id,
                    "amount": package.monthly_price,
                    "currency": "TRY",
                    "valid_from": package.valid_from or now,
                    "active": True,
                    "metadata": {
                        "synthetic": True,
                        "migration_backfill": True,
                        "reference_datetime_price": True,
                    },
                },
            )
        Subscription.objects.filter(
            data_snapshot_id=snapshot_id,
            sla_profile_id__isnull=True,
        ).update(sla_profile_id=sla_profile.id)

    for payment in PaymentRecord.objects.all().order_by("id"):
        old_status = payment.status
        amount = payment.amount or Decimal("0.00")
        if old_status == "paid":
            new_status = "paid_on_time"
            paid_amount = amount
            outstanding_amount = Decimal("0.00")
        elif old_status == "cancelled":
            new_status = "voided"
            amount = Decimal("0.00")
            paid_amount = Decimal("0.00")
            outstanding_amount = Decimal("0.00")
        elif old_status == "due":
            new_status = "overdue"
            paid_amount = Decimal("0.00")
            outstanding_amount = amount
        else:
            new_status = old_status
            paid_amount = Decimal("0.00")
            outstanding_amount = amount
        PaymentRecord.objects.filter(pk=payment.pk).update(
            status=new_status,
            recurring_amount=amount,
            one_time_amount=Decimal("0.00"),
            discount_amount=Decimal("0.00"),
            billed_amount=amount,
            paid_amount=paid_amount,
            outstanding_amount=outstanding_amount,
            currency="TRY",
        )

    for history in CompensationHistory.objects.select_related("subscription").order_by("id"):
        old_status = history.status
        if old_status == "approved":
            decision_status = "approved"
            settlement_status = "pending"
        elif old_status == "paid":
            decision_status = "approved"
            settlement_status = "paid"
        elif old_status == "rejected":
            decision_status = "rejected"
            settlement_status = "not_applicable"
        else:
            decision_status = "manual_review"
            settlement_status = "not_applicable"
        customer_id = history.subscription.customer_id if history.subscription_id else None
        CompensationHistory.objects.filter(pk=history.pk).update(
            customer_id=customer_id,
            decision_status=decision_status,
            settlement_status=settlement_status,
            currency="TRY",
            settled_at=history.decided_at if settlement_status == "paid" else None,
        )


class Migration(migrations.Migration):
    dependencies = [
        (
            "customers",
            "0006_remove_subscriptionconnection_unique_open_active_connection_per_subscription_and_more",
        ),
        ("datasets", "0003_groundtruthcase"),
        ("operations", "0003_alarmtypeallowedsourcekind_and_more"),
        ("rules", "0002_alter_rule_options_alter_rulechangeset_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=160)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Percent"),
                            ("fixed_amount", "Fixed amount"),
                            ("free_month", "Free month"),
                        ],
                        max_length=24,
                    ),
                ),
                ("discount_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration_months", models.PositiveIntegerField(default=0)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("stackable", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=24,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Kampanya",
                "verbose_name_plural": "Kampanyalar",
                "db_table": "customers_campaign",
                "ordering": ["data_snapshot", "code"],
            },
        ),
        migrations.CreateModel(
            name="CampaignAllowedSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("sme", "SME"),
                            ("enterprise", "Enterprise"),
                            ("public", "Public"),
                        ],
                        max_length=24,
                    ),
                ),
            ],
            options={
                "db_table": "customers_campaign_allowed_segment",
                "ordering": ["data_snapshot", "campaign__code", "segment"],
            },
        ),
        migrations.CreateModel(
            name="CampaignAllowedServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[("broadband", "Broadband"), ("metro_ethernet", "Metro Ethernet")],
                        max_length=32,
                    ),
                ),
            ],
            options={
                "db_table": "customers_campaign_allowed_service_type",
                "ordering": ["data_snapshot", "campaign__code", "service_type"],
            },
        ),
        migrations.CreateModel(
            name="CampaignAllowedTechnology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "technology",
                    models.CharField(
                        choices=[
                            ("fiber", "Fiber"),
                            ("gpon", "GPON"),
                            ("vdsl", "VDSL"),
                            ("adsl", "ADSL"),
                        ],
                        max_length=32,
                    ),
                ),
            ],
            options={
                "db_table": "customers_campaign_allowed_technology",
                "ordering": ["data_snapshot", "campaign__code", "technology"],
            },
        ),
        migrations.CreateModel(
            name="ServicePackageAllowedSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("sme", "SME"),
                            ("enterprise", "Enterprise"),
                            ("public", "Public"),
                        ],
                        max_length=24,
                    ),
                ),
            ],
            options={
                "verbose_name": "Servis paketi uygun segmenti",
                "verbose_name_plural": "Servis paketi uygun segmentleri",
                "db_table": "customers_service_package_allowed_segment",
                "ordering": ["data_snapshot", "service_package__package_code", "segment"],
            },
        ),
        migrations.CreateModel(
            name="ServicePackagePriceVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="TRY", max_length=3)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("version_number", models.PositiveIntegerField()),
                ("active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Servis paketi fiyat versiyonu",
                "verbose_name_plural": "Servis paketi fiyat versiyonları",
                "db_table": "customers_service_package_price_version",
                "ordering": ["data_snapshot", "service_package__package_code", "version_number"],
            },
        ),
        migrations.CreateModel(
            name="SLAProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=160)),
                (
                    "availability_target_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("support_window", models.CharField(max_length=40)),
                ("response_target_minutes", models.PositiveIntegerField()),
                ("restoration_target_minutes", models.PositiveIntegerField()),
                ("latency_threshold_ms", models.PositiveIntegerField()),
                ("jitter_threshold_ms", models.PositiveIntegerField()),
                (
                    "packet_loss_threshold_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "backup_requirement",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("optional", "Optional"),
                            ("recommended", "Recommended"),
                            ("required", "Required"),
                        ],
                        default="none",
                        max_length=24,
                    ),
                ),
                (
                    "required_path_diversity",
                    models.CharField(
                        choices=[
                            ("not_required", "Not required"),
                            ("partially_diverse", "Partially diverse"),
                            ("fully_diverse", "Fully diverse"),
                        ],
                        default="not_required",
                        max_length=32,
                    ),
                ),
                (
                    "monitoring_level",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("enhanced", "Enhanced"),
                            ("proactive", "Proactive"),
                            ("continuous", "Continuous"),
                        ],
                        default="standard",
                        max_length=24,
                    ),
                ),
                ("is_contractual", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "SLA profili",
                "verbose_name_plural": "SLA profilleri",
                "db_table": "customers_sla_profile",
                "ordering": ["data_snapshot", "code"],
            },
        ),
        migrations.AddField(
            model_name="compensationhistory",
            name="currency",
            field=models.CharField(default="TRY", max_length=3),
        ),
        migrations.AddField(
            model_name="compensationhistory",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compensation_history",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="compensationhistory",
            name="decision_status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("manual_review", "Manual review"),
                ],
                default="manual_review",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="compensationhistory",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="compensationhistory",
            name="incident",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compensation_history",
                to="operations.incident",
            ),
        ),
        migrations.AddField(
            model_name="compensationhistory",
            name="outage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compensation_history",
                to="operations.outage",
            ),
        ),
        migrations.AddField(
            model_name="compensationhistory",
            name="rule_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compensation_history",
                to="rules.ruleversion",
            ),
        ),
        migrations.AddField(
            model_name="compensationhistory",
            name="settled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="compensationhistory",
            name="settlement_status",
            field=models.CharField(
                choices=[
                    ("not_applicable", "Not applicable"),
                    ("pending", "Pending"),
                    ("credited", "Credited"),
                    ("paid", "Paid"),
                ],
                default="not_applicable",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="billed_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="billing_period_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="billing_period_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="currency",
            field=models.CharField(default="TRY", max_length=3),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="one_time_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="outstanding_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="recurring_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="servicepackage",
            name="backup_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servicepackage",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive"), ("retired", "Retired")],
                default="active",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="servicepackage",
            name="symmetric",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servicepackage",
            name="valid_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicepackage",
            name="valid_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaignenrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("paid_on_time", "Paid on time"),
                    ("paid_late", "Paid late"),
                    ("overdue", "Overdue"),
                    ("partial", "Partial"),
                    ("failed", "Failed"),
                    ("reversed", "Reversed"),
                    ("voided", "Voided"),
                ],
                default="overdue",
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="compensationhistory",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("incident__isnull", False),
                    ("rule_version__isnull", False),
                    ("decision_status__in", ["approved", "rejected"]),
                ),
                fields=("subscription", "incident", "rule_version"),
                name="unique_final_compensation_per_sub_incident_rule",
            ),
        ),
        migrations.AddConstraint(
            model_name="compensationhistory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("data_snapshot", "idempotency_key"),
                name="unique_compensation_history_idempotency_key",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="data_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="datasets.datasnapshot",
            ),
        ),
        migrations.AddField(
            model_name="campaignenrollment",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollments",
                to="customers.campaign",
            ),
        ),
        migrations.AddField(
            model_name="campaignallowedsegment",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="segments",
                to="customers.campaign",
            ),
        ),
        migrations.AddField(
            model_name="campaignallowedsegment",
            name="data_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_allowed_segments",
                to="datasets.datasnapshot",
            ),
        ),
        migrations.AddField(
            model_name="campaignallowedservicetype",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_types",
                to="customers.campaign",
            ),
        ),
        migrations.AddField(
            model_name="campaignallowedservicetype",
            name="data_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_allowed_service_types",
                to="datasets.datasnapshot",
            ),
        ),
        migrations.AddField(
            model_name="campaignallowedtechnology",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technologies",
                to="customers.campaign",
            ),
        ),
        migrations.AddField(
            model_name="campaignallowedtechnology",
            name="data_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_allowed_technologies",
                to="datasets.datasnapshot",
            ),
        ),
        migrations.AddField(
            model_name="servicepackageallowedsegment",
            name="data_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_package_allowed_segments",
                to="datasets.datasnapshot",
            ),
        ),
        migrations.AddField(
            model_name="servicepackageallowedsegment",
            name="service_package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allowed_segments",
                to="customers.servicepackage",
            ),
        ),
        migrations.AddField(
            model_name="servicepackagepriceversion",
            name="data_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_package_price_versions",
                to="datasets.datasnapshot",
            ),
        ),
        migrations.AddField(
            model_name="servicepackagepriceversion",
            name="service_package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_versions",
                to="customers.servicepackage",
            ),
        ),
        migrations.AddField(
            model_name="slaprofile",
            name="data_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sla_profiles",
                to="datasets.datasnapshot",
            ),
        ),
        migrations.AddField(
            model_name="servicepackage",
            name="default_sla_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="default_service_packages",
                to="customers.slaprofile",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="sla_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="customers.slaprofile",
            ),
        ),
        migrations.RunPython(
            backfill_commercial_defaults,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="compensationhistory",
            name="status",
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.UniqueConstraint(
                fields=("data_snapshot", "code"), name="unique_campaign_code_per_snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_to__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="campaign_valid_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_value__gte", Decimal("0.00"))),
                name="campaign_discount_value_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignallowedsegment",
            constraint=models.UniqueConstraint(
                fields=("data_snapshot", "campaign", "segment"),
                name="unique_campaign_allowed_segment",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignallowedservicetype",
            constraint=models.UniqueConstraint(
                fields=("data_snapshot", "campaign", "service_type"),
                name="unique_campaign_allowed_service_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignallowedtechnology",
            constraint=models.UniqueConstraint(
                fields=("data_snapshot", "campaign", "technology"),
                name="unique_campaign_allowed_technology",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicepackageallowedsegment",
            constraint=models.UniqueConstraint(
                fields=("data_snapshot", "service_package", "segment"),
                name="unique_service_package_allowed_segment",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicepackagepriceversion",
            constraint=models.UniqueConstraint(
                fields=("service_package", "version_number"),
                name="unique_service_package_price_version_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicepackagepriceversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_to__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="service_package_price_version_valid_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicepackagepriceversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", Decimal("0.00"))),
                name="service_package_price_version_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="slaprofile",
            constraint=models.UniqueConstraint(
                fields=("data_snapshot", "code"), name="unique_sla_profile_code_per_snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="slaprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("availability_target_percent__gte", Decimal("0.00")),
                    ("availability_target_percent__lte", Decimal("100.00")),
                ),
                name="sla_availability_target_percent_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="slaprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("packet_loss_threshold_percent__gte", Decimal("0.00")),
                    ("packet_loss_threshold_percent__lte", Decimal("100.00")),
                ),
                name="sla_packet_loss_threshold_percent_range",
            ),
        ),
    ]
