# Generated by Django 5.2.16 on 2026-07-29 12:27

from django.db import migrations, models


def backfill_suspension_reason(apps, schema_editor):
    subscription = apps.get_model("customers", "Subscription")
    subscription.objects.filter(status="suspended", suspension_reason="").update(
        suspension_reason="unknown"
    )
    subscription.objects.exclude(status="suspended").update(suspension_reason="")


def reverse_backfill_suspension_reason(apps, schema_editor):
    subscription = apps.get_model("customers", "Subscription")
    subscription.objects.update(suspension_reason="")


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_campaign_campaignallowedsegment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='suspension_reason',
            field=models.CharField(blank=True, choices=[('customer_request', 'Customer request'), ('payment_related', 'Payment related'), ('administrative', 'Administrative'), ('provider_fault', 'Provider fault'), ('unknown', 'Unknown')], max_length=32),
        ),
        migrations.RunPython(backfill_suspension_reason, reverse_backfill_suspension_reason),
    ]
