# Generated by Django 5.2.16 on 2026-07-29 12:31

from django.db import migrations, models


def backfill_compensation_conflict_group(apps, schema_editor):
    compensation_history = apps.get_model("customers", "CompensationHistory")
    for history in compensation_history.objects.select_related("rule_version__rule").filter(
        rule_version__isnull=False,
        compensation_conflict_group="",
    ):
        history.compensation_conflict_group = history.rule_version.rule.conflict_group
        history.save(update_fields=["compensation_conflict_group"])


def reverse_backfill_compensation_conflict_group(apps, schema_editor):
    compensation_history = apps.get_model("customers", "CompensationHistory")
    compensation_history.objects.update(compensation_conflict_group="")


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_subscription_suspension_reason'),
        ('datasets', '0003_groundtruthcase'),
        ('operations', '0003_alarmtypeallowedsourcekind_and_more'),
        ('rules', '0003_rule_conflict_group_rule_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensationhistory',
            name='compensation_conflict_group',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.RunPython(
            backfill_compensation_conflict_group,
            reverse_backfill_compensation_conflict_group,
        ),
        migrations.AddConstraint(
            model_name='compensationhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('incident__isnull', False), models.Q(('compensation_conflict_group', ''), _negated=True), ('decision_status__in', ['approved', 'rejected'])), fields=('subscription', 'incident', 'compensation_conflict_group'), name='unique_final_compensation_per_sub_incident_group'),
        ),
    ]
