from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]
CORPUS_KEY = "processtwin-rag-corpus-v1"
CORPUS_VERSION = "1"
SYNTHETIC_NOTICE = (
    "Bu doküman ProcessTwin geliştirme ve test ortamı için hazırlanmış tamamen "
    "sentetik bir kaynaktır. Gerçek bir kurum, operatör veya yürürlükteki ticari "
    "politika belgesi değildir."
)
MULTICITY_SNAPSHOT_KEY = "multi-city-realism-v1-multi-city-realism-snapshot-v1"
MALTEPE_SNAPSHOT_KEY = (
    "maltepe-mvp-synthetic-dataset-maltepe-mvp-v1-maltepe-mvp-fixed-seed-v1-maltepe-mvp-snapshot"
)

MULTICITY_RULES = [
    "BB-DEGRADATION-QUALITY",
    "BB-FULL-OUTAGE-TIERED",
    "BB-PARTIAL-OUTAGE-PRORATED",
    "CAP-FLOOR-CONFLICT",
    "ELIG-CUSTOMER-IMPACT-CONFIRMED",
    "ELIG-SUBSCRIPTION-VALID",
    "EXCL-DUPLICATE-COMPENSATION",
    "EXCL-PENDING-CANCELLED",
    "EXCL-PLANNED-MAINTENANCE-NORMAL",
    "EXCL-PROTECTION-LOSS-ONLY",
    "EXCL-SUSPENSION-POLICY",
    "ME-AVAILABILITY-BREACH",
    "ME-DEGRADED-FAILOVER",
    "ME-FAILED-FAILOVER",
    "ME-JITTER-BREACH",
    "ME-LATENCY-BREACH",
    "ME-PACKET-LOSS-BREACH",
    "ME-SHORT-FAILOVER-INTERRUPTION",
    "MOD-GRADED-RESTORATION",
    "MOD-MAINTENANCE-OVERRUN",
    "MOD-RECURRING-INCIDENT",
    "MOD-RESTORATION-TARGET-BREACH",
    "MR-UNKNOWN-MISSING-EVIDENCE",
    "SLA-BACKUP-MISSING",
    "SLA-PATH-DIVERSITY-BREACH",
]

MULTICITY_ALARMS = [
    "ACCESS_NODE_UNREACHABLE",
    "BACKUP_LINK_UNAVAILABLE",
    "BACKUP_POWER_DEGRADED",
    "BANDWIDTH_UTIL_HIGH",
    "BNG_UNREACHABLE",
    "COMMERCIAL_POWER_LOSS",
    "COOLING_FAILURE",
    "DEDICATED_PORT_DOWN",
    "DISTRIBUTION_CABLE_DOWN",
    "DEVICE_RESOURCE_HIGH",
    "DSLAM_PORT_SATURATION",
    "DSLAM_UNREACHABLE",
    "DSL_LINE_QUALITY_DEGRADED",
    "DSL_PORT_DOWN",
    "DSL_RETRAIN_FREQUENT",
    "FAILOVER_UNSUCCESSFUL",
    "FIBER_CUT_SUSPECTED",
    "HIGH_TEMPERATURE",
    "LINK_FLAPPING",
    "LINK_PACKET_LOSS_HIGH",
    "METRO_AGG_UNREACHABLE",
    "OLT_UNREACHABLE",
    "ONT_DISCONNECT_SURGE",
    "OPTICAL_SIGNAL_LOSS",
    "OPTICAL_SIGNAL_LOW",
    "PON_CAPACITY_THRESHOLD",
    "PON_PORT_DOWN",
    "PRIMARY_PATH_DOWN",
    "SLA_LATENCY_BREACH",
    "SLA_PACKET_LOSS_BREACH",
    "UPLINK_DOWN",
]

GROUND_TRUTH_CASES = [
    "GT-MCR-NET-BNG-WIDE-001",
    "GT-MCR-NET-DSLAM-GROUP-001",
    "GT-MCR-NET-FAILED-FAILOVER-001",
    "GT-MCR-NET-FIBER-ROUTE-001",
    "GT-MCR-NET-FLAPPING-001",
    "GT-MCR-NET-METRO-AGG-001",
    "GT-MCR-NET-PON-PARTIAL-001",
    "GT-MCR-NET-POWER-ZONE-001",
    "GT-MCR-NET-SHARED-RISK-001",
    "GT-MCR-NET-UNKNOWN-RCA-001",
    "GT-MCR-RULE-BACKUP-MISSING-001",
    "GT-MCR-RULE-BB-DEGRADATION-001",
    "GT-MCR-RULE-DUPLICATE-001",
    "GT-MCR-RULE-FAILED-FAILOVER-001",
    "GT-MCR-RULE-FAILOVER-45S-001",
    "GT-MCR-RULE-FULL-OUTAGE-001",
    "GT-MCR-RULE-MAINT-OVERRUN-001",
    "GT-MCR-RULE-ME-LATENCY-001",
    "GT-MCR-RULE-MISSING-PRICE-001",
    "GT-MCR-RULE-MONTHLY-CAP-001",
    "GT-MCR-RULE-NOISE-NO-INCIDENT-001",
    "GT-MCR-RULE-PARTIAL-PRORATED-001",
    "GT-MCR-RULE-PAYMENT-SUSPENSION-001",
    "GT-MCR-RULE-PLANNED-NORMAL-001",
    "GT-MCR-RULE-PROTECTION-LOSS-001",
    "GT-MCR-RULE-PROVIDER-FAULT-SUSPENSION-001",
    "GT-MCR-RULE-RECURRING-MOD-001",
    "GT-MCR-RULE-SHARED-RISK-DIVERSITY-001",
    "GT-MCR-RULE-UNDER-30-001",
    "GT-MCR-RULE-UNKNOWN-ROOT-001",
]


def metadata(*, scope_type, rule_refs=None, alarm_refs=None, ground_truth_refs=None, source_file):
    return {
        "corpus_key": CORPUS_KEY,
        "corpus_version": CORPUS_VERSION,
        "synthetic_notice": SYNTHETIC_NOTICE,
        "rule_refs": rule_refs or [],
        "alarm_refs": alarm_refs or [],
        "ground_truth_refs": ground_truth_refs or [],
        "scope_type": scope_type,
        "source_file": source_file,
        "content_normalization_version": "lf-nfc-trim-final-newline-v1",
    }


DOCUMENTS = [
    {
        "document_code": "SYN-COMP-2026-OVERVIEW",
        "file_path": "documents/rules/syn_comp_2026_overview.md",
        "title": "SYN-COMP-2026 v1 sentetik telafi politikası genel bakış",
        "version": 1,
        "document_type": "rule_policy",
        "source_kind": "synthetic",
        "language": "tr",
        "scope_type": "multi_city",
        "snapshot_identifier": MULTICITY_SNAPSHOT_KEY,
        "valid_from": "2026-07-01T00:00:00+03:00",
        "valid_to": None,
        "rule_refs": MULTICITY_RULES,
        "alarm_refs": [],
        "ground_truth_refs": GROUND_TRUTH_CASES,
    },
    {
        "document_code": "SYN-COMP-2026-ELIGIBILITY",
        "file_path": "documents/rules/syn_comp_2026_eligibility.md",
        "title": "SYN-COMP-2026 v1 uygunluk ve dışlama kuralları",
        "version": 1,
        "document_type": "rule_policy",
        "source_kind": "synthetic",
        "language": "tr",
        "scope_type": "multi_city",
        "snapshot_identifier": MULTICITY_SNAPSHOT_KEY,
        "valid_from": "2026-07-01T00:00:00+03:00",
        "valid_to": None,
        "rule_refs": [
            "ELIG-SUBSCRIPTION-VALID",
            "ELIG-CUSTOMER-IMPACT-CONFIRMED",
            "EXCL-PENDING-CANCELLED",
            "EXCL-SUSPENSION-POLICY",
            "EXCL-PLANNED-MAINTENANCE-NORMAL",
            "EXCL-PROTECTION-LOSS-ONLY",
            "EXCL-DUPLICATE-COMPENSATION",
        ],
        "alarm_refs": [],
        "ground_truth_refs": [],
    },
    {
        "document_code": "SYN-COMP-2026-BROADBAND",
        "file_path": "documents/rules/syn_comp_2026_broadband.md",
        "title": "SYN-COMP-2026 v1 broadband telafi kuralları",
        "version": 1,
        "document_type": "rule_policy",
        "source_kind": "synthetic",
        "language": "tr",
        "scope_type": "multi_city",
        "snapshot_identifier": MULTICITY_SNAPSHOT_KEY,
        "valid_from": "2026-07-01T00:00:00+03:00",
        "valid_to": None,
        "rule_refs": [
            "BB-FULL-OUTAGE-TIERED",
            "BB-PARTIAL-OUTAGE-PRORATED",
            "BB-DEGRADATION-QUALITY",
        ],
        "alarm_refs": [],
        "ground_truth_refs": [
            "GT-MCR-RULE-FULL-OUTAGE-001",
            "GT-MCR-RULE-UNDER-30-001",
            "GT-MCR-RULE-PARTIAL-PRORATED-001",
            "GT-MCR-RULE-BB-DEGRADATION-001",
        ],
    },
    {
        "document_code": "SYN-COMP-2026-METRO-SLA",
        "file_path": "documents/rules/syn_comp_2026_metro_sla.md",
        "title": "SYN-COMP-2026 v1 Metro Ethernet ve SLA kuralları",
        "version": 1,
        "document_type": "rule_policy",
        "source_kind": "synthetic",
        "language": "tr",
        "scope_type": "multi_city",
        "snapshot_identifier": MULTICITY_SNAPSHOT_KEY,
        "valid_from": "2026-07-01T00:00:00+03:00",
        "valid_to": None,
        "rule_refs": [
            "ME-SHORT-FAILOVER-INTERRUPTION",
            "ME-AVAILABILITY-BREACH",
            "ME-LATENCY-BREACH",
            "ME-JITTER-BREACH",
            "ME-PACKET-LOSS-BREACH",
            "ME-FAILED-FAILOVER",
            "ME-DEGRADED-FAILOVER",
        ],
        "alarm_refs": [],
        "ground_truth_refs": [
            "GT-MCR-RULE-ME-LATENCY-001",
            "GT-MCR-RULE-FAILOVER-45S-001",
            "GT-MCR-RULE-FAILED-FAILOVER-001",
            "GT-MCR-RULE-BACKUP-MISSING-001",
        ],
    },
    {
        "document_code": "SYN-COMP-2026-REVIEW-CAPS",
        "file_path": "documents/rules/syn_comp_2026_review_caps.md",
        "title": "SYN-COMP-2026 v1 modifier, sınır ve inceleme kuralları",
        "version": 1,
        "document_type": "rule_policy",
        "source_kind": "synthetic",
        "language": "tr",
        "scope_type": "multi_city",
        "snapshot_identifier": MULTICITY_SNAPSHOT_KEY,
        "valid_from": "2026-07-01T00:00:00+03:00",
        "valid_to": None,
        "rule_refs": [
            "MOD-GRADED-RESTORATION",
            "MOD-RECURRING-INCIDENT",
            "MOD-MAINTENANCE-OVERRUN",
            "MOD-RESTORATION-TARGET-BREACH",
            "SLA-PATH-DIVERSITY-BREACH",
            "SLA-BACKUP-MISSING",
            "MR-UNKNOWN-MISSING-EVIDENCE",
            "CAP-FLOOR-CONFLICT",
        ],
        "alarm_refs": [],
        "ground_truth_refs": [
            "GT-MCR-RULE-RECURRING-MOD-001",
            "GT-MCR-RULE-MAINT-OVERRUN-001",
            "GT-MCR-RULE-MONTHLY-CAP-001",
            "GT-MCR-RULE-MISSING-PRICE-001",
            "GT-MCR-RULE-UNKNOWN-ROOT-001",
            "GT-MCR-RULE-SHARED-RISK-DIVERSITY-001",
            "GT-MCR-RULE-DUPLICATE-001",
        ],
    },
    {
        "document_code": "SYN-OPERATIONS-LIFECYCLE-2026",
        "file_path": "documents/procedures/syn_operations_lifecycle_2026.md",
        "title": "SYN operasyon olay yaşam döngüsü",
        "version": 1,
        "document_type": "procedure",
        "source_kind": "synthetic",
        "language": "tr",
        "scope_type": "global",
        "snapshot_identifier": None,
        "valid_from": None,
        "valid_to": None,
        "rule_refs": [],
        "alarm_refs": [],
        "ground_truth_refs": [
            "GT-MCR-NET-BNG-WIDE-001",
            "GT-MCR-NET-METRO-AGG-001",
            "GT-MCR-NET-FIBER-ROUTE-001",
            "GT-MCR-NET-POWER-ZONE-001",
            "GT-MCR-NET-PON-PARTIAL-001",
            "GT-MCR-NET-DSLAM-GROUP-001",
            "GT-MCR-NET-FLAPPING-001",
            "GT-MCR-NET-UNKNOWN-RCA-001",
            "GT-MCR-RULE-NOISE-NO-INCIDENT-001",
            "GT-MCR-RULE-PAYMENT-SUSPENSION-001",
            "GT-MCR-RULE-PROVIDER-FAULT-SUSPENSION-001",
        ],
    },
    {
        "document_code": "SYN-FAILOVER-MAINTENANCE-2026",
        "file_path": "documents/procedures/syn_failover_maintenance_2026.md",
        "title": "SYN failover ve planlı bakım prosedürü",
        "version": 1,
        "document_type": "procedure",
        "source_kind": "synthetic",
        "language": "tr",
        "scope_type": "global",
        "snapshot_identifier": None,
        "valid_from": None,
        "valid_to": None,
        "rule_refs": [],
        "alarm_refs": [],
        "ground_truth_refs": [
            "GT-MCR-NET-FAILED-FAILOVER-001",
            "GT-MCR-NET-SHARED-RISK-001",
            "GT-MCR-RULE-FAILOVER-45S-001",
            "GT-MCR-RULE-PROTECTION-LOSS-001",
            "GT-MCR-RULE-PLANNED-NORMAL-001",
            "GT-MCR-RULE-MAINT-OVERRUN-001",
        ],
    },
    {
        "document_code": "SYN-ALARM-CATALOG-2026",
        "file_path": "documents/alarm_catalog/syn_alarm_catalog_2026.md",
        "title": "SYN 2026 alarm kataloğu",
        "version": 1,
        "document_type": "technical_guide",
        "source_kind": "synthetic",
        "language": "tr",
        "scope_type": "multi_city",
        "snapshot_identifier": MULTICITY_SNAPSHOT_KEY,
        "valid_from": "2026-07-01T00:00:00+03:00",
        "valid_to": None,
        "rule_refs": [],
        "alarm_refs": MULTICITY_ALARMS,
        "ground_truth_refs": [],
    },
    {
        "document_code": "REFUND-001-V1-SOURCE",
        "file_path": "documents/compensation/refund_001_v1_source.md",
        "title": "REFUND-001 v1 sentetik kaynak metni",
        "version": 1,
        "document_type": "rule_policy",
        "source_kind": "synthetic",
        "language": "tr",
        "scope_type": "maltepe",
        "snapshot_identifier": MALTEPE_SNAPSHOT_KEY,
        "valid_from": "2026-01-01T00:00:00+03:00",
        "valid_to": "2026-07-14T23:59:59+03:00",
        "rule_refs": ["REFUND-001"],
        "alarm_refs": [],
        "ground_truth_refs": [],
    },
    {
        "document_code": "REFUND-001-V2-SOURCE",
        "file_path": "documents/compensation/refund_001_v2_source.md",
        "title": "REFUND-001 v2 sentetik kaynak metni",
        "version": 2,
        "document_type": "rule_policy",
        "source_kind": "synthetic",
        "language": "tr",
        "scope_type": "maltepe",
        "snapshot_identifier": MALTEPE_SNAPSHOT_KEY,
        "valid_from": "2026-07-15T00:00:00+03:00",
        "valid_to": None,
        "rule_refs": ["REFUND-001"],
        "alarm_refs": [],
        "ground_truth_refs": [],
    },
    {
        "document_code": "SYN-CAUSAL-ANALYSIS-2026",
        "file_path": "documents/procedures/syn_causal_analysis_2026.md",
        "title": "SYN 2026 nedensel alarm ve session analysis rehberi",
        "version": 1,
        "document_type": "technical_guide",
        "source_kind": "synthetic",
        "language": "tr",
        "scope_type": "global",
        "snapshot_identifier": None,
        "valid_from": None,
        "valid_to": None,
        "rule_refs": [],
        "alarm_refs": [],
        "ground_truth_refs": [],
    },
    {
        "document_code": "SYN-ALARM-CATALOG-2026",
        "file_path": "documents/alarm_catalog/syn_alarm_catalog_2026_v2.md",
        "title": "SYN 2026 alarm kataloğu v2",
        "version": 2,
        "document_type": "technical_guide",
        "source_kind": "synthetic",
        "language": "tr",
        "scope_type": "multi_city",
        "snapshot_identifier": MULTICITY_SNAPSHOT_KEY,
        "valid_from": "2026-07-01T00:00:00+03:00",
        "valid_to": None,
        "rule_refs": [],
        "alarm_refs": MULTICITY_ALARMS,
        "ground_truth_refs": [],
    },
    {
        "document_code": "SYN-COMP-2026-ELIGIBILITY",
        "file_path": "documents/rules/syn_comp_2026_eligibility_v2.md",
        "title": "SYN-COMP-2026 uygunluk ve kanıt kuralları v2",
        "version": 2,
        "document_type": "rule_policy",
        "source_kind": "synthetic",
        "language": "tr",
        "scope_type": "multi_city",
        "snapshot_identifier": MULTICITY_SNAPSHOT_KEY,
        "valid_from": "2026-07-01T00:00:00+03:00",
        "valid_to": None,
        "rule_refs": [
            "ELIG-CUSTOMER-IMPACT-CONFIRMED",
            "EXCL-PROTECTION-LOSS-ONLY",
            "MR-UNKNOWN-MISSING-EVIDENCE",
        ],
        "alarm_refs": [],
        "ground_truth_refs": [],
    },
]


def get_document_metadata(descriptor):
    return metadata(
        scope_type=descriptor["scope_type"],
        rule_refs=descriptor["rule_refs"],
        alarm_refs=descriptor["alarm_refs"],
        ground_truth_refs=descriptor["ground_truth_refs"],
        source_file=descriptor["file_path"],
    )
