# Generated by Django 5.2.16 on 2026-07-27 10:29

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('datasets', '0001_initial'),
        ('operations', '0001_initial'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation_code', models.CharField(max_length=100)),
                ('result_type', models.CharField(choices=[('eligible', 'Eligible'), ('not_eligible', 'Not eligible'), ('manual_review', 'Manual review'), ('insufficient_data', 'Insufficient data')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='draft', max_length=24)),
                ('proposed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('explanation', models.TextField(blank=True)),
                ('calculation_trace', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_evaluations', to='customers.customer')),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_evaluations', to='datasets.datasnapshot')),
                ('outage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_evaluations', to='operations.outage')),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensation_evaluations', to='rules.ruleversion')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_evaluations', to='customers.subscription')),
            ],
            options={
                'db_table': 'compensation_evaluation',
                'ordering': ['data_snapshot', '-created_at', 'evaluation_code'],
                'constraints': [models.UniqueConstraint(fields=('data_snapshot', 'evaluation_code'), name='unique_compensation_evaluation_code_per_snapshot'), models.UniqueConstraint(fields=('outage', 'subscription', 'rule_version'), name='unique_compensation_evaluation_per_outage_subscription_rule'), models.CheckConstraint(condition=models.Q(('proposed_amount__gte', Decimal('0.00'))), name='compensation_proposed_amount_non_negative')],
            },
        ),
    ]
