# Generated by Django 5.2.16 on 2026-07-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compensationevaluation',
            options={'ordering': ['data_snapshot', '-created_at', 'evaluation_code'], 'verbose_name': 'Telafi değerlendirmesi', 'verbose_name_plural': 'Telafi değerlendirmeleri'},
        ),
    ]
