# Generated by Django 5.2.16 on 2026-07-29 12:27

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0002_alter_compensationevaluation_options'),
        ('datasets', '0003_groundtruthcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_basis', models.CharField(blank=True, choices=[('contracted_monthly_price', 'Contracted monthly price'), ('billed_recurring_amount', 'Billed recurring amount'), ('campaign_adjusted_recurring_amount', 'Campaign adjusted recurring amount'), ('package_list_price', 'Package list price')], max_length=48)),
                ('selected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unrounded_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('decision', models.CharField(choices=[('eligible', 'Eligible'), ('ineligible', 'Ineligible'), ('manual_review', 'Manual review'), ('evidence_only', 'Evidence only')], max_length=32)),
                ('evidence_schema_version', models.PositiveIntegerField(default=1)),
                ('evidence_hash', models.CharField(max_length=64)),
                ('matched_conditions', models.JSONField(blank=True, default=list)),
                ('failed_conditions', models.JSONField(blank=True, default=list)),
                ('excluded_rules', models.JSONField(blank=True, default=list)),
                ('candidate_base_rules', models.JSONField(blank=True, default=list)),
                ('applied_modifiers', models.JSONField(blank=True, default=list)),
                ('formula_inputs', models.JSONField(blank=True, default=dict)),
                ('cap_floor_trace', models.JSONField(blank=True, default=list)),
                ('manual_review_reasons', models.JSONField(blank=True, default=list)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('finalized', models.BooleanField(default=True)),
                ('compensation_evaluation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decision_evidence', to='compensation.compensationevaluation')),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_evidence_records', to='datasets.datasnapshot')),
            ],
            options={
                'verbose_name': 'Karar kanıtı',
                'verbose_name_plural': 'Karar kanıtları',
                'db_table': 'compensation_decision_evidence',
                'ordering': ['data_snapshot', '-created_at'],
            },
        ),
    ]
