# Generated by Django 5.2.16 on 2026-07-29 12:27

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0003_decisionevidence'),
        ('rules', '0003_rule_conflict_group_rule_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionevidence',
            name='rule_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decision_evidence_records', to='rules.ruleset'),
        ),
        migrations.AddField(
            model_name='decisionevidence',
            name='selected_rule_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decision_evidence_records', to='rules.ruleversion'),
        ),
        migrations.AddConstraint(
            model_name='decisionevidence',
            constraint=models.UniqueConstraint(fields=('data_snapshot', 'evidence_hash'), name='unique_decision_evidence_hash_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='decisionevidence',
            constraint=models.CheckConstraint(condition=models.Q(('final_amount__gte', Decimal('0.00'))), name='decision_evidence_final_amount_non_negative'),
        ),
    ]
