# Generated by Django 5.2.16 on 2026-08-03 12:55

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models

import apps.rag.models

LEGACY_EMBEDDING_COUNT = 74
GEMINI_PROVIDER = "gemini"
GEMINI_MODEL = "gemini-embedding-2"
GEMINI_DIMENSIONS = 768
GEMINI_EMBEDDING_VERSION = "asymmetric-retrieval-v1"
GEMINI_PROMPT_VERSION = "rag-section-aware-document-v2"


def backfill_gemini_embeddings(apps, schema_editor):
    DocumentChunk = apps.get_model("rag", "DocumentChunk")
    DocumentChunkEmbedding = apps.get_model("rag", "DocumentChunkEmbedding")
    chunks = DocumentChunk.objects.all().order_by("pk")
    embedded = list(chunks.exclude(embedding__isnull=True))
    if not embedded:
        return
    if len(embedded) != LEGACY_EMBEDDING_COUNT or chunks.count() != len(embedded):
        raise RuntimeError("legacy_embedding_set_is_partial")

    records = []
    for chunk in embedded:
        metadata = chunk.metadata or {}
        if chunk.embedding_provider != GEMINI_PROVIDER:
            raise RuntimeError("legacy_embedding_provider_mismatch")
        if chunk.embedding_model != GEMINI_MODEL:
            raise RuntimeError("legacy_embedding_model_mismatch")
        if chunk.embedding_dimensions != GEMINI_DIMENSIONS:
            raise RuntimeError("legacy_embedding_dimensions_mismatch")
        if chunk.embedding_version != GEMINI_EMBEDDING_VERSION:
            raise RuntimeError("legacy_embedding_version_mismatch")
        if metadata.get("prompt_version") != GEMINI_PROMPT_VERSION:
            raise RuntimeError("legacy_embedding_prompt_version_mismatch")
        if metadata.get("content_hash") != chunk.content_hash:
            raise RuntimeError("legacy_embedding_content_hash_mismatch")
        if len(chunk.embedding) != GEMINI_DIMENSIONS:
            raise RuntimeError("legacy_embedding_vector_dimensions_mismatch")
        records.append(
            DocumentChunkEmbedding(
                document_chunk_id=chunk.pk,
                provider=GEMINI_PROVIDER,
                model=GEMINI_MODEL,
                dimensions=GEMINI_DIMENSIONS,
                embedding_version=GEMINI_EMBEDDING_VERSION,
                prompt_version=GEMINI_PROMPT_VERSION,
                content_hash=chunk.content_hash,
                embedding=chunk.embedding,
            )
        )
    DocumentChunkEmbedding.objects.bulk_create(records)
    if DocumentChunkEmbedding.objects.filter(provider=GEMINI_PROVIDER).count() != len(records):
        raise RuntimeError("legacy_embedding_backfill_count_mismatch")


def irreversible_backfill(apps, schema_editor):
    raise migrations.IrreversibleError(
        "Multiple embedding provider sets cannot be safely restored to one legacy column."
    )


def add_vector_dimensions_constraint(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "ALTER TABLE rag_document_chunk_embedding "
        "ADD CONSTRAINT rag_chunk_embedding_vector_dims "
        "CHECK (vector_dims(embedding) = dimensions)"
    )


def remove_vector_dimensions_constraint(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "ALTER TABLE rag_document_chunk_embedding "
        "DROP CONSTRAINT IF EXISTS rag_chunk_embedding_vector_dims"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('mock', 'Mock'), ('gemini', 'Gemini'), ('ollama', 'Ollama')], max_length=80)),
                ('model', models.CharField(max_length=160)),
                ('dimensions', models.PositiveIntegerField(default=768)),
                ('embedding_version', models.CharField(max_length=80)),
                ('prompt_version', models.CharField(max_length=120)),
                ('content_hash', models.CharField(max_length=64, validators=[apps.rag.models.validate_sha256])),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('document_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_records', to='rag.documentchunk')),
            ],
            options={
                'db_table': 'rag_document_chunk_embedding',
                'ordering': ['document_chunk', 'provider', 'model', 'embedding_version'],
                'indexes': [models.Index(fields=['provider', 'model', 'embedding_version', 'prompt_version'], name='rag_emb_descriptor_idx'), models.Index(fields=['document_chunk', 'provider', 'model'], name='rag_emb_chunk_provider_idx'), models.Index(fields=['content_hash'], name='rag_emb_content_hash_idx')],
                'constraints': [models.UniqueConstraint(fields=('document_chunk', 'provider', 'model', 'dimensions', 'embedding_version', 'prompt_version', 'content_hash'), name='rag_chunk_embedding_identity_uniq'), models.CheckConstraint(condition=models.Q(('dimensions', 768)), name='rag_chunk_embedding_dimensions_768')],
            },
        ),
        migrations.RunPython(backfill_gemini_embeddings, irreversible_backfill),
        migrations.RunPython(
            add_vector_dimensions_constraint,
            remove_vector_dimensions_constraint,
        ),
    ]
